### ISSUE TITLE
force layout should have option to set random number generator seed

### ISSUE THREAD

**Issue by ghost** [d3/d3#1002]
Because the force layout uses Math.random() to generate random numbers, the layout looks different every time a page is reloaded. It would be useful to add the option to set a random number seed so that there is an option of reproducible layouts.

**Comment by mikeazo** [comment]
@cmap I know this is old, but thought I'd share something I found. https://github.com/davidbau/seedrandom seems to work pretty well for making the force layout more or less deterministic. Here is a JSFiddle I adapted: http://jsfiddle.net/s8pcecka/2/

Unfortunately, it isn't completely cross-browser. Chrome and Firefox resulted in very similar layouts. Safari was fairly different. Haven't done much IE testing.

**Comment by coli** [comment]
Wow that is incredible, thanks for sharing.
