### ISSUE TITLE
Add source maps

### ISSUE THREAD

**Issue by ansman** [d3/d3#1012]
Source maps can be incredibly useful to debug code in production.

For example jQuery just started including source maps with their distribution: http://blog.jquery.com/2013/01/09/jquery-1-9-rc1-and-migrate-rc1-released/

**Comment by natevw** [comment]
xref: https://github.com/mbostock/smash/issues/15 or https://github.com/mbostock/d3/issues/2220

**Comment by estekhin** [comment]
Having a source map published along with the minimized js would help me too.

**Comment by mbostock** [comment]
D3 4.0 is now built using [Rollup](http://rollupjs.org), which has a `--sourcemap` option. I haven’t enabled it by default yet, though.
