### ISSUE TITLE
d3.selection.remove() removes DOM elements but doesn't clear the selection.

### ISSUE THREAD

**Issue by sym3tri** [d3/d3#1041]
For example:

```
var s = d3.selectAll('svg');
s.remove();
// actual dom nodes are removed.
console.log(s);
// s selection still contains references to all the removed dom nodes.
```

Reassigning your selection variable as such would clear out the node references.

```
var s = d3.selectAll('svg');

s = s.remove();
// or
s = d3.selectAll('svg')
```

Based on what the docs say:
_"Generally speaking, you should stop using selections once you've removed them, because there's not currently a way to add them back to the document."_

...this seems like intended behavior, but I'm just curious what kind of use cases require not clearing the selection? I would think clearing out the selection would be a sensible default.

Also this seems like it could lead to memory leaks if the selections are not properly disposed/reassigned.

**Comment by nomi-ramzan** [comment]
Hi @mbostock is there any way to remove all children except last child.
