### ISSUE TITLE
d3 does not run in web worker threads

### ISSUE THREAD

**Issue by adambom** [d3/d3#1053]
D3 will not run inside a web worker thread. The reason is because workers don't have access to the DOM and d3 has hard dependencies on the DOM API.

Not a huge deal, but it would be nice to have access to parts of the library that don't require DOM access, like scales.

Here's what I'm doing:

``` javascript
// in main.js
var w = new Worker('worker.js');

// in worker.js
importScripts('d3.js'); 
// Fails with error: 'Uncaught ReferenceError: CSSStyleDeclaration is not defined'

self.onmessage = function (e) {
    var scale = d3.scale.linear();
    // do stuff
};
```

**Comment by clschnei** [comment]
:+1: To @p3k 's solution for shimming `window`/`document`.
