### ISSUE TITLE
Strange tweening of CSS percentage values

### ISSUE THREAD

**Issue by cvincent** [d3/d3#1070]
I may be misunderstanding how tweening transitions values, but I was able to code up a pretty simple reproduction of the issue:
http://bl.ocks.org/4748295/608ac60850d55b5c29f5e0da030bf49033634a5f

I would expect that the bars would start without a transition since they `enter` at the correct values to begin with. Instead, it transitions from a large, unexpected value to the correct value upon entry. Further, when the data updates (wait about 5 seconds), the transition displays the same funkiness, going from some large, unexpected value to the new value, rather than from the old value to the new value.

My guess is there's an issue with reading the correct value from a CSS percentage.

**Comment by veltman** [comment]
Here's an example using `styleTween` to interpolate a percentage: http://bl.ocks.org/veltman/ad5aaa518266ead2cc55
