### ISSUE TITLE
Adding rounded corners to `d3.svg.arc`

### ISSUE THREAD

**Issue by bm-w** [d3/d3#1131]
Hi Mike,

For some project, I needed to implement rounded corners for the `d3.svg.arc` shape generator. For the purpose, I added a `cornerRadius` method in a custom-built version of D3. _All good._

Now, I'm wondering if you're interested in adding it back to the main code. If so, I'd like to get some input in how to solve the problematic case with large corner radii relative to the arc's width. See here for three possible approaches (obviously in addition to not handling the problematic case at all): http://bl.ocks.org/bm-w/5124918

These three approaches handle large radii up to a certain point. Obviously, they all break down again when a truly ridiculously large corner radius is used (i.e. larger than half the difference between outer and inner radius). I'm not sure if such cases would require special handling as well.

_NB. As the issue never occurred in the project, I did not yet implement the special case. I'd be perfectly willing to, but would want a design decision first._

**Comment by andrey-asp** [comment]
- [ ] 

- [ ]
