### ISSUE TITLE
d3.behavior.zoom on IE browser

### ISSUE THREAD

**Issue by carlos-gva** [d3/d3#1146]
Hi.
I have some problems when I use d3.behavior.zoom event with drag on Internet Explorer.
I have a svg with several elements. Each element has a xlink:href associated, and when I call the d3.behavior.zoom, I lose the possibility of executing the xlink:href. When I click on an element, nothing happens. 
If I set .on(“mousedown.zoom”, null), the links work fine, but obviously I lose the drag.
How can I fix this?
Regards,
Carlos.

**Comment by errold32** [comment]
This is still a problem in d3 3.5.5
