### ISSUE TITLE
d3.v3.js does not work if document encoding is not UTF8

### ISSUE THREAD

**Issue by ikriv** [d3/d3#1195]
On line 1285 of d3.v3.js we find some non-ASCII characters related to the definition of Pi.
var π = Math.PI, ε = 1e-6

While it may look cool to define variables named with Greek letters, it creates issue in HTML documents encoded in encodings other than UTF-8. If document encoding is not utf-8, and if D3JS scripts are included without explicit charset="utf-8" attribute, an "illegal character" error will pop up.

Possible resolutions may include:
- stick to ASCII in variable names (probably the best option)
- add charset="utf-8" to all script tags in all examples

**Comment by JJ** [comment]
I keep getting the `SyntaxError: An invalid or illegal string was specified` here http://geneura-papers.github.io/2015-ea-languages/#/bf
with source
```
<!doctype html>
<html lang="en">

	<head>
		<meta charset="utf-8">

	<!-- more stuff -- >
		<!-- d3 here -->
		<script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
```
The file is utf-8 codified. In fact, when the file was *not* utf8 coded I didn't get that error. Any help?
