### ISSUE TITLE
Data passed to functions on child objects (such as event listeners, attr, etc) gets stale copies of bound models

### ISSUE THREAD

**Issue by chriserickson** [d3/d3#1319]
The data object passed to functions on sub-elements of a data bound selections is a copy of the real data object and becomes stale when data is re-bound.

For example:
d3.selectAll(...)
.data([myData])
.append('svg:g')
.append('svg:rect')
.on('click', function(item) { alert(item.details) })

// clicking shows item.details

d3.selectAll(...).data([newModels])

// clicking will show the original details, even though they've changed in the new models.

if on('click') is bound to the root element (the group in this case) then the click handler DOES get the updated data, however you can't register a click event on a group element in IE 10.

A further example can be seen here:
http://jsfiddle.net/8y93F/

**Comment by coli** [comment]
Hi, .select() worked but not selectAll(), do you know why?
