### ISSUE TITLE
d3.svg.brush shouldn't preventDefault on brushstart.

### ISSUE THREAD

**Issue by jasondavies** [d3/d3#1321]
For consistency, a similar technique to d3.behavior.{drag,zoom} should be used instead.

**Comment by mizzao** [comment]
I just came across this thread when updating from D3 3.1 to 3.4+, and would note for others that a zoomable area with a brush requires the `brushstart` event to manually call `d3.event.sourceEvent.stopPropagation()` or similar to prevent the zoom from also being activated while the brush is being dragged.
