### ISSUE TITLE
Nodes hop away in force directed

### ISSUE THREAD

**Issue by ftrotter** [d3/d3#1357]
When a use mouses over a node in the default force-directed example, the nodes move away from the mouse. 

Essentially the nodes subtly "avoid" being captured via a click event. This problems becomes more noticeable as graphs become larger and larger and for large graphs with large nodes, the problem makes the graph layout very difficult to use. 

However, the problem itself can be replicated by simply using a very large graph data set, with the default code from the example. Here is a video of that problem:

http://screencast.com/t/jXejnCwGN45

Thanks for all of your hard work and an amazing library. 

Regards,
-FT

**Comment by mbostock** [comment]
I made some improvements in d3-force, but I’m not sure if there’s anything else to do here, so closing.

**Comment by ftrotter** [comment]
That is the right choice. We introduced some latency and am looking forward to all of the improvements coming in d3. Thanks for the great project!
