### ISSUE TITLE
Force Layout In D3.js gets very slow when a node is filled with an Image using pattern.

### ISSUE THREAD

**Issue by Ankit-Bhatia** [d3/d3#1376]
HI ,
 I have implemented a basic Dots implementation of Force layout in D3 .
It runs absolutely fine until I attach each circle / node with a image pattern.
When I do that the page almost stops and the transitions get unresponsive and so does my system, I see 100% CPU utilization .
I am not sure If I did this right or is there any other method of attaching Images to nodes in D3.

here is the jsfiddle for it http://jsfiddle.net/Ankitb/eaGhB/

regards
Ankit

**Comment by KirillChokparov** [comment]
Pattern is really slow thing with image.
See good fast implemention: http://bl.ocks.org/mbostock/950642

**Comment by ronyrun** [comment]
@KirillChokparov  this example works with a unique image and is still slow with several biggers images.

Hello, @artzub do you have an example on your pocket ?

@Ankit-Bhatia did you find a solution, I encounter the same behavior.
I'm looking for a Force layout with Canvas out of SVG.

**Comment by KirillChokparov** [comment]
Hello,
See my site www.visual-data/demo
At the bottom there the scheme with nodes, links and different images on nodes.
I have tested it: 2000 nodes each with image plus 4000 links work perfectly on ordinary comp.

Best regards,
Kirill Chokparov

Отправлено с iPad

**Comment by ronyrun** [comment]
Thank you @KirillChokparov !!

**Comment by ronyrun** [comment]
@KirillChokparov would you share the code or not ?? I'm unable to understand Russian :)

**Comment by KirillChokparov** [comment]
Of course. You can take d3.js from site and see how that work. Could you do this?

**Comment by ronyrun** [comment]
Yes I'm gonna try.
Thank you very much !!!

**Comment by KirillChokparov** [comment]
Let me know please when you succeed.

**Comment by KirillChokparov** [comment]
The file might be obfuscated. So let me know and I will give you the origin version.

**Comment by ronyrun** [comment]
the file is OK.
Some characters are not readable but it's obiously some Russians words :)

**Comment by KirillChokparov** [comment]
I am glad! Good luck!

**Comment by artzub** [comment]
@ronyrun Hello! I made a simple [example](http://codepen.io/artzub/pen/oXaVpz) for you. Shows how to use canvas with the force layout and the clip and the drawImage functions of the 2d context of  the canvas.

**Comment by artzub** [comment]
@ronyrun If you want the drag behavior then you should calculate the mouse positions on each tick or maybe other moment and find a node under the mouse cursor, and set to the node fixed = true, and to change node.x and node.y. For fast finding nodes you can use colors masks for an each node into other hidden canvas with using pixes data.

**Comment by ronyrun** [comment]
thank you @artzub !!
