### ISSUE TITLE
Unable to drag nodes in a force layout graph when zooming is added

### ISSUE THREAD

**Issue by brzpegasus** [d3/d3#1412]
I took the code from the [_Miserables_ force-directed graph example](http://bl.ocks.org/mbostock/4062045) and added zooming.

With version `3.1.10` of d3, I can zoom with the mouse wheel, and also drag individual nodes within the graph to reposition them.

But with version `3.2.7`, while zooming still works, dragging individual nodes results in dragging the entire graph instead:

https://gist.github.com/brzpegasus/97a2427ff0ba57a979d2#file-force-layout-with-zoom-L19

Was this an intended change? I'm relatively new to d3 so it's possible I'm just missing something critical in the code for this to work with the latest version.

**Comment by mael-morel** [comment]
@brzpegasus Thanks, working

**Comment by brzpegasus** [comment]
@mael-morel :+1:

**Comment by syairazi** [comment]
Thanks that working for me.
