### ISSUE TITLE
d3.scale.log(), 0 in domain

### ISSUE THREAD

**Issue by furufors** [d3/d3#1420]
My first bug-report ever so bear with me!

This concerns d3.scale.log() with a value of zero in the domain.

When the input domain contain 0 the javascipt-engine will crash, due to calling log(0). Since log(0) is mathematically undefined, it would be nice if d3 handled this special case instead of causing a total crash.

Using: Version 3.2.7

**Comment by angieskazka** [comment]
hi Mike! i am trying to follow your hint [here](https://groups.google.com/d/msg/d3-js/QCOk9Or7vWI/YTh22CFFeY8J) and use a polylog scale:

`scale = d3.scale.log().domain([-5.0, -0.1, 0.1, 100.0]).range([-200, 0, 0, 200]);`

here is what i get:

`scale(-5)`
-200 // looks fine, same for all values below -0

`scale(5)`
NaN // same for values -0, 0 and all values above

I would expect it to go polylog and return values above 0. Am i wrong or is there a bug? (d3.js v3.4.13)
Thank you!

**Comment by mbostock** [comment]
A log scale that includes or crosses zero in the domain is not supported, so this won’t work and my earlier hint is obsolete.

I suppose you could implement your own custom scale to do this, but you’d still need to be careful about showing the discontinuity in the axis.

Better probably would be to draw your data twice with two different log scales (one positive, one negative) and then clip it, or to use a pow scale, or to otherwise avoid the problem.

**Comment by angieskazka** [comment]
Thanks for the reply, Mike. I will try to extend d3 with a custom scale, which handles the gap, and share it if successful. 

Drawing the whole thing twice is not the best for me because my data markers can go from positive to negative range and back, i want to keep (or, rather, fake) the continuity. Imagine a country goes from positive GDP change to negative and back.

**Comment by mgold** [comment]
This is probably better suited for the mailing list, but... what happens if a country has a GDP of exactly zero? I think this means that logarithms are the wrong mathematical model for your data. As Mike, suggests, try a power scale, which handles negatives implicitly:

````js
d3.scale.sqrt()(-4)
-2
````

**Comment by angieskazka** [comment]
thanks, Max @mgold. 
We're talking not about GDP as absolute value but relative to that of the previous year. So ΔGDP. Now, if ΔGDP this year is zero (or 0 ± a little ε), then we leave the marker at zero, as simple as that. When it's negative we go negative. Even more interesting is that the marker can go "continuously" from positive to negative domain and back, as it happens in real life.

So i have to fake continuity and the part 0 ± ε where the strange thing happens. See how it was done in the [old version here](http://www.gapminder.org/world/#$majorMode=chart$is;shi=t;ly=2003;lb=f;il=t;fs=11;al=30;stl=t;st=t;nsl=t;se=t$wst;tts=C$ts;sp=5.59290322580644;ti=1982$zpv;v=0$inc_x;mmid=XCOORDS;iid=phAwcNAVuyj1jiMAkmq1iMg;by=ind$inc_y;mmid=YCOORDS;iid=0AkBd6lyS3EmpdFY5Z0QzTzRRbzJ1VXdqdGVyNE0tcFE;by=ind$inc_s;uniValue=8.21;iid=phAwcNAVuyj0XOoBL_n5tAQ;by=ind$inc_c;uniValue=255;gid=CATID0;by=grp$map_x;scale=log;dataMin=194;dataMax=96846$map_y;scale=log;dataMin=-10.9551;dataMax=20$map_s;sma=49;smi=2.65$cd;bd=0$inds=). Shift the time slider to see how the bubbles travel and may fall on zero.

![image](https://cloud.githubusercontent.com/assets/3648190/5836926/fc424f56-a17a-11e4-832c-1043b4f62807.png)

Yes, we abuse the scale. We redefine the definition of "logarithmic"  near and below zero. Of a logarithm we just need a characteristic distortion on the rest of the axis.

Agree with Mike's comment on that there should be a visible discontinuity on the scale to give a hint of that.
 
Power scale would deliver a completely different picture (i tried different exponent values <1) and is not reflecting the nature of data correctly. Particularly i need to keep the fact that every 2x or 10x increase take the same space on the screen, and that is a log. 

See log above and power below (exp=0.5):
![image](https://cloud.githubusercontent.com/assets/3648190/5836729/2f12d52e-a179-11e4-9a0d-3e97eecfa653.png)

**Comment by mgold** [comment]
I suppose that image is reasonable, except perhaps that you have positive thousandths but negatives go straight to hundredths.

**Comment by kylebrandt** [comment]
@angieskazka Did you ever get a custom scale built for this? Looking for 0 support, and negative support would be a nice bonus as well. http://stackoverflow.com/questions/32052285/d3-scale-post-processing

**Comment by mgold** [comment]
The SO link 404s.

You can always do a wrapper function. The details will depend on what you want, but for example:
```js
function myScale(x){
  if (x === 0){
    return 0;
  }else{
    return myRealScale(Math.abs(x))
  }
}
```

Alternatively, use clamping to force the value onto the domain:
```js
> myScale = d3.scale.log().domain([1, 100])
> myScale(0)
NaN
> myScale.clamp(true)
> myScale(0)
0
```

**Comment by angieskazka** [comment]
@kylebrandt yes, i did make it work!
see the demo here: http://static.gapminderdev.org/vizabi/feature/axis-labeler/preview_pages/_examples/axis-labeler.html

Use [Q] and [E] to browse through examples of how it works with different input domains.

The updated code is here:
https://github.com/Gapminder/vizabi/blob/develop/src/plugins/d3.genericLogScale.js

also you might find this to be useful:
https://github.com/Gapminder/vizabi/blob/develop/src/plugins/d3.axisWithLabelPicker.js

sorry for lack of documentation, it's still work in progress
please PM me if anything is unclear
