### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by panickos** [d3/d3#1444]
Using d3 version: "3.2.8" on Chrome for Mac OS X and I get the following error:

Uncaught SyntaxError: Unexpected token ILLEGAL /dev/ui/dashboard/third-party/d3.js:1362

var π = Math.PI, ε = 1e-6, ε2 = ε \* ε, d3_radians = π / 180, d3_degrees = 180 / π;

It looks like chrome doesn't like the greek characters.

Here's how it looks in Chrome:
var Ï€ = Math.PI, Îµ = 1e-6, Îµ2 = Îµ \* Îµ, d3_radians = Ï€ / 180, d3_degrees = 180 / Ï€;

I haven't tried any other browsers.

**Comment by thomasvanlankveld** [comment]
Would it be a good idea to implement a custom error thrown checking `document.characterSet`?

It feels like this mistake is too easy to make to just get `Uncaught SyntaxError: Unexpected token ILLEGAL ` when it happens, I think a more descriptive error message would be in place here.

However, I'm not sure if we can also check in JavaScript whether this was used:

```html
<script charset="utf-8" src="d3.js"></script>
```

**Comment by PaulBrinkley** [comment]
I have my meta charset included as above, and I'm still getting this Unexpected token error. What else could be going wrong?

**Comment by jfarid27** [comment]
I'm piggybacking this as well. I'm using Mac Chrome v42.0.2311.135 and D3 version 3.5.5. My html...

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
    <body>
        <script charset="utf-8" src="node_modules/d3/d3.js"></script>
        <script>
            console.log(d3)
        </script>
    </body>
</html>
```

The subsequent error is on line 1261 in d3.js, Unexpected token illegal. I could just be messing up the html, but it seems like I've covered both cases and I still am getting an error. 

A workaround for now is just using the minified version.

**Comment by tomkur** [comment]
Also, this makes problems with some utf-8-unfriendly tools, please see [this issue](https://github.com/facebook/flow/issues/521) in [facebook/flow](https://github.com/facebook/flow).

Maybe it would be better to avoid this sort of problems already in d3 by using ascii identifiers? Even though greek letters look really cool there :smile:

**Comment by mbostock** [comment]
The Unicode variable names are going away in D3 4.0.

**Comment by tomkur** [comment]
Great, thanks!
