### ISSUE TITLE
d3.sum returns 0 for [null, null, null]

### ISSUE THREAD

**Issue by nrabinowitz** [d3/d3#1447]
This may be expected behavior, but I had expected `d3.sum` to work like SQL `SUM`, in that given an array of `null`s it would return `null`. Instead, it returns `0`.

**Comment by pstanton** [comment]
// will return null if empty or all elements are null (much better)
d3.sumNullsafe = function(array, f) {
    var s = null, n = array.length, a, i = -1;
    if (arguments.length === 1) {
      while (++i < n)
    	  if (!isNaN(a = array[i]))
    		  s = s == null ? a : s + a;
    } else {
      while (++i < n)
    	  if (!isNaN(a = f.call(array, array[i], i)))
    		  s = s == null ? a : s + a;
    }
    return s;
  };
