### ISSUE TITLE
Possible to have multiple styling for d3.svg.line segments?

### ISSUE THREAD

**Issue by john-clarke** [d3/d3#1456]
What is the best way to implement multiple formats for a single d3.svg.line() element? For instance, I'd like to format the first part of a line with solid line and the tail end with a dashed line. The only way I can think of is the render the line twice and inverse an undefined section.

**Comment by petepolack** [comment]
Another issue with drawing two lines with different `defined` functions is that lone data points are not rendered on a line. Consider the following values: `[1.1, 1.2, 1.3, 0.4, 1.4]`. If I draw one line defined for values `>1` and another defined for values `<1`, the last two values will not be displayed—they are not lines, after all.

**Comment by mbostock** [comment]
That’s true, although you can still render empty lines, say by using SVG’s [stroke-linecap](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap): round property, or by explicitly drawing the data points on top of the line.
