### ISSUE TITLE
d3.geom.voronoi should automatically resolve coincident points.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#1503]
Detecting and resolving coincident points when using the voronoi layout is a pain. The common solution is to offset each point by a small random jitter. However, if you are very unlucky, this could still result in coincident points. In addition, random jitter gives a nondeterministic layout, so it might be better if the voronoi layout resolved these automatically, say by laying coincident points out in a small circle.

**Comment by micahstubbs** [comment]
:+1:
