### ISSUE TITLE
Append and insert should use the selected element’s document to create elements.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#1533]
Currently selection.append and selection.insert use the captured global document (d3_document) to create new elements. When using a document different from the one D3 was instantiated in, as in Node.js, this can cause an error:

``` js
var d3 = require("d3"),
    jsdom = require("jsdom");

var document = jsdom.jsdom("<html><body></body></html>");

d3.select(document).select("body").append("div"); // Error: Wrong document
```

Instead of using d3_document to create the new element, append and insert should use `this.ownerDocument` on the parent element. This ensures that the element always matches the document to which it is to be appended.

Note that you can work around this issue by creating the elements yourself:

``` js
d3.select(document).select("body").append(function() { return document.createElement("div"); });
```

**Comment by jonashaag** [comment]
This breaks if `this.ownerDocument` is `undefined`, which may happen if the element in question has not been added to the DOM yet. In that case, we should fall back to `d3_document`:

```js
  function d3_selection_creator(name) {
    return typeof name === "function" ? name : (name = d3.ns.qualify(name)).local ? function() {
      return (this.ownerDocument || d3_document).createElementNS(name.space, name.local);
    } : function() {
      return (this.ownerDocument || d3_document).createElementNS(this.namespaceURI, name);
    };
  }
```
