### ISSUE TITLE
Missing d3.geo.path perimeter method.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#1556]
For symmetry with path.area / d3.geo.area. Also, rename d3.geo.length to d3.geo.perimeter (since we can’t override function.length).

**Comment by Fil** [comment]
Is this not implemented by https://github.com/d3/d3-geo#geoLength ? In which case the issue could be closed as well as #1688.

**Comment by mbostock** [comment]
@Fil No. d3.geoLength is spherical length, *path*.length would be planar after projecting. The only real issue is deciding the name since *function*.length is reserved. However, we could just define it using Object.defineProperty and then it would work…
