### ISSUE TITLE
make dragging behavior optional for layout/force.

### ISSUE THREAD

**Issue by blq** [d3/d3#1583]
I think dragging should be an optional behavior for layout/force. 
I consider dragging part of a UI behavior. And similarly to how algorithms should strive to separate from graphics I think dragging should be opt-in for a layout algorithm.

Dragging couples to mouse with document specific code and also brings in the entire selector adding a lots of code-weight to a custom build.

(I'm making a custom custom build of D3 with my own graphics, doesn't use the selector and without explicit interactivity).

Regards
/ Fredrik Blomqvist

**Comment by mbostock** [comment]
In D3 4.0, the new d3-force module has no dependency on d3-drag.
