### ISSUE TITLE
Add a "How to contribute" section to the d3js.org website

### ISSUE THREAD

**Issue by kottmann** [d3/d3#1606]
D3js.org is really well done and get new users started quickly, but for me it left the question on how to contribute back to project open.

I would like to suggest to add a page to d3js.org which outlines this process in a few sentences, e.g. open an issue on github, post proposals for new features in the google group, etc.

**Comment by adarshhs** [comment]
@mbostock  Can you please add this 'CONTRIBUTING' section to master branch (all branches) so that its easy for the contributors to find it?
