### ISSUE TITLE
Feature Request: let tickPadding take a function argument

### ISSUE THREAD

**Issue by adonomay** [d3/d3#1641]
Long tick labels can overlap, making the text hard to read.  See http://jsfiddle.net/6XPpe/5/

```
var xAxis = d3.svg.axis()
.scale(xScale)
.orient("bottom")
.tickPadding(function(d, i) {
  // some logic here to vary the tick padding by index, e.g.
  return i % 2 ? 10 : 20;
 });
```

There are other ways to accomplish the same end: increase the spacing between or width of columns, tilt the axis text to be diagonal, truncate the axis labels and add ellipses in the tickFormat function, attach the text elements separately from the axis method chain and position them dynamically there, and so on.  Those all have readability or code clarity drawbacks though (or in the case of wider columns, size restrictions can make this a no-go).  

Arguably the specificity of this use case makes it a bad candidate for d3 as opposed to a higher-level charting library (<a href="http://peltiertech.com/Excel/Charts/Staggered.html">MS excel, for example, has hacks for this</a>).  But supporting a function in tickPadding wouldn't be hard and wouldn't break anything, I think. And there may be other use cases for this feature that make sense on a proper visualization level as well.

**Comment by roydon-tj** [comment]
@mbostock  If I deliberately want to break a text into something like this is there a better way? I am modifying the function to do this, but its not so generic

![screen shot 2015-03-02 at 6 22 24 pm](https://cloud.githubusercontent.com/assets/8610709/6444961/0a3f0d62-c127-11e4-8b89-e9ee9f5e6746.png)
