### ISSUE TITLE
Text-wrapping routine.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#1642]
It might be useful to expose this as d3.svg.textWrap?

``` js
function wrap(text, width) {
  text.each(function() {
    var text = d3.select(this),
        words = text.text().split(/\s+/).reverse(),
        word,
        line = [],
        lineNumber = 0,
        lineHeight = 1.1, // ems
        y = text.attr("y"),
        dy = parseFloat(text.attr("dy")),
        tspan = text.text(null).append("tspan").attr("x", 0).attr("y", y).attr("dy", dy + "em");
    while (word = words.pop()) {
      line.push(word);
      tspan.text(line.join(" "));
      if (tspan.node().getComputedTextLength() > width) {
        line.pop();
        tspan.text(line.join(" "));
        line = [word];
        tspan = text.append("tspan").attr("x", 0).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word);
      }
    }
  });
}
```

Live example: http://bl.ocks.org/mbostock/7555321

**Comment by acauamontiel** [comment]
And for big words?

**Comment by michaelcrubenstein** [comment]
Noticed a problem if the text has a leading space. In this case (word = words.pop()) is an empty string, which is treated as false. Solution would be either to explicitly test for a value of undefined, or trim the text before splitting it.

**Comment by davidjmcclelland** [comment]
Tried this (mbostock's original example wrap function) on a responsive layout. i.e. chart width and height percentage instead of pixel values. Resizing browser window immediately redraws the text without the linebreaks. Everything else scales smoothly.

**Comment by vijithassar** [comment]
updated the [plugin](https://github.com/vijithassar/d3-textwrap) for d3.js v4

**Comment by curran** [comment]
This is also a nice module that implements text wrapping https://github.com/d3plus/d3plus-text

This was extracted from the larger project https://github.com/alexandersimoes/d3plus

**Comment by KathyReid** [comment]
+1 to this being part of core d3.js. I've bumped up against this issue several times now. How can I help / assist?

**Comment by mbostock** [comment]
I have no plans to add this as a core feature. I’d recommend contributing to one of the existing D3 plugins that implements this feature or, if you prefer, to develop a new one.
