### ISSUE TITLE
Click events in zoom behavior are suppressed in IE as it triggers mousemove on mousedown 

### ISSUE THREAD

**Issue by spootze** [d3/d3#1658]
The zoom behavior seems to [listen for mousemove to discern clicks from dragging](https://github.com/mbostock/d3/blob/master/src/behavior/zoom.js#L170-L180). IE 9-11 on the other hand seems to trigger mousemove immediately on mousedown which in turn ends up suppressing all click events inside the element for which zoom behavior is called.

This issue is demonstrated [here](http://jsfiddle.net/ErQL3/).

Maybe setting the dragged flag should be delayed on IE? I couldn't find references as to how browser detection is done in D3.

**Comment by wal0x** [comment]
any news on this bug ?

**Comment by mbostock** [comment]
See d3/d3-zoom#65.
