### ISSUE TITLE
IsotypeLayout (Contribution?)

### ISSUE THREAD

**Issue by Fannon** [d3/d3#1667]
Hello there,

thanks for this great library!

I've written a very rough D3.js Isotype Layout.
It takes tables and converts it into a data structure fitting to create Isotype Graphics. What's special is that it creates a data entry for every "Icon".

Here are some Screenshots:

![2013-11-25_-_07-46-17](https://f.cloud.github.com/assets/470980/1752663/49d5406a-6627-11e3-9696-470e60cc9add.png)

![](http://up.fannon.de/img/2015-08-08_10_30_13.png)

The Code to the Layout is here: https://github.com/Fannon/isomatic/blob/master/js/isotypeLayout.js

So if you're interested I could commit this to D3.js. Of course there would be some work to do prior to this. Also it would be nice to know if i thought/did it the right way.

Greets,
Simon

**Comment by markvital** [comment]
Any update on this, would love to use one?

**Comment by Fannon** [comment]
Hi!

You could include this file: https://github.com/Fannon/isomatic/blob/master/src/js/isotypeLayout.js

And it should be available. Creating Isotype graphics is not trivial however, see https://github.com/Fannon/isomatic/blob/master/src/js/views/GraphView.js how we've implemented them. There are two examples / mode in this file.. a simpler and a one more advanced one.

Simon

**Comment by markvital** [comment]
Great tool, thanks you.
It would be cool to support fractions, like in this example: https://twitter.com/markvitals/status/594651285464350721

I'm looking into Isomatic. Great idea with layouts, and import to SVG.
I'm working on a similar tool, just for knowledge visualization: http://annalogy.co. Looking for ways to integrate Isotype into it.

**Comment by Fannon** [comment]
Hello Mark,

fractions are supported, but only through scaling the image size. The example you've provided looks very nice, I'd prefer this to scaling ;)

Please note that isomatic supports an "advanted" layouting algorithm, too. When browsing through the source code, you'll find both the simple and advanced version.

The actual d3.js layouter works for both.

Great to hear you like it! You're project sounds interesting!

Simon
