### ISSUE TITLE
d3.scale.log, setting base doesn't seem to be working.

### ISSUE THREAD

**Issue by trevithj** [d3/d3#1696]
Changing the base of a log scale doesn't appear to do anything. For example:

```
  var s = d3.scale.log();
  s.base(10)(1000);
  s.base(16)(4096);
  s.base( 2)(8);
```

Expected a result of 3 in all cases. Actual output was:

```
  2.9999999999999996
  3.6123599479677737
  0.9030899869919434
```

Last tried in version 3.4.1

**Comment by guilhermesimoes** [comment]
Does this mean that a log scale will behave the same way as long as it has the same domain and range, regardless of its base? I was trying to plot points in a log-2 axis and a log-10 axis and they look the same. I'm probably misunderstanding something...

I even found [this question on SO][1] trying to achieve the same task but it hasn't been answered.

Here's [the question's JSFiddle][2].

[1]: http://stackoverflow.com/questions/28289719/d3-log-scale-base-not-making-an-effect
[2]: http://jsfiddle.net/esm4kLwg/3/

**Comment by mbostock** [comment]
Yes, the output of the scale is the same, so they look the same. The only difference is the ticks.
