### ISSUE TITLE
d3.js examples not working in chrome

### ISSUE THREAD

**Issue by ghost** [d3/d3#1698]
Hello everyone,
I tried running d3.js examples, but the charts would only display in the Firefox browser. The charts were not displayed at all in the Chrome browser. I have tried many things, such as starting Chrome with the extension --disable-web-security and other extensions, none of which worked. This is just a simple example from the d3.js website. Does the solution involve installing your own web server?

Here is an example of Firefox running the index.html file: 
![image](https://f.cloud.github.com/assets/6406010/1917544/45ca154a-7d9c-11e3-9da8-badd20d1aaab.png)

Here is Chrome: 
![image](https://f.cloud.github.com/assets/6406010/1917548/63bdae86-7d9c-11e3-8607-a3bd53a633da.png)

**Comment by Xarrow** [comment]
The same origin policy in Chrome
