### ISSUE TITLE
Formatting currency

### ISSUE THREAD

**Issue by macduy** [d3/d3#170]
Hi

I'm familiar with using d3.format to format numbers, however I was wondering, what do I need to do to include a currency symbol, e.g. '$'? So far, I only got this...

``` javascript
var format = d3.format(".2f");
...
d3.select(el).selectAll("text")...
      .text(format)
```

Thanks!

**Comment by cilphex** [comment]
Does it only work with the "$" symbol?

**Comment by mbostock** [comment]
You need to use “$” in the format string, but your locale can define the currency symbol as “£”, as in the [en-GB locale](https://github.com/mbostock/d3/blob/master/src/locale/en-GB.js).
