### ISSUE TITLE
Collapsible Tree(d3.v3.min.js): Multiple parent nodes for child.

### ISSUE THREAD

**Issue by paritalavenkat** [d3/d3#1700]
Hi, Can I have two separate parents links for a child. In the below example Doctor1 should also have a link to Hospital,currently Doctor1 has link only to Group Practice1.

{
"name": "Hospital",
"children": [
{"name": "Group Practice1",
"children": [
{"name": "Doctor1"},
{"name": "Doctor2"},
{"name": "Doctor3"}
]
},
{"name": "Group Practice3"},
{"name": "Group Practice2"}
]
}

**Comment by RazumO** [comment]
Here you can find out my solution(without collapsibility), based on **d3.js tree layout**: https://github.com/RazumO/MultipleParentsTree

**Comment by shijocj** [comment]
how can I modify d3 hierarchy.js file to support "multiple parent for a node" with collapsible and expandable functionalities .
