### ISSUE TITLE
Missing `rangeRoundPoints`?

### ISSUE THREAD

**Issue by salomvary** [d3/d3#1760]
If there is `rangeBands` and `rangeRoundBands`, shouldn't there be a `rangeRoundPoints`?

Use case: I'm drawing a line chart using `ordinal.rangePoints` and want to draw vertical background tick lines using the same ordinal scale, and they should not be antialiased. Right now there seems to be no other way of doing this than doing "manual" rounding on the scale's output.

**Comment by e-kaya** [comment]
Hi, I am not sure whether I should report this here but I am getting an error when I try the code snippet where an example rangeRoundPoints function is presented. For example when I try this on the console,
var m = d3.scale.ordinal().domain([1, 2, 3, 4]).rangeRoundPoints([0, 100]);
The error message I am getting is: Uncaught TypeError: d3.scale.ordinal(...).domain(...).rangeRoundPoint is not a function(…).

**Comment by mbostock** [comment]
Your example works for me in 3.5.10 (using the console on d3js.org). Is it possible that you are not using [version 3.5](https://github.com/mbostock/d3/releases/tag/v3.5.0) or later?

**Comment by e-kaya** [comment]
Hi Mike, yes, it's my bad. I noticed that I have been using 3.0.8. Sorry for taking your time and thank you for the quick response.
