### ISSUE TITLE
attrTween function not called for all modified nodes of a transition

### ISSUE THREAD

**Issue by coli** [d3/d3#1774]
I'm using a custom transition.attrTween() function.

For code:

```
 root.selectAll('g').transition().attrTween('d', customFunc).selectAll('path').attr('d', calcPoints)
```

customFunc is called on 'g' nodes, and not 'path' nodes. However, there is an internal 'attr.d' attrTween function that does get's called on the 'path' nodes.

I want my attrTween function to be called instead of that internal function, I looked at selection.attr and it does not look like I can override that default function there

**Comment by Vishnupriyachirappa** [comment]
I am drawing an arc with path in svg and i want to animate but string interpolator calculating flag valvues how should avoid
