### ISSUE TITLE
The scope of d3.behavior.drag?

### ISSUE THREAD

**Issue by natevw** [d3/d3#1793]
This ticket follows a rabbit trail off of #1786

Backstory: I'm using `d3.behavior.drag` basically as a cross-platform foundation (Pointer Events pull request planned ;-) for a feature that ends up being like `d3.svg.brush` but within HTML and would also love to have something even more generic for general touch wrapping.

It's clear that the intended use is more of a "drag a target around" than my use case (e.g. I'm having to fix up the origin so that I get locations _within_ the target rather than its parent) and for having a general multitouch handler there's some other missing/broken pieces. I'm wondering if this is "in scope" for d3.behavior.drag or maybe I should just be using [PointerEvents polyfill](https://github.com/Polymer/PointerEvents).

One of the "core" problems with d3.behavior.drag multitouch is that the touchend handler doesn't pay attention to which touch was ended. But that leads back to a few other assumptions: that the drag is meant to be called on a moveable child (rather than a brush-like parent situation, which would need to _distinguish_ between events from different fingers and has to manually fix up origin), that only one finger will "touchstart" at once, that "touchcancel" won't get called…

Kind of a laundry list, and don't mean to sound like I'm griping — for practical purposes once I worked around #1388 (which is not really the behavior's fault) it is working for my main case right now. Just trying to figure out what my long-term "go-to" tool should be for this stuff: d3.behavior.drag, PointerEvents polyfill, or make a third-party "pointers behavior" plugin…

**Comment by wim82** [comment]
we also have this strange issue, when we swipe a UIWebView with 4 fingers (switch apps) - it fires a touchcancel & not a touchend. Since we have some tooltip dragging enabled on a linechart, it eventually breaks the scroll.

I'm unable to provide an example at the moment, but just wanted to share already.. will investigate this more closely soon.
