### ISSUE TITLE
Mozilla TypeError: mutating the [[Prototype]] of an object will cause your code to run very slowly

### ISSUE THREAD

**Issue by blankdots** [d3/d3#1805]
I'm working on Mozilla Aurora v 30.0a2 and I noticed this Warning today appearing in both Firefox Dev tools and Firebug. 

"TypeError: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"

I've switched to Chrome and there was no such warning in the console.

To be sure that it is not something inside my web application I've tested several examples provided in https://github.com/mbostock/d3/wiki/Gallery and they all seem to give out the same warning.

I know it is just a warning but still, I thought I should bring it up.

**Comment by mbostock** [comment]
ES6 supports extending arrays using the class syntax (`class d3_Selection extends Array`), so we’ll be able to use that instead of reassigning \_\_proto\_\_.

**Comment by crxgames** [comment]
Can confirm this on Firefox 35.0 fresh instead without plugins and with firebug/web developer toolbar.

**Comment by pornel** [comment]
Firefox 38.0a1 complains about:

```js
var d3_subclass = {}.__proto__ ? function(object, prototype) {
    object.__proto__ = prototype;
  }
```

**Comment by fvpDev** [comment]
__proto__...deprecated?

**Comment by leninmehedy** [comment]
Firefox38.5.2 complains about:
```javascript
var d3_subclass = {}.__proto__ ? function(object, prototype) {
    object.__proto__ = prototype;
  }
```

**Comment by mbostock** [comment]
In [D3 4.0](https://github.com/mbostock/d3/tree/4), [d3-selection](https://github.com/d3/d3-selection) no longer uses array subclassing, so there’s no Prototype modification warning.

**Comment by r0b-** [comment]
Is there a chance to get a fix for version 3.x?

**Comment by mbostock** [comment]
No, sorry.

**Comment by gabrielrtakeda** [comment]
Same with Firefox 45.0.2
<img width="919" alt="screen shot 2016-04-11 at 19 25 57" src="https://cloud.githubusercontent.com/assets/5435389/14444369/5ac7513e-001b-11e6-8678-0d3551d0f35e.png">

**Comment by shapovalovts** [comment]
The same in FF 45.0.1.

**Comment by sjoerd222888** [comment]
The same in FF 46.0.1
