### ISSUE TITLE
nodejs ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by artzub** [d3/d3#1816]
I try to use d3.xhr on nodejs. But when I run **node server.js** I catch an error

```
n:\projects\artzub.com\d3\clearspending\node_modules\d3\d3.js:1852
oresend", "progress", "load", "error"), headers = {}, request = new XMLHttpReq
                                                                    ^
ReferenceError: XMLHttpRequest is not defined
    at d3_xhr (n:\projects\artzub.com\d3\clearspending\node_modules\d3\d3.js:1852:114)
```

My code is very simple (server.js):

```
var d3 = require("d3");

d3.xhr(url, function(){});
```

I've tried to fix this error (d3.js position [1852:114]):

```
...
request = new d3_window.XMLHttpRequest(), responseType = null;
...
```

But caught another error:

```
n:\projects\artzub.com\d3\clearspending\node_modules\d3\d3.js:1907
      request.open(method, url, true);
              ^
TypeError: Object #<XMLHttpRequest> has no method 'open'
```

What am I doing wrong?

**Comment by curran** [comment]
Has anyone figured out a way to run Node.js-based unit tests for modules that depend on d3.xhr? It looks like this requires the code to actually run in the browser, so I'm investigating [Karma](https://karma-runner.github.io/0.12/index.html), but I would prefer to have the tests run in Node with a straightforward `mocha` invocation.

I tried to introduce the XMLHttpRequest global as follows:

```
XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
```

This did create the global variable, and d3.xhr did try to use it, however the following error was thrown:

```
Error: the string "Protocol not supported." was thrown, throw an Error :)
```
