### ISSUE TITLE
d3.median is slow, O(n log n) instead of O(n)

### ISSUE THREAD

**Issue by ChALkeR** [d3/d3#1833]
Hello again.

d3.median is calculated using `d3.quantile(array.sort(d3_ascending), .5)`. That is as crazy as sorting the whole array just to find the maximum.

Median should be implemented using a [selection algorithm](http://en.wikipedia.org/wiki/Selection_algorithm), which is able to find k-th smallest number in O(n) for an unordered array.

`Array.prototype.sort` of course can not have complexity better than O(n log n) for an average case: https://en.wikipedia.org/wiki/Sorting_algorithm#Comparison_of_algorithms.

Also see:
http://www.cplusplus.com/reference/algorithm/nth_element/ 
http://en.wikipedia.org/wiki/Quickselect — average O(n), worst-case O(n^2).
http://en.wikipedia.org/wiki/Median_of_medians — average O(n), worst-case O(n).

**Comment by 8613545800459** [comment]
？ ；？？？？？？！！“““？；？

**Comment by Fil** [comment]
For people who need more juice it's possible to build a faster d3.median using [mourner/quickselect](https://github.com/mourner/quickselect) https://bl.ocks.org/Fil/1092338525a5e6a7237b31453ed6e313

Agree with @mbostock it's not mandatory to include this in the core of d3 if the cost in maintainance and bytes is too high.

With thanks to @mourner; errors are mine obviously, specfically I run the partialSort twice to get two values, there's probably better.

**Comment by mourner** [comment]
Thanks for mentioning my library! For anyone in need of an existing module that does median/quantile/multi-quantile really fast, check out `simple-statistics` — last year I submitted a PR that makes it really fast for these tasks (based on the quickselect algorithm) https://github.com/simple-statistics/simple-statistics/pull/146. Quantile and median are `O(N)` and multi-quantile is `O((N + K) log K)`.

**Comment by Fil** [comment]
Thank you Vladimir. I made a similar block for simplestatistics here:
https://bl.ocks.org/Fil/238bd6b9453e87f2c75182c13a477509
