### ISSUE TITLE
Selecting html elements whose id starts with a number throws error

### ISSUE THREAD

**Issue by gtsop** [d3/d3#1858]
Reproduced here:
http://jsfiddle.net/EXKv5/

**Comment by ziyuang** [comment]
@jasondavies Doesn't work if an ID is like "333".

**Comment by lgpage** [comment]
I assume this Is this still unsupported?
Trying to work with node-uuid is proving frustrating at the moment.

BTW, html5 has removed this restriction:
https://www.w3.org/TR/html5/dom.html#the-id-attribute

**Comment by mbostock** [comment]
D3 just calls through to your browser’s underlying W3C Selectors API implementation, so whether or not it works depends entirely on your browser.

**Comment by lgpage** [comment]
Fair enough. Thanks for the info.

**Comment by joseacti** [comment]
May be you can try querySelector('[id = "123"])
