### ISSUE TITLE
Brush misbehaves with overlayed elements containing data

### ISSUE THREAD

**Issue by Bringer128** [d3/d3#1890]
When a brush container contains an element with data, mouse events on that element are treated as being on the "resize e" rectangle.

I've created a fiddle demonstrating the issue here: http://jsfiddle.net/t9SDL/1/
And a fiddle demonstrating the correct behaviour here: http://jsfiddle.net/t9SDL/2/

To reproduce: 
- Create a small horizontal extent with the mouse
- Drag from a point on the path element that is not under the extent.

Behaviour experienced: The extent resizes as if we were dragging the edge of the extent, despite how far the mouse is from the extent.
Expected behaviour: The extent redraws from the mouse location.

The salient difference between the two is how the data gets into the path element.

The failing case:

```
.datum(lineData)
.attr("d", lineFunction)
```

The working case:

```
.attr("d", lineFunction(lineData))
```

Looking at the d3 source, this line appears to have the problem:

```
    function brushstart() {
      var target = this, eventTarget = d3.select(d3.event.target), event_ = event.of(target, arguments), g = d3.select(target), resizing = eventTarget.datum(), resizingX = !/^(n|s)$/.test(resizing) && x, resizingY = !/^(e|w)$/.test(resizing) && y, dragging = eventTarget.classed("extent"), dragRestore = d3_event_dragSuppress(), center, origin = d3.mouse(target), offset;
```

Specifically, the part:

```
resizing = eventTarget.datum()
```

In the fiddle's case, the eventTarget is the path element which can have data attached.

I assume this code is using whether data is attached to detect whether the event target was one of the ".resize rect" elements that get generated.

**Comment by mbostock** [comment]
I think the brush could be implemented a bit more robustly. Like, it should probably look at the class of the element clicked on brushstart, rather than assuming that the event target’s data is a string that may contain a resize direction.
