### ISSUE TITLE
voronoi.triangles fails with square rectangle

### ISSUE THREAD

**Issue by isaomatsunami** [d3/d3#1895]
d3.geom.voronoi().triangles returns only one triangle when given 4 points that consists of rectangle.

var h = 100, w = 200, vertices = [[0,0],[w,0],[0,h],[w,h]];
console.log( d3.geom.voronoi().triangles(vertices).length );  // shows 1
vertices = [[0,0],[w,0],[0,h],[w,h + 0.001]];
console.log( d3.geom.voronoi().triangles(vertices).length );  // shows 2

And I hope any accessor to edges(.r/.l) variables inside, especially info about index-based triangles.

**Comment by Fil** [comment]
This issue can be closed.

If anything, it is to be reopened on d3-voronoi; but see https://github.com/d3/d3-voronoi/pull/13 which claims another computation method, and https://github.com/d3/d3-voronoi/pull/12 which "solves" it by adding jitter.

**Comment by 199600375707** [comment]
Issue3d/3d image_1895
