### ISSUE TITLE
d3js blocked by Content-Security-Policy

### ISSUE THREAD

**Issue by uu1101** [d3/d3#1904]
When the server sends a restrictive Content-Security-Policy header,

``` .http
Content-Security-Policy: default-src 'self'; script-src 'self'; img-src 'self'
```

the following error comes up in Firefox:

```
Content Security Policy: The page's settings blocked the loading of a resource: An attempt to call JavaScript from a string (by calling a function like eval) has been blocked
```

and a similar to that of Chrome:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

The culprit is the following code, where a Function object is being created:

``` .js
    dsv.parse = function(text, f) {
      var o;
      return dsv.parseRows(text, function(row, i) {
        if (o) return o(row, i - 1);
        var a = new Function("d", "return {" + row.map(function(name, i) {
          return JSON.stringify(name) + ": d[" + i + "]";
        }).join(",") + "}");
        o = f ? function(row, i) {
          return f(a(row), i);
        } : a;
      });
    };
```

The following replacement looks sensible to me, am I missing something?

``` .js
    dsv.parse = function(text, f) {
      var o;
      return dsv.parseRows(text, function(row, i) {
        if (o) return o(row, i - 1);
        var a = function(d) {
          var r = {};
          row.forEach(function(name, i) {
            r[name] = d[i];
          });
          return r;
        };
        o = f ? function(row, i) {
          return f(a(row), i);
        } : a;
      });
    };
```

Best regards,
uu1101.

-- edit: fixed code

**Comment by magicmathmandarin** [comment]
I have been trying to use D3.js at work, where there is very strict IT security policy.  I have not been able to use <script src="https://d3js.org/d3.v4.min.js"></script> at all.  Nothing at all shows up.  I tried referencing the D3 library in my local computer but still not working. 

However, I found a very limited way to get version 3 ( <script src="https://d3js.org/d3.**v3**.min.js"></script> to work in my work environment where every data has to be hard coded.  If I link data using d3.csv then it doesn't work again.   Having to hard code all the data makes it difficult to use this great library.

Can you please help?  Thanks!

**Comment by curran** [comment]
@magicmathmandarin Have you tried UNPKG? For example:

 * v3: `<script src="https://unpkg.com/d3@3.5.17/d3.min.js"></script>`
 * v4: `<script src="https://unpkg.com/d3@4.13.0/build/d3.min.js"></script>`
 * v5: `<script src="https://unpkg.com/d3@5.0.0/dist/d3.min.js"></script>`

**Comment by magicmathmandarin** [comment]
Hi Curran,

Thanks for the suggestion.  These alternative references work in my
personal computer.  But they still don't work in my work computer.  My work
is a very large organization.  And yet I don't know anyone who has
successfully  used D3 :(

**Comment by sabatale** [comment]
Unfortunately this is still an issue for most companies with a CSP policy, I got this one today:

```
function objectConverter(columns) {
--
8057 | return new Function("d", "return {" + columns.map(function(name, i) {
8058 | return JSON.stringify(name) + ": d[" + i + "] \|\| \"\"";
8059 | }).join(",") + "}");
8060 | }
```

**Comment by curran** [comment]
Related PR https://github.com/d3/d3-dsv/pull/87

**Comment by m10812021** [comment]
I found that the latest version of d3.js contains innerHTML, which causes csp problems. Is there any solution?
