### ISSUE TITLE
d3.min.js != d3.js

### ISSUE THREAD

**Issue by sibnerian** [d3/d3#1909]
I installed d3 as a bower component. When I load `bower_components/d3/d3.js` (the 
main' script for bower), I get errors like `ReferenceError: Can't find variable: d3`. However, when I change it to `bower_components/d3/d3.min.js` it works fine.

This seems just plain weird. Is there any reason why the minified version behaves differently?

**Comment by Tiagojdferreira** [comment]
Having the same issue and adding:
```html
<meta charset="UTF-8">
```
Did not fix my problem.
