### ISSUE TITLE
Improve inline docs on albersUSA

### ISSUE THREAD

**Issue by jorgecarleitao** [d3/d3#1984]
In [albers-usa](https://github.com/mbostock/d3/blob/master/src/geo/albers-usa.js), some numbers are not documented (e.g. line 44, 45):

``` javascript
return (y >= .120 && y < .234 && x >= -.425 && x < -.214 ? alaska
        : y >= .166 && y < .234 && x >= -.214 && x < -.115 ? hawaii
        : lower48).invert(coordinates); 
```

It could be helpful to those trying to create custom projections to know where these numbers are coming from. I.e. from where we can get them from the shapefile/topojson? what do they mean on the final projection?

This is also valid for lines 110 onwards. The constants are difficult to understand.

**Comment by anuragagarwal561994** [comment]
Link for albers-usa is broken

**Comment by mbostock** [comment]
@anuragagarwal561994 If you’re referring to the comment that was made two years ago by the OP the source for d3.geoAlbersUsa is now [in d3-geo](https://github.com/d3/d3-geo/blob/master/src/projection/albersUsa.js).

**Comment by Fil** [comment]
The numbers are the relative coordinates of the bounding-boxes of the rectangles encompassing Alaska and Hawaii, in the AlbersUsa referential (scale and translate).

The rectangles are visible on https://bl.ocks.org/mbostock/5629120 (with Puerto Rico as a bonus). The [0,0] in this referential is the center of the image (i.e. [480,250]). I have outlined all these elements on http://bl.ocks.org/Fil/7723167596af40d9159be34ffbf8d36b
