### ISSUE TITLE
style.setProperty in IE8

### ISSUE THREAD

**Issue by macduy** [d3/d3#199]
IE8 complains when running

``` javascript
d3.select(element).attr('style', ...)
```

because this.style.setProperty is undefined.

Is there a known work-around for this?

**Comment by Samuel1989** [comment]
Hey Guys,

I am also experiencing this issue with IE 11.

Is there a recommended fix for this issue? I have attempted the polyfill solution above but it has not worked. Do you officially support IE? 

Thank you,
Sam
