### ISSUE TITLE
`d3.uri()` convenience method to load raster images as base64 data uri for href="<data URI>" hard embedding

### ISSUE THREAD

**Issue by hugolpz** [d3/d3#2095]
### Demo solution:

**HTML & svg implementation [demoed there](http://fiddle.jshell.net/xGUsu/116/) ([v/116/](http://fiddle.jshell.net/xGUsu/116/show/light/)).** It may deserve to push d3 integration further by building a new but simple `d3.uri()` [Requests > Convenience method](https://github.com/mbostock/d3/wiki/Requests#convenience-methods) using existing the [d3.xhr constructor](https://github.com/mbostock/d3/wiki/Requests#d3_xhr) ([code](https://github.com/mbostock/d3/blob/master/d3.js#L1922-L2013)).

Benefice is an all-in-svg code, easing sharing. 
### Currently

D3js generates SVG with [linked images](http://bl.ocks.org/hugolpz/c59f79a9f52e3897c129) : 

```
svg.append("image")
  .attr("xlink:href", "file.jpg")
  .attr({ width: 960,height: 500 })
  .attr("class", "bg");
```

producing :

```
<image xlink:href="file.jpg" width="960" height="500" class="bg"></image>
```

While this approach is valid, it results into svg elements actually missing the rasters data, which is externalized.
### Proposal

1/ to load the image.jpg's data ; 2. convert into a data URI string (`var str`) using JS. 3/ to replace `<image href="file.jpg" ... ></image>` by `<image href="data:image/png;base64,<dataURI>" ... ></image>`. See demo code.
### Note
1. I didn't tested if the data_uri type extension should really match the image's extension.
2. The JS code to do 1. (base64 conversion) have been [discussed here](http://stackoverflow.com/a/26595628/1974961) while 1 & 2 are [discussed there](http://stackoverflow.com/questions/28788468/). **The script successfully replace the href link by an href with valid and working data uri, so the image is really embedded.**

**Comment by hugolpz** [comment]
Note: I think the `ns` are conflicting. I got client side d3js where the data uri doesn't work on chrome, and after I download it via svg-crowbar it then displays the data uri image in chrome. Weird and out of my league.

**Comment by hugolpz** [comment]
```
var converterEngine = function (input) { // fn BLOB => Binary => Base64 ?
    var uInt8Array = new Uint8Array(input),
          i = uInt8Array.length;
    var biStr = []; //new Array(i);
    while (i--) { biStr[i] = String.fromCharCode(uInt8Array[i]);  }
    var base64 = window.btoa(biStr.join(''));
    return base64;
};

var getImageBase64 = function (url, callback) {
    var xhr = new XMLHttpRequest(url), img64;
    xhr.open('GET', url, true);                   // url is the url of a PNG/JPG image.
    xhr.responseType = 'arraybuffer';
    xhr.callback = callback;
    xhr.onload  = function(){
        img64 = converterEngine(this.response); // convert BLOB to base64
        this.callback(null,img64);
    };
    xhr.onerror = function(){ callback('B64 ERROR', null); };
    xhr.send();
};
```

**Comment by lifejuggler** [comment]
Does this code work?
