### ISSUE TITLE
d3.behavior.{zoom,drag} should pan with inertia

### ISSUE THREAD

**Issue by mbostock** [d3/d3#2096]
Most slippy map interfaces now use inertia, so we should too.

**Comment by TWiStErRob** [comment]
+1, I would want to set on/off and friction
(maybe turn off by setting friction to a value which means infinitely sticky)

**Comment by huned** [comment]
@mbostock have you seen the implementation of inertial drag behavior here? http://bl.ocks.org/pjanik/5872514

**Comment by Silviusconcept** [comment]
I add a transition() on zoom callback and voilà.
