### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'transition'  d3.js, line 8600 character 5

### ISSUE THREAD

**Issue by ramseyfeng** [d3/d3#2156]
Hi Mike, 
I'm trying to upgrade d3.js from version '3.3.13' to '3.5.2'.
I ran into the issue as described in issue title.
It only happens in IE browser.
It pretty much the same issue as https://github.com/mbostock/d3/issues/1491, but i don't think it is fixed already.
Do you have any suggestion on this?

Thanks in advance!

Ramsey

**Comment by mbostock** [comment]
Duplicate of #2174.
