### ISSUE TITLE
Gantt / Bar Range Layout request

### ISSUE THREAD

**Issue by CaitlinWeb** [d3/d3#2215]
I'd really like to see Gantt charts, or bar charts with ranges, as part of D3. I've gotten one to work using https://github.com/dk8996/Gantt-Chart but it's not generic enough. It would be great to see this as a Layout.

In the future I may do a pull request if I end up creating a more generic version of dk8996's chart. But I was wondering if new layouts are being developed, and if so, I hope this type could be included.

**Comment by roydondsouza** [comment]
@CaitlinWeb waiting for this feature. Let's see what @mbostock has to say about this.

**Comment by mgold** [comment]
You should probably take this to the [mailing list](https://groups.google.com/forum/#!forum/d3-js).

You're probably best keeping it as an independent plugin that waiting on this project. D3 isn't a graphing library; it's a data-driven DOM manipulation library.

**Comment by mbostock** [comment]
My inclination is this should be a plug-in or an example, rather than a core feature.

**Comment by dk8996** [comment]
@mbostock Is there anything I  can do to make it more like a plug-in?

**Comment by mgold** [comment]
I'd start with fully understanding [Towards Reusable Charts](http://bost.ocks.org/mike/chart/) and then studying the Layouts in the D3 source.

**Comment by mbostock** [comment]
@dk8996 It appears you already have implemented it as a plug-in and example. :) Afraid I don’t have time at the moment to give you any more helpful feedback.

**Comment by sjp700** [comment]
I've been working on a visual planning tool that can also generate a Gantt chart.  It is still work in progress but if there is sufficient interest I could start this as a project in github (although I  haven't done this before).  The main example is on http://www.buyingcircles.co.uk/  and others at http://www.pmd3.co.uk/.    The chart and 'handsontable' have a direct link up with an MS SQL database for real time planning .    I've tried to implement a clip path to stop the panning going over the y-axis but can't get it to work with a grouped element with 'rect' and text!
