### ISSUE TITLE
Closure Externs for D3?

### ISSUE THREAD

**Issue by shripadk** [d3/d3#224]
Is it possible to have a externs file available for d3 so that for those of us who want to use d3 along with closure can easily use the library? d3 variables/functions are rewritten when compiled in ADVANCED mode.

**Comment by pallosp** [comment]
I've created externs for d3 v4.2.7 and shared them at http://pastebin.com/A4an42b2

I've also been experimenting with compiling d3 together with its caller using advanced optimizations. I replaced the bootstrapping code with a simpler version that Closure Compiler understands, blacklisted 171 properties that would break after renaming, and suppressed a few warning classes.

The results are promising. Besides the simple optimizations the compiler can also remove roughly 60% of the unused code. The only blocker is that the function inlining pass breaks some functions that declare variables after their first use (https://github.com/d3/d3/issues/2978).

**Comment by sfinktah** [comment]
@pallosp you are an absolute legend.   I needed externs for d3-hexbin so here those are, although not with the same level of detail, but working.

    var d3_hexbin = {
        "version": {},
        "hexbin": function () {},
    };
    d3_hexbin.hexbin.prototype.hexagon = function(radius) {};
    d3_hexbin.hexbin.prototype.centers = function() {};
    d3_hexbin.hexbin.prototype.mesh = function() {};
    d3_hexbin.hexbin.prototype.x = function(_) {};
    d3_hexbin.hexbin.prototype.y = function(_) {};
    d3_hexbin.hexbin.prototype.radius = function(_) {};
    d3_hexbin.hexbin.prototype.extent = function(_) {};
