### ISSUE TITLE
Graticule labels?

### ISSUE THREAD

**Issue by collioud** [d3/d3#2259]
Hi,
That would be great to have an option to add labels on map graticules, even if I know this could be (very) tricky for some peculiar geo projections...
Thanks a lot!
Arnaud

**Comment by vigorousnorth** [comment]
I had to do this a few weeks ago. The positioning of the text elements is tricky but here's my stab at it: 

http://bl.ocks.org/vigorousnorth/7e075f3cbd44a0cbb55e

graticule.lines() returns an array of your graticule paths, and each element contains a "coordinates" property that identifies the lat/lng of each line:
https://github.com/mbostock/d3/wiki/Geo-Paths#graticule_lines

You can use these coordinates properties to infer whether each path is a latitude line or a longitude line, find out where it is, and assign its number to a text element or an id property for the path.

**Comment by collioud** [comment]
Nice! Thank you! I will use your code as a basis (I am trying to achieve this with an Aitoff-Hammer projected map).
Have you tried doing the same thing on a map with zooming/panning abilities enabled?

**Comment by collioud** [comment]
Here is an example for my purpose:
http://jsfiddle.net/syf4r6zw/2/

The core of the labeling is in the function labelGraticule(). 
Please note that this example is for an astronomical use (using [Right Ascension, Declination] as coordinates, and an astronomical convention for longitude axis).

**Comment by Fil** [comment]
Seems that the given examples are very fine, and the issue could be closed.
I have updated @vigorousnorth 's exmaple to d3v4 here http://bl.ocks.org/Fil/38f12149738b8767bb10ad1086ce2db0
