### ISSUE TITLE
Too many recursive call to build a quadtree, in d3.geom.js

### ISSUE THREAD

**Issue by orikoon** [d3/d3#238]
Hi, I'm using d3 for visualizing huge-network.

and testing many kinds of huge networks data(10000+ nodes) with force-directed layout.

On the specific network data, I meet the error: "RangeError: Maximum call stack size exceeded" with chrome 12.
I tracked this error and found this is the stack-overflow error(too many recursion with firefox)..
I think that it is caused by a limitation of recursion(http://www.javascriptrules.com/2009/06/30/limitation-on-call-stacks/).

So I fixed the function insertChild(quadtree), on d3.geom.js, to the iterative version.. error is disappeared! (and some speedup?)

Recursive version(BEFORE):

```
function insertChild(n, p, x1, y1, x2, y2) {
// Compute the split point, and the quadrant in which to insert p.
var sx = (x1 + x2) * .5,
    sy = (y1 + y2) * .5,
    right = p.x >= sx,
    bottom = p.y >= sy,
    i = (bottom << 1) + right;

// Recursively insert into the child node.
n.leaf = false;
n = n.nodes[i] || (n.nodes[i] = d3_geom_quadtreeNode());
// Update the bounds as we recurse.
 if (right) x1 = sx; else x2 = sx;
 if (bottom) y1 = sy; else y2 = sy;
 insert(n, p, x1, y1, x2, y2);
}
```

Iterative version(AFTER):

```
function insertChild(n, p, x1, y1, x2, y2) {
var s=new Array();
while(true)
{
    var sx = (x1 + x2) * .5,
        sy = (y1 + y2) * .5,
        right = p.x >= sx,
        bottom = p.y >= sy,
        i = (bottom << 1) + right;

    n.leaf = false;
    n = n.nodes[i] || (n.nodes[i] = d3_geom_quadtreeNode());
    // Update the bounds as we recurse.
    if (right) x1 = sx; else x2 = sx;
    if (bottom) y1 = sy; else y2 = sy;
    if (isNaN(p.x) || isNaN(p.y)) return; // ignore invalid points
    if (n.leaf) {
        var v = n.point;
        if (v) {
            if ((Math.abs(v.x - p.x) + Math.abs(v.y - p.y)) >= .01) {
                n.point=null;
                s.push({arg1:n, arg2:p, arg3:x1, arg4:y1, arg5:x2, arg6:y2});
            }
        }
        else {
                n.point=p;
                if(s.length==0) break;
                else
                { var obj=s.pop(); n=obj.arg1; p=obj.arg2; x1=obj.arg3; y1=obj.arg4; x2=obj.arg5; y2=obj.arg6; }
            }
        }
    }
}
```

**Comment by katiepeters** [comment]
I know this issue is old, but I am also running into a maximum call stack problem. First time using d3.quadtree, so maybe I'm doing something wrong? 

Sample of data: 
[[8, 70], [284, 70], [43, 70.2], [158, 70.2], [61, 70.2], [224, 70.2], [379, 70.2], [75, 70.2], [185, 70.2]]

And there are roughly 300 points that look about the same - x between 1 and 400, y hovering around 70.

```javascript
		let quadtree = d3.geom.quadtree()
			.extent([[-1, -1], [width + 1, height + 1]])
			(data);
```
