### ISSUE TITLE
Zoom events don’t initialize pre-transition zoom state.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#2387]
If you call zoom.event, it sets `element.__chart__` so that a zoom transition starts from the correct view. But this doesn’t happen automatically if a zoom event (or zoomstart / zoomend event) is dispatched. It probably should.

**Comment by apoorvnandan** [comment]
Hi,
I have never solved a bug in an open source project but I have been using D3 in few of my projects and I have also posted one of my visualizations in the Gallery in the Wiki.
I would like to solve this bug.
Can you please guide me? I have forked the repo and installed D3's dependencies. 
Thanks,
Apoorv

**Comment by mbostock** [comment]
Related mbostock/d3#2521.

**Comment by mbostock** [comment]
Related commits 181656196c60462f2242295aaaffa7b99c0b9d96 079db13a7c51597078832099939d478117526a48.

**Comment by mbostock** [comment]
The new d3-zoom handles this cleanly. The zoom state is stored in *element*.\_\_zoom and can be accessed by d3.zoomTransform.
