### ISSUE TITLE
ColorBrewer is not GPLv2 compatible

### ISSUE THREAD

**Issue by DevinCarlson** [d3/d3#2395]
I'd like to include d3 in a Drupal distribution that I'm working on. Since I'm using the Drupal.org packaging system, I cannot include d3 because the Apache 2.0 license used by ColorBrewer is not compatible with GPLv2 (which is what all code on Drupal.org must be licensed as, per the license policy: http://drupal.org/licensing/faq#q4).

All of the other libraries included with d3 are GPLv2 (see the list of compatible licenses: http://drupal.org/node/1475972#whitelist-licenses), except for the CSS and JS file included with ColorBrewer.

I was wondering if it would be possible to replace the ColorBrewer CSS/JS with something else or if I should contact the authors of ColorBrewer to see if they would agree to dual-license it under MIT or another permitted license.

It would be great to be able to use d3 with Drupal, Wordpress, etc!

**Comment by mbostock** [comment]
The [included ColorBrewer CSS & JS](https://github.com/mbostock/d3/tree/master/lib/colorbrewer) are not part of D3; they are included in the git repository merely for convenience. You should be able to remove them from your distribution to remove the license incompatibility. D3 has no dependencies (other than development dependencies for testing).

**Comment by jasondavies** [comment]
Actually, we do include code derived from ColorBrewer in [src/scale/category.js](https://github.com/mbostock/d3/blob/master/src/scale/category.js#L5-8).

**Comment by mbostock** [comment]
Ah, right. You’d need to remove d3.scale.category20c, too.
