### ISSUE TITLE
Transitions stop working if exception thrown in tween

### ISSUE THREAD

**Issue by natevw** [d3/d3#2415]
If a tween throws an exception for whatever reason, transitions stop working until the page is refreshed.

The actual problem [besides the code throwing exceptions, of course…] is ± in the [d3.timer](https://github.com/mbostock/d3/blob/9c3df31216aa28d8252b216b558cbb5907480b5b/src/event/timer.js) implementation, however it appears that the transition code is overriding some of that internal mechanism and may also need handling for this.

(I'm generally loath to add too much coddling against "operator error", apart from throwing informative assertions, but in a case of a global handler like this it seems like something that should be fixed. Otherwise any single buggy/careless "user" of `d3.timer` can break it globally for all the others within the page.)

**Comment by mbostock** [comment]
Superseded by d3/d3-transition#48.

**Comment by mbostock** [comment]
(This was sort-of fixed by d3/d3-timer#4 d3/d3-timer#8, in that timers now have well-defined behavior if an error is thrown. But transitions do not yet have well-defined behavior if an error is thrown.)

**Comment by mbostock** [comment]
Related d3/d3-transition@c066c7c7063fcb5a81cdcbfeab5eb6c1502ebbf7.
