### ISSUE TITLE
Minimal segment size in Chord

### ISSUE THREAD

**Issue by bsideup** [d3/d3#2417]
Hi!

I want to use D3 + Chord to visualize data. But when there are no connections segment is displayed with 0px width (text is broken as well). Is it possible to specify minimal segment width for such case? 

Thanks!

**Comment by jasondavies** [comment]
If I understand correctly, you want to avoid showing nodes that have no connections at all.  I think the best way to do this would be to exclude such nodes from the matrix that you pass to the chord layout.

It is often useful to include zero-connection nodes in the chord layout, and there aren’t any display issues if padding is used to avoid overlapping text labels, so I don’t think the chord layout should be modified to allow a minimum segment size to be specified.

**Comment by bsideup** [comment]
You understand me wrong. I still need to display this nodes.

**Comment by jasondavies** [comment]
Ah, sorry, I understand now.

**Comment by bartiosze** [comment]
Do you guys have any workaround do get those zero-connection nodes displayed? Or any hint on where to go if I'd like to work on it myself?

**Comment by fumoseaffabulazioni** [comment]
Hey there, I have a different problem but probably the solution is the same. I am creating a visualization of a laboratory based on collaborations; it means that I have several people and chords that connect them if they work together. There is a major point: the professor is too much connected, thus my question is: **how it is possible to make segments of the same size?** Doing this, all people of the lab will have the same segment length; collaborations will be pointed out by the density of chords starting from a single segment.

@jasondavies Do you think that using placeholders connections is a solution? I.e. the professor has 10 real connection, the PhD student 1 pointing to the professor and 9 fake connections. This 9 should balance the size of the segment.

@bsideup The other solution is to have a minimal segment size: if you want this parameter to avoid disappearing segments, I could you this to set a high minimal segment size having all segments of the same length.
