### ISSUE TITLE
The brush should support pointer events.

### ISSUE THREAD

**Issue by pgrm** [d3/d3#2446]
Hi, the brush doesn't seem to work with IE 11 using the touchscreen on a windows tablet device. It works fine using the mouse, and when tested in Firefox it works both with the mouse, as wells as the touch screen. We've tested it with the example page: http://bl.ocks.org/mbostock/1667367

Do you have any thoughts on this which might help us? I've seen touch is supported since 2012 (https://github.com/mbostock/d3/pull/511) but probably it never worked with IE, or is this just something which broke in the late past?

In any case, would there be plans to fix this?

Thanks

**Comment by mbostock** [comment]
Related #2403, but that’s just in regards to the drag behavior, not the brush.

**Comment by mbostock** [comment]
Related #1439.
