### ISSUE TITLE
D3 4.0.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#2461]
- [x] release notes, #2841
- [x] major releases of modules, #2849
- [x] reference index, #2865
- [x] [d3-array](https://github.com/d3/d3-array)
- [x] [d3-axis](https://github.com/d3/d3-axis)
- [x] [d3-brush](https://github.com/d3/d3-brush)
- [x] [d3-chord](https://github.com/d3/d3-chord)
- [x] [d3-collection](https://github.com/d3/d3-collection)
- [x] [d3-color](https://github.com/d3/d3-color)
- [x] [d3-dispatch](https://github.com/d3/d3-dispatch)
- [x] [d3-drag](https://github.com/d3/d3-drag)
- [x] [d3-dsv](https://github.com/d3/d3-dsv)
- [x] [d3-ease](https://github.com/d3/d3-ease)
- [x] [d3-force](https://github.com/d3/d3-force)
- [x] [d3-format](https://github.com/d3/d3-format)
- [x] [d3-geo](https://github.com/d3/d3-geo)
- [x] [d3-hierarchy](https://github.com/d3/d3-hierarchy)
- [x] [d3-interpolate](https://github.com/d3/d3-interpolate)
- [x] [d3-path](https://github.com/d3/d3-path)
- [x] [d3-polygon](https://github.com/d3/d3-polygon)
- [x] [d3-quadtree](https://github.com/d3/d3-quadtree)
- [x] [d3-queue](https://github.com/d3/d3-queue)
- [x] [d3-random](https://github.com/d3/d3-random)
- [x] [d3-request](https://github.com/d3/d3-request)
- [x] [d3-scale](https://github.com/d3/d3-scale)
- [x] [d3-selection](https://github.com/d3/d3-selection)
- [x] [d3-shape](https://github.com/d3/d3-shape)
- [x] [d3-time-format](https://github.com/d3/d3-time-format)
- [x] [d3-time](https://github.com/d3/d3-time)
- [x] [d3-timer](https://github.com/d3/d3-timer)
- [x] [d3-transition](https://github.com/d3/d3-transition)
- [x] [d3-voronoi](https://github.com/d3/d3-voronoi)
- [x] [d3-zoom](https://github.com/d3/d3-zoom)

**Comment by colinmegill** [comment]
+1 for making the modules as agnostic as possible about SVG / Canvas etc. If the DOM model in general is an implementation detail, the potential scope of the library increases, especially for server side rendering. Easy to imagine using d3.layout.tree() with: https://github.com/Automattic/node-canvas this way. Or with react-native on iOS, as d3.layout.tree() just returns x y pairs and diagonals.

**Comment by colinmegill** [comment]
Just checked the google results for `d3 canvas server` and the first three are unanswered SO posts.

**Comment by mbostock** [comment]
> as agnostic as possible about SVG / Canvas

Yep. Obviously the retained-mode aspects of D3, notably d3-selection and d3-transition, will always require a DOM-like scenegraph. (I say DOM-like because it doesn’t strictly require the DOM: [OMG Particles II](http://bl.ocks.org/mbostock/9539958) selects a simple object to store transition state, and [DOM-to-Canvas](http://bl.ocks.org/mbostock/1276463) uses custom DOM elements to render to Canvas.) But many other aspects of D3 don’t care about the visual representation, including layouts.

I have a more ambitious plan to develop D3’s geometry pipeline that could allow things like d3.svg.line and d3.svg.area to work with either Canvas or SVG. The geometry pipeline is what currently allows d3.geo to output to either SVG or Canvas, as shown in the [World Tour](http://bl.ocks.org/mbostock/4183330).

This effort may or may not intersect with [Path2D](https://developer.mozilla.org/en-US/docs/Web/API/Path2D), which will hopefully become more widely supported in the future. If it does, it becomes trivial to take D3’s [SVG shapes](https://github.com/mbostock/d3/wiki/SVG-Shapes) and use their generated path data with Canvas. But, there are still some nice things about having a generic, composable geometry pipeline. See [Pencil Sketch](http://bl.ocks.org/mbostock/e2a20d86124693ef0f93) for another example.

**Comment by colinmegill** [comment]
> Including layouts

Absolutely... have taken advantage of that with React... see:

* Tree: http://jsbin.com/yiweti/18/edit?html,js,output
* Force: http://jsbin.com/fanofa/14/edit?html,js,output
* Treemap: http://jsbin.com/qoyevo/9/edit?html,js,output

I'm generally excited about this methodology because the SVG is more declarative, and the loops are more explicit. 

It will have to handle transitions differently, which is what I'm working on now:

[gist](https://gist.github.com/colinmegill/a3733a4369dd172dd800) [gif](www.gfycat.com/CandidBlushingCuckoo)

I'm excited about this for a whole bunch of reasons, and modular D3 helps this a bunch.

**Comment by colinmegill** [comment]
`<circle r={this.props.hasChildren ? 3 : 1} />` gives me a lot of joy :)

**Comment by mbostock** [comment]
Ol notes:

* The current d3.locale API might make it awkward to have d3-number-format and d3-time-format in separate modules. Maybe that API should be broken up so that d3.formatNumber is localizable and d3.formatTime is localizable without depending on a shared d3.locale object.

* The names d3.format and d3.time.format aren’t great. Maybe d3.formatNumber and d3.formatDate? More generally, should “time” be renamed “date”?

* The d3-svg module should probably be broken up into separate modules? Also, should it be SVG-specific? Probably we can make it work with Canvas, too. Maybe d3-shapes is a better name? Though note that things like d3.svg.axis will likely remain SVG-specific. And making too many name changes will make migration difficult, so we’ll probably want aliases for anything we rename, anyway.

* The d3.transform class will be removed, though d3.interpolateTransform will still be supported.

**Comment by chrisvfritz** [comment]
Really looking forward to this! In my visualization projects, D3 is increasingly being used as a layout engine, with everything else handled by React. I know v4 is still a ways out, but __is there a timeline for when an alpha version might be available?__

**Comment by mbostock** [comment]
Many of the modules are already available for use: see <https://github.com/d3>. There’s no explicit timeline for the first “complete” default build of D3 4.0, but my goal is early next year. I expect that the remaining layouts (d3-hierarchy, d3-chord, and the stack layout for d3-shape) will be done this month. I’ll probably tackle d3-force after that.

**Comment by chrisvfritz** [comment]
Wonderful to hear! I really appreciate your work. I'll start trying out some of the available modules in new projects. Are they at a point where it's useful to open issues or submit PRs if something isn't working quite right?

**Comment by imanhodjaev** [comment]
Hi @mbostock when do you plan to rollout `d3-brush` as a separate module?

Thank you.

**Comment by mbostock** [comment]
@imanhodjaev It’s probably next after I finish [d3-zoom](https://github.com/d3/d3-zoom), so it should be in the next two weeks. After that, d3-geo and d3-geo-projection.

**Comment by mbostock** [comment]
Current status:

![image](https://cloud.githubusercontent.com/assets/230541/16353007/a32cecee-3a28-11e6-9b53-fce8096e9417.png)

**Comment by colinmegill** [comment]
Woohoo!

**Comment by mbostock** [comment]
(Probably won’t blast off until next week. But we are close!)

**Comment by tianxuzhang** [comment]
awasome!
