### ISSUE TITLE
z-index or "bring-to-top" on svg: elements

### ISSUE THREAD

**Issue by gryzzly** [d3/d3#252]
Hi!

I am sorry I am asking this here, I didn't find any other channel for help on d3. First of all, great thanks for this library, it's super cool.

My question is this:
let's say, I have an svg canvas:

```
var canvas = d3.select('.canvas').append('svg:svg').attr('width', width).attr('height', height);
```

I then create a collection of circles, symbolizing the amount of developers who completed certain survey, and place them randomally over the canvas, with something like this ( I have 29 circles | devs ) :

```
return d3.scale.linear().domain([ 0, 29 ]).rangeRound([ 22, width - 22 ])( ~~( Math.random() * 29 ) )  + 'px';
```

Then, I create a collection of rectangles, that symbolize options for the first question, with a simple transition from `style('opaticy', 0.001)` to `style('opacity', 0.8)`. 

Now, I want to animate the circles' coordinates so that depending on the amount of the devs selecting certain option, each option would have the proper amount of circles over it. 

But, since I've drawn the circles first, before the rectangles, they are "below" the rectangles. And I want my circles to preserve through all the "frames / questions", because I want them to "move around", not to be drawn from scratch all the time. I've tried to google "z-index" for svg, but I didn't find much. I've found out that order of elements has certain impact, so I thought maybe there is an API to "bring to top" a collection? 

Thanks!

**Comment by hijiangtao** [comment]
Hi, dear mbstock. Thanks for your great work in D3.
I face the same problem in changing the place order of <rect> elements in a visualization chart. I am trying to use the last method you mentioned above 'Use D3's sort operator to reorder the elements.', but the reality is that the chart exists too many rect elements, i wonder if the sort method is the best solution to solve my problem? Thanks.

**Comment by hijiangtao** [comment]
Hi, dear mbstock. Thanks for your great work in D3.
I face the same problem in changing the place order of elements in a visualization chart. I am trying to use the last method you mentioned above 'Use D3's sort operator to reorder the elements.', but the reality is that the chart exists too many rect elements, i wonder if the sort method is the best solution to solve my problem? Thanks.

**Comment by brutalcrozt** [comment]
Hi i am new comer, but is this [spec](https://dev.w3.org/SVG/modules/renderorder/SVGRenderOrder.html) can be implement?

**Comment by mbostock** [comment]
@brutalcrozt That is dependent on your browser, not D3, which just manipulates the DOM. Also the latest spec is [SVG 2’s z-index property](https://www.w3.org/TR/SVG2/render.html#ZIndexProperty).
