### ISSUE TITLE
Zoom behavior should not block window scrolling when zoom is within scaleExtent

### ISSUE THREAD

**Issue by jakerichan** [d3/d3#2549]
When using zoom and the cursor is over a d3 chart, a user is unable to scroll the window.  After hitting a scaleExtent min or max, scroll-ability should be returned to the window.

**Comment by mbostock** [comment]
Covered by #2550.

**Comment by mbostock** [comment]
Reopening to track since previous PR was closed.

**Comment by mbostock** [comment]
This has been implemented in [d3-zoom](https://github.com/d3/d3-zoom) for D3 4.0.
