### ISSUE TITLE
Add ability to name parameters in the zip function

### ISSUE THREAD

**Issue by bjedrzejewski** [d3/d3#2582]
Zip function currently creates an array from multiple arrays. It would be very useful if it could also take property names as arguments and return array of objects.

**Comment by mbostock** [comment]
Could you provide a code snippet of how that would work? Based on your description, I am imagining something like:

```js
var data = [
  {yield: 27, variety: "Manchuria", year: 1931, site: "University Farm"},
  {yield: 48.87, variety: "Manchuria", year: 1931, site: "Waseca"},
  {yield: 27.43, variety: "Manchuria", year: 1931, site: "Morris"},
  …
];

var zipped = zip(data, ["yield", "year"]); // [[27, 1931], [48.87, 1931], …]
```

Which makes it sound more like array.map and [permute](https://github.com/d3/d3-arrays#permute):

```js
var permuted = data.map(function(d) { return permute(d, ["yield", "year"]); });
```
