### ISSUE TITLE
Enable d3 selections to iterate ES6 Maps and Sets?

### ISSUE THREAD

**Issue by ericsoco** [d3/d3#2584]
I went all-in on ES6 in a new project and structured my data layer with ES6 [Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Sets](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set). Then, I started trying to plug my data into d3, specifically into `.data()` calls, and found myself having to do a lot of:

```
.data((d) => Array.from(myMap.values()))
// and
.data((d) => Array.from(mySet))
```

I'm not very familiar with d3's internals, so not sure how much of a restructuring this would require, but if selections could use [ES6 for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loops, that would probably go a long way to solving this one.

There will still be vagaries though, e.g.: would selections iterate Map.values() by default? What if a developer needs to iterate keys/entries?

**Comment by mbostock** [comment]
We’ll definitely want to use for…of loops when we can depend on ES6 support. I think it’s too soon to require that for 4.0, but eventually, sure. :)

**Comment by mbostock** [comment]
Related https://github.com/leebyron/iterall
