### ISSUE TITLE
Mouse wheel implementation broken on Windows

### ISSUE THREAD

**Issue by blaise-io** [d3/d3#2589]
In Chrome 46 / Windows 7, `d3.event.deltaY` always returns `-0`, so mousewheel does not do anything. I can fix it by replacing:

```
    if (!d3_behavior_zoomWheel) {
      d3_behavior_zoomWheel = "onwheel" in d3_document ? (d3_behavior_zoomDelta = function() {
        return -d3.event.deltaY * (d3.event.deltaMode ? 120 : 1);
      }, "wheel") : ...
```

with:

```
    if (!d3_behavior_zoomWheel) {
      d3_behavior_zoomWheel = "onwheel" in d3_document && !(/win/i).test(navigator.platform) ? (d3_behavior_zoomDelta = function() {
        return -d3.event.deltaY * (d3.event.deltaMode ? 120 : 1);
      }, "wheel") : ...
```

See: https://github.com/layar/d3/commit/49077acd0c847f9dc9811efb96d963e323d32a54, tested in latest Chrome, IE, Firefox on Windows and Mac OS X.

This works, but it would be better to use a proven mouse wheel library to handle mouse wheel events, or draw inspiration from https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Listening_to_this_event_across_browser

**Comment by langdonx** [comment]
FWIW, on two separate machines Chrome 46+Windows 7, deltaY is either -100 or +100 and zoom still works fine.

**Comment by kfei** [comment]
Possibly related to Chrome's breaking changes: https://codereview.chromium.org/1285133008/
