### ISSUE TITLE
Add a d3 geo contains(ppint,  feature) 

### ISSUE THREAD

**Issue by pwiecz** [d3/d3#2662]
This is a feature request. 
d3 can compute a centroid or area of a feature,  but there is no function to check if a point lie within a given feature. 
Such a function working correctly for all features (across 180th meridian, containing pole etc.) would be immensly helpful to me. 
Probably it can be implemented relatively easily using the same logic that's used for clipping. 
If so at least some pointers how to implement this would be very helpful. 
Thank you.

**Comment by mbostock** [comment]
There is a [d3_geo_pointInPolygon](https://github.com/mbostock/d3/blob/master/src/geo/point-in-polygon.js) function, but it’s currently private. It’s used for clipping.

**Comment by pwiecz** [comment]
Thanks, it's working great for me.

**Comment by Fil** [comment]
It is now (d3v4) here https://github.com/d3/d3-geo/blob/master/src/polygonContains.js

Can we expose it?

**Comment by mbostock** [comment]
If you exposed it as d3.geoContains(*feature*, *point*) and made sure it supported all GeoJSON feature types (requiring an exact match for point and line features, and generalizing it to support multipolygons), then yes.
