### ISSUE TITLE
Issue in inverting conic projections when parallels are negative

### ISSUE THREAD

**Issue by mijamo** [d3/d3#2707]
Hi,

At first I though I was doing something wrong so I submitted a question on SO, but after more investigation it really looks like a bug.

When you set a projection with negative parallels ( example : -20 and -50), the invert function does not work as expected : 

    var p = d3.geo.conicEqualArea().parallels([-35,-50])
    
    p.invert([480,250])
    // Result : Array [ -268.7327478371507, -0 ], whereas expected value would be [0,0]
    
    p([-268.7327478371507,-0])
    // Result : Array [715.2876827794818, 388.95968864688876], so projection and invert are not coherent

After checking d3's code, I found a quick and dirty fix in the invert functions, ex hereafter with conicEqualArea :

    forward.invert = function(x, y) {
        var ρ0_y = ρ0 - y;
        var hack = ρ0_y > 0 ? 1 : -1;
        return [
          Math.atan2(x, Math.abs(ρ0_y)) / n * hack,
          d3_asin((C - (x * x + ρ0_y * ρ0_y) * n * n) / (2 * n))
        ];
      };

This way the invert function works as expected. This problem is that Math.atan2( ±0, +0 ) ==>  ±0 so the invert works as expected in the north lattitudes, but Math.atan2( ±0, -0 ) ==>  ±PI, so in this case it breaks everything.

I have not submitted a pull request yet as I am not really sure this is a real fix and will not bring many more issues.

**Comment by mbostock** [comment]
I haven’t verified your fix, but it sounds entirely plausible.
