### ISSUE TITLE
Easier way to draw a circular segment in d3?

### ISSUE THREAD

**Issue by hanfeisun** [d3/d3#2739]
I found d3 has `d3.svg.arc` for convenient drawing of an arc. 

However, there seems no way to draw a [circular segment ⌓](https://www.wikiwand.com/en/Circular_segment) easily. 

The possible parameters for drawing circular segment are `radius` (r) and `height` (h).

Will it be possible for this shape to be added to d3 in the future?

**Comment by mbostock** [comment]
No immediate plans to do this, but it would go into [d3-shape](https://github.com/d3/d3-shape) or a new [D3 plugin](https://bost.ocks.org/mike/d3-plugin/) if it were to be added.

Also see my [Circular Segment](http://bl.ocks.org/mbostock/3422480) example, which uses clipping. But I think it’d be pretty straightforward to change it to use SVG’s elliptical arc commands.

**Comment by chandramouli-sastry** [comment]
Hey!  I wrote a plugin which could help you: https://github.com/chandramouli-sastry/d3-csegment. I'm quite new to open source and I'm working on creating a pull request. Please let me know what you think about this.
