### ISSUE TITLE
cleaner wiki sidebar

### ISSUE THREAD

**Issue by pokeball99** [d3/d3#2740]
we should format the wiki sidebar for user friendliness, https://github.com/bibanon/bibanon/wiki is a good example. such as putting the translations in its own sections and such

**Comment by mikroware** [comment]
I added a sidebar to the d3 wiki (like [bibanon/bibanon/wiki](/bibanon/bibanon/wiki)). It contains all useful pages which I could find on the wiki.

**Comment by pokeball99** [comment]
@mikroware haha, looks awesome man, thanks, don't know if this considered "done" since more *could* be done with it
