### ISSUE TITLE
Tag npm packages with e.g. `d3-modularized`

### ISSUE THREAD

**Issue by ericsoco** [d3/d3#2827]
It's easy to find all the lodash modules because they're tagged with the keyword [`lodash-modularized`](https://www.npmjs.com/browse/keyword/lodash-modularized). Would be great to have the same thing for the new d3 npm modules.

**Comment by mbostock** [comment]
Okay, done. They’ll start appearing under [d3-module](https://www.npmjs.com/browse/keyword/d3-module) on subsequent releases (which will be soon).
