### ISSUE TITLE
Can't find the source

### ISSUE THREAD

**Issue by johnbendi** [d3/d3#2833]
I can't find the sources for the d3 project in the repo and no clear instruction is given on how to get it.

**Comment by mbostock** [comment]
The source is broken up into many repositories; see <https://github.com/d3>. Clicking on any of the sections in the [API Reference](https://github.com/d3/d3/blob/master/README.md#api-reference) will take you to the corresponding repository where you can view the source, such as [d3-array](https://github.com/d3/d3-array).
