### ISSUE TITLE
d3.csv.parse does not work

### ISSUE THREAD

**Issue by AppleXiao1995** [d3/d3#2836]
I can't use d3.csv.parse in the latest released version of d3. in which it says "d3.csv.parse is not a function".
```html
<!DOCTYPE html>
<meta charset="utf-8">
<head>
</head>

<body>
<script src="https://d3js.org/d3.v4.0.0-alpha.44.min.js"></script>
<script>
var flare = 'id,\na,\nb,\n';
var data = d3.csv.parse(flare);
console.log(data);
</script>


```
Can it be solved? Thanks!

**Comment by mbostock** [comment]
Some of the API methods have been renamed (and changed) in the D3 4.0 API as compared to D3 3.x. See the [documentation for d3-dsv](https://github.com/d3/d3#delimiter-separated-values-d3-dsv) and [d3.csvParse](https://github.com/d3/d3-dsv#csvParse).
