### ISSUE TITLE
How to interrupt an axis transition

### ISSUE THREAD

**Issue by jnm2** [d3/d3#2838]
I have a constantly scrolling axis that uses axis transitions to move and to achieve fade in and fade out.

When the window is resized, the graph gets wider. I need to change the range of the X axis. The problem is that when I update the range, the range change also gets animated along with the scroll. This is undesirable- I want the resize to be instantaneous, to interrupt the scrolling transition, reposition all the ticks instantaneously, and continue scrolling it as it was before after the range is updated.

`xAxisElement.interrupt()` doesn't have an effect. I tried `xAxisElement.transition().axisElement.delay(1).axis(xAxis).transition(duration).axis(futureXAxis)` to first reset the axis to the new width, then continue scrolling as normal. The first transition gets skipped. With `delay(10)` sometimes the first transition runs, sometimes it doesn't. 10 ms is also too long- I really want to update the width immediately.

I found a workaround, which is to destroy and recreate the X axis every time the graph is resized. It would be nice to have a less nuclear option for performance and persistence.

**Comment by mbostock** [comment]
When you create an axis transition, you’re creating multiple independent, synchronized transitions on the descendants of the axis element (the tick lines, the tick labels, the domain path, *etc.*). So the reason that *selection*.interrupt on the axis G element has no visible effect is that, despite cancelling the transition the G element, it does not cancel the transitions on the descendant elements—and these are the ones you see moving.

If you want to interrupt the axis transition, you need to interrupt it on the descendants of the G element instead. If `g` is a selection of your axis element:

```js
g.selectAll("*").interrupt();
```

**Comment by jnm2** [comment]
`g.selectAll("*").interrupt()` works for the oldest tick but none of the rest. I assume they aren't being selected? I'll try to figure out why.

**Comment by jnm2** [comment]
Wow, talk about user error. Thank you. Seems like I could've figured this out.

However, it isn't as symmetrical with `axisEl.transition()`. Maybe you would consider special-casing `axisEl.interrupt()` the same way `.transition()` is special-cased?
