### ISSUE TITLE
The nest.rollup() function between v3 and v4.

### ISSUE THREAD

**Issue by cv711** [d3/d3#2839]
Hi!

In v3 this snippet:
```javascript
var points = [
      {date: '2016-05-01', value: 10},
      {date: '2016-05-01', value: 20},
      {date: '2016-06-02', value: 15},
      {date: '2016-05-05', value: 5}
    ];

var dataByDate = d3.nest()
    .key(d => d.date)
    .rollup(d => d3.sum(d, g => g.value))
    .map(points);

console.log(dataByDate);
```

gives back a JSON Object:
```Object {2016-05-01: 30, 2016-06-02: 15, 2016-05-05: 5}```

whereas in v4 the same code returns an instance of a d3.Map if I'm not mistaken:
```D {$2016-05-01: 30, $2016-06-02: 15, $2016-05-05: 5}```

Is there some other way to get a JSON Object back in the new API or is this going away?

Thanks,
Chris

**Comment by mbostock** [comment]
Yes. Use [*nest*.object](https://github.com/d3/d3-collection#nest_object) instead of [*nest*.map](https://github.com/d3/d3-collection#nest_map).

```js
var dataByDate = d3.nest()
    .key(d => d.date)
    .rollup(d => d3.sum(d, g => g.value))
    .object(points);
```
