### ISSUE TITLE
D3 4.0 Release Notes

### ISSUE THREAD

**Issue by mbostock** [d3/d3#2841]
https://github.com/d3/d3/blob/master/CHANGES.md

- [x] [d3-array](https://github.com/d3/d3-array)
- [x] [d3-axis](https://github.com/d3/d3-axis)
- [x] [d3-brush](https://github.com/d3/d3-brush)
- [x] [d3-chord](https://github.com/d3/d3-chord)
- [x] [d3-collection](https://github.com/d3/d3-collection)
- [x] [d3-color](https://github.com/d3/d3-color)
- [x] [d3-dispatch](https://github.com/d3/d3-dispatch)
- [x] [d3-drag](https://github.com/d3/d3-drag)
- [x] [d3-dsv](https://github.com/d3/d3-dsv)
- [x] [d3-ease](https://github.com/d3/d3-ease)
- [x] [d3-force](https://github.com/d3/d3-force)
- [x] [d3-format](https://github.com/d3/d3-format)
- [x] [d3-geo](https://github.com/d3/d3-geo)
- [x] [d3-hierarchy](https://github.com/d3/d3-hierarchy)
- [x] [d3-interpolate](https://github.com/d3/d3-interpolate)
- [x] [d3-path](https://github.com/d3/d3-path)
- [x] [d3-polygon](https://github.com/d3/d3-polygon)
- [x] [d3-quadtree](https://github.com/d3/d3-quadtree)
- [x] [d3-queue](https://github.com/d3/d3-queue)
- [x] [d3-random](https://github.com/d3/d3-random)
- [x] [d3-request](https://github.com/d3/d3-request)
- [x] [d3-scale](https://github.com/d3/d3-scale)
- [x] [d3-selection](https://github.com/d3/d3-selection)
- [x] [d3-shape](https://github.com/d3/d3-shape)
- [x] [d3-time-format](https://github.com/d3/d3-time-format)
- [x] [d3-time](https://github.com/d3/d3-time)
- [x] [d3-timer](https://github.com/d3/d3-timer)
- [x] [d3-transition](https://github.com/d3/d3-transition)
- [x] [d3-voronoi](https://github.com/d3/d3-voronoi)
- [x] [d3-zoom](https://github.com/d3/d3-zoom)

**Comment by mbostock** [comment]
Basic outline:

- [x] [d3-array](https://github.com/d3/d3-array)
- [x] [d3-axis](https://github.com/d3/d3-axis)
- [x] [d3-brush](https://github.com/d3/d3-brush)
- [ ] [d3-chord](https://github.com/d3/d3-chord)
- [x] [d3-collection](https://github.com/d3/d3-collection)
- [x] [d3-color](https://github.com/d3/d3-color)
- [x] [d3-dispatch](https://github.com/d3/d3-dispatch)
- [x] [d3-drag](https://github.com/d3/d3-drag)
- [x] [d3-dsv](https://github.com/d3/d3-dsv)
- [x] [d3-ease](https://github.com/d3/d3-ease)
- [x] [d3-force](https://github.com/d3/d3-force)
- [x] [d3-format](https://github.com/d3/d3-format)
- [ ] [d3-geo-projection](https://github.com/d3/d3-geo-projection)
- [ ] [d3-geo](https://github.com/d3/d3-geo)
- [x] [d3-hierarchy](https://github.com/d3/d3-hierarchy)
- [x] [d3-interpolate](https://github.com/d3/d3-interpolate)
- [x] [d3-path](https://github.com/d3/d3-path)
- [x] [d3-polygon](https://github.com/d3/d3-polygon)
- [x] [d3-quadtree](https://github.com/d3/d3-quadtree)
- [ ] [d3-queue](https://github.com/d3/d3-queue)
- [x] [d3-random](https://github.com/d3/d3-random)
- [x] [d3-request](https://github.com/d3/d3-request)
- [ ] [d3-scale](https://github.com/d3/d3-scale)
- [x] [d3-selection](https://github.com/d3/d3-selection)
- [ ] [d3-shape](https://github.com/d3/d3-shape)
- [ ] [d3-time-format](https://github.com/d3/d3-time-format)
- [ ] [d3-time](https://github.com/d3/d3-time)
- [x] [d3-timer](https://github.com/d3/d3-timer)
- [ ] [d3-transition](https://github.com/d3/d3-transition)
- [ ] [d3-voronoi](https://github.com/d3/d3-voronoi)
- [ ] [d3-zoom](https://github.com/d3/d3-zoom)

**Comment by mbostock** [comment]
I’m planning on releasing 4.0 at the end of this month, so there’s not much that will change between now and release. Many of the modules (see #2849) have already had major releases (1.0 or higher), and so there won’t be any backwards-compatible changes in those released modules between now and 4.0. The primary remaining development effort is limited to [d3-geo](https://github.com/d3/d3-geo) and [d3-chord](https://github.com/d3/d3-chord), which have not yet been fully implemented.

**Comment by syntagmatic** [comment]
@courtagenjim If it's critical to develop from a stable API in the short term, sticking with version 3 is a good choice. Then if you want to upgrade to v4 at an appropriate time to get new features after the API is complete and has stabilized, you can do it on your own schedule. This reference should be useful when you make the switch:

https://github.com/d3/d3/blob/master/CHANGES.md

**Comment by courtagenjim** [comment]
AWESOME answers: on the 4.0 release timeframe, and on the feature completeness. Also appreciate the rapid response to my query. Kudos!

**Comment by mbostock** [comment]
🎉
