### ISSUE TITLE
Feature request for axis.copy()

### ISSUE THREAD

**Issue by jnm2** [d3/d3#2842]
When animating from one axis to another, it's nice to be able to clone the current axis and modify the scale in the same way that `scale.copy()` is nice.

If you think it would be a good addition, I'm willing to PR.

**Comment by mbostock** [comment]
Can you link me an example? I’m not grokking the use case. The common case of animated axis transitions is when the scale domain changes, so that doesn’t require *axis*.copy. I’m not sure when you’d need to retain references to multiple axes.

**Comment by jnm2** [comment]
Not in a public repo, but here's the relevant bit:

```TypeScript
const now = Date.now();

xScale.domain([now - duration, now]);
lineScrollContainer.interrupt().transition();
lineScrollContainer.attr('transform', `translate(${xScale(new Date(now - duration))})`);
lineScrollContainer.transition()
    .duration(tickUpdateInterval)
    .ease('linear')
    .attr('transform', `translate(${xScale(new Date(now - duration - tickUpdateInterval))})`);

xAxisEl.selectAll('*').interrupt();
xAxisEl.call(xAxis); // xAxis was previously set up with .scale(xScale)
xAxisEl
    .transition()
    .duration(tickUpdateInterval)
    .ease('linear')
    .call(xAxis.copy().scale(xScale.copy().domain([now - duration + tickUpdateInterval, now + tickUpdateInterval])));
```

I'm interrupting every time, setting the current scale, and then setting the future scale, rather than just animating from wherever it happens to be at the moment to the new scale. The reason is that there are times where realtime data is being added or the window is resized where I can't just wait for transition end.

**Comment by jnm2** [comment]
Also, this solves https://github.com/d3/d3/issues/885#issuecomment-210901596 for me.

**Comment by mbostock** [comment]
Hmm. That seems like the sort of use case where you should be using d3.timer and continuously updating the axis via *selection*.call, rather than using a transition with linear easing.

**Comment by jnm2** [comment]
Perhaps. How does that compare performance-wise? Also, will that do the fades on the axis ticks like transitions do?
