### ISSUE TITLE
Feature Request: Add callif() method

### ISSUE THREAD

**Issue by mike-ward** [d3/d3#2863]
I find it easier to chain conditional branches to my call chains by adding the following to d3

```
d3.selection.prototype.callif = function(condition) {
    if (condition) d3.selection.prototype.call.apply(this, Array.prototype.slice.call(arguments, 1));
    return this;
};
```

**Comment by mbostock** [comment]
A reasonable idea, but not one I plan on implementing in the short term. It might be a good fit in d3-jetpack or a similar D3 “extended” API utility module.
