### ISSUE TITLE
Add .tension parameter to d3.svg.line().interpolate("step")

### ISSUE THREAD

**Issue by lgrkvst** [d3/d3#2864]
This is an enhancement request.

Complementing `interpolate("step")` with `.tension(radius)` would provide an efficient way to control corner rounding:

![rounded corner](http://i.stack.imgur.com/cWsxU.png)

`radius` would be an path-wide absolut value as I imagine a frequent use-case would include a constant rounding factor on every corner of the path.

**Comment by mbostock** [comment]
Do you mind re-filing this over in https://github.com/d3/d3-shape?

**Comment by mbostock** [comment]
Okay, I’ll do it. Moved to d3/d3-shape#74.
