### ISSUE TITLE
D3 4.0 + bower

### ISSUE THREAD

**Issue by jgalb** [d3/d3#2874]
I noticed the post-publish script is missing bower generation, is this intentional?

**Comment by mbostock** [comment]
My mistake; I forgot to add it back now that we’re out of alpha. I will push 4.0 to Bower soon. It lives here: https://github.com/mbostock-bower/d3-bower

**Comment by mbostock** [comment]
Fixed the postpublish script and also pushed v4.0.0 to d3-bower.

**Comment by jgalb** [comment]
Thanks again Mike.
