### ISSUE TITLE
Undocumented change in 4.0: append element with class name

### ISSUE THREAD

**Issue by ocombe** [d3/d3#2877]
Hello,

while porting my code from v3 to v4, nothing was working without error until I found out that you cannot set the class name in the append/insert function anymore.

Example:
v3:
```ts
this.xAxisElement = this.axesArea.append('g.axis.x')
    .attrs({
        transform: `translate(${0}, ${this.internalHeight})`
    })
    .call(this.xAxis);
```

v4:
```ts
this.xAxisElement = this.axesArea.append('g')
    .attrs({
        'class': "axis x",
        transform: `translate(${0}, ${this.internalHeight})`
    })
    .call(this.xAxis);
```

And this fails totally silently, which is not good !

**Comment by mbostock** [comment]
This is documented in the release notes, but I will check and try to make
it more explicit.

The multi-value map methods have been removed from the default bundle. If
you want them, you can use the d3-selection-multi module.

https://github.com/d3/d3-selection-multi

As for calling selection.append with shorthand syntax for setting classes
on the created elements: that has never been supported in D3, so you must
be using a convenience module such as d3-jetpack. I am not the maintainer
of that module, so I am not sure whether it is compatible with 4.0 or
whether it needs an update. There’s a chance it still works but it could
probably also use an update (at least to adopt the new module pattern).

**Comment by ocombe** [comment]
Ahah my bad sorry, I used to have d3-jetpack for so long that I didn't even know that this wasn't some part of D3, and I removed jetpack when I updated to v4.0 ! (Man, I miss the `.translate` method so much!!)

Thanks then !

As for the multi value map, I'm aware of that, no worries !
