### ISSUE TITLE
partitions in V4?

### ISSUE THREAD

**Issue by albell** [d3/d3#2880]
I'd like to port some existing code from v3 to v4, and hitting a bump. Layouts seem to be gone completely. Is the plan to release these in the future as modules? Is there a timeline for that? (I want to use layout.partition.) I am itching to start using V4 on a current project because of the new Cubehelix space (_awesome_, BTW).

Thanks in advance for any help.

**Comment by mbostock** [comment]
Start here: https://github.com/d3/d3/blob/master/CHANGES.md#hierarchies-d3-hierarchy

**Comment by albell** [comment]
Thanks. Got it.
