### ISSUE TITLE
Full version of D3 v4 does not include selection.attrs

### ISSUE THREAD

**Issue by dengeist** [d3/d3#2890]
From the d3-selection-multi library page:

> You can also load directly from d3js.org, either as a standalone library or as part of D3 4.0.

Yet when I load only the core D3 library and attempt `selection.attrs(obj)`, the console reports that `selection.attrs` is not a function. After importing the standalone library, however, it works just fine. Am I misunderstanding the copy on the selection-multi page or is this a bug in core D3?

**Comment by mbostock** [comment]
That text is copy-pasted from the other D3 modules and is wrong. The
d3-selection-multi plugin is not included in the default bundle. I will fix
the text.

**Comment by dengeist** [comment]
Thanks for the clarification! I found the notes about how d3 was made modular shortly after raising this issue, of course. Haha.
