### ISSUE TITLE
V4 migration guidelines

### ISSUE THREAD

**Issue by ramtob** [d3/d3#2893]
Hello,
I notice that v4 is a major overhaul, and is not backward-compatible (to put it mildly :). Can you offer some guidelines to make a migration from v3 to v4 as quick and painless as possible?
TIA

**Comment by curran** [comment]
Is there something not covered in the release notes at https://github.com/d3/d3/blob/master/CHANGES.md that you would like to see?

**Comment by ramtob** [comment]
Well, anything that could make the transition from v3 quicker and easier, beyond going over line by line and changing the code. For example, I understand that all the d3 class names have changed. It could be nice to have a shim module, such that the v3 class names will continue to work after the transition to v4.

**Comment by mbostock** [comment]
Please use the release notes (and the summary of the release notes) to learn what has changed:

https://github.com/d3/d3/releases/v4.0.0
https://github.com/d3/d3/blob/master/CHANGES.md

Sorry, but I have no plans on writing an explicit migration guide or providing a compatibility shim; of course anyone else is welcome to do so. I know the change list is long, but in many cases the changes are easy to apply. It may be less onerous than you think.
