### ISSUE TITLE
Include d3-selection-multi

### ISSUE THREAD

**Issue by nielsheeren** [d3/d3#2894]
Please include the **d3-selection-multi** library because it's missing this functionality in v4.

**Comment by mbostock** [comment]
The exclusion is intentional. You must load d3-selection-multi separately if you want to use it. For details see https://github.com/d3/d3-selection-multi

**Comment by nielsheeren** [comment]
Thanks for the reply.  I love the library and v4 but I hope the next major release will be more backwards compatible.
