### ISSUE TITLE
d3.xml not working with v4.x

### ISSUE THREAD

**Issue by iyogeshjoshi** [d3/d3#2896]
So I was trying to import a SVG file using `d3.xml` method which was working properly in __v3.5.17__ but after upgrading it to __v4.x__ I'm unable to import SVG file, also it ain't throwing any error or anything I'm getting `undefined` in both error and data in _callback_.

I'm using it with _electron_. To make sure I tried opening the file with same path using __fs__ module and it was working properly. I think there is some issue with v4 `d3.xml`.

**Comment by curran** [comment]
For what it's worth, here's where `d3.xml` is documented - https://github.com/d3/d3-request/blob/master/README.md#xml

There is a note there that states

> XML parsing relies on [*xhr*.responseXML](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseXML) which is not supported by [node-XMLHttpRequest](https://github.com/driverdan/node-XMLHttpRequest/issues/8) as of version 1.8; thus, this method is supported in browsers but not in Node.

Is your Electron code that uses `d3.xml` running in Node or Chromium?

**Comment by mbostock** [comment]
Are you trying to pass a mime-type as the optional second argument to d3.xml? This is no longer supported. (I overlooked this in the release notes, but I have since added it.) For example, the following code no longer works because the second argument (the mime type) is inadvertently treated as data to be sent with the GET request, and the third argument (the callback) is ignored:

```js
d3.xml("rect01.svg", "image/svg+xml", function(error, xml) {
  if (error) throw error;
  document.body.appendChild(xml.documentElement);
});
```

I’ve just fixed d3/d3-request#12 so that this throws an error ("invalid callback: image/svg+xml") making the error more clear.

You either need to use the default mime type of application/xml, as here:

```js
d3.xml("file.svg", function(error, xml) {
  if (error) throw error;
  …
});
```

Or you need to use *request*.mimeType to specify the MIME type by chaining:

```js
d3.xml("file.svg").mimeType("image/svg+xml").get(function(error, xml) {
  if (error) throw error;
  …
});
```

I’ve updated the [External SVG example](http://bl.ocks.org/mbostock/1014829) to demonstrate correct usage in D3 4.x.

If that’s not it, and there’s a separate issue specific to Electron, I’m afraid I’m not going to be much help as I don’t use Electron. If you can do some further debugging I can revisit this issue.

**Comment by iyogeshjoshi** [comment]
@curran I'm serving the file in electron's browser window, and I suppose it's __V8 Engine__ and __Chromium__ only not _Node_, Also I'm not Specifying any mime type anywhere just like @mbostock said I'm doing it the same way
```js
d3.xml("file.svg", function(error, xml) {
  if (error) throw error;
  …
});
```
Though image path and everything seems correct still neither I'm getting error or any response data both of them are coming `undefined` :confused:

**Comment by curran** [comment]
I suppose the key that will allow more folks to help is the ability to reproduce the behavior. It may be worthwhile to create a mostly-boilerplate Electron app whose sole purpose is to reproduce this behavior.

**Comment by mbostock** [comment]
Sounds like responseXML is unsupported in that environment.

I’ll change d3.xml to throw an error in that case rather than return
undefined, but that won’t really fix your problem. Unclear whether you can
get a detached DOM with Electron or if you will have to resort to string
manipulation.

**Comment by iyogeshjoshi** [comment]
@curran @mbostock on tracing and doing some debugging I found that in `d3-request` module there are few things I figured:
* When I'm not providing any protocol like 'file://' or 'http://' it's not throwing any error
* I don't know exactly why and how but for some reason even if I give 'http://' protocol it wasn't giving error when my _apache2.server_ was running 
* After adding protocol and stopping apache server, I'm getting __Parse Error__ with:

**Comment by mbostock** [comment]
Regarding my previous comment, I had forgotten that in d3/d3-request@fdcb8bc9641739aa79429b101e5a88ae5684d03b (#2659) we already check if the response is missing a throw a parse error.

Regarding your debugging, it sounds like you are trying to make a cross-domain request without the necessary Access-Control-Allow-Origin response header (see http://enable-cors.org). If that happens, regardless of what your server serves (even a 404 response code), the browser doesn’t allow any of the response to be visible to the client, so the resulting status is zero and d3-request can’t distinguish between a success and a failure. The resulting responseXML is undefined, and so a parse error is thrown.

Possibly we should always consider a status of zero an error, but that status is also set when making local requests out of the file system. See 95b1eaaf68a1e75e6cf95b88d7e4bbc834b8489d. However most browsers no longer allow this for security reasons, so it might be worth dropping.

**Comment by mbostock** [comment]
Update: based on 95b1eaaf68a1e75e6cf95b88d7e4bbc834b8489d it looks like the zero status applies not just to the local file system but to other local requests such as chrome-extension:// and some other protocols I’m not familiar with, so I think it would be best to not change this behavior.

**Comment by iyogeshjoshi** [comment]
@mbostock The CORS reason seems to be valid but in Electron they have option to disable _web-security_, even after disabling it wasn't working so I'm not sure whether _web-security_ flag in electron is not working or D3. I'll Dig into this, will try everything from scratch till then we can keep this issue close :)
