### ISSUE TITLE
angular2 installation of d3

### ISSUE THREAD

**Issue by estradamarkie** [d3/d3#2900]
Hi,

Just wondering how to properly install d3js into angular2 project? I installed it using npm install d3 and import import * as d3 from 'd3'; in my .ts file but IDE is giving me a redline saying "can't find module".

I've also added it in my systemjs.config.js
var map = {
    'd3':                         'node_modules/d3/build'
 };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'd3':                          { main: 'build.js', defaultExtension: 'js'},
  };

**Comment by mbostock** [comment]
Sorry, but I don’t know anything about Angular2 so I can’t say how it needs to be configured.

If you’re trying to find D3’s ES2015 module definition, it’s defined by the jsnext:main field in the [package.json](https://github.com/d3/d3/blob/master/package.json) and it currently resolves to [index.js](https://github.com/d3/d3/blob/master/index.js). If you’ve installed D3 using `npm install d3` then you’ll find it in node_modules/d3/index.js.

If you’re trying to find D3’s UMD bundles, there are actually three. The [build/d3.js](https://npmcdn.com/d3/build/d3.js) and [build/d3.min.js](https://npmcdn.com/d3/build/d3.min.js) bundles are for the browser, including AMD. There is also a CommonJS bundle for Node, [build/d3.node.js](https://npmcdn.com/d3/build/d3.node.js).

**Comment by estradamarkie** [comment]
Hi,

Thanks for your answer, I did try node_modules/d3/index.js however its saying tracerur.js is missing, does d3js using  tracerur dependency or vise versa?

**Comment by mbostock** [comment]
D3 does not depend on Traceur. Perhaps Angular is assuming that Traceur is
(incorrectly) needed because of the use of ES2015 modules. But that is the
only ES2015 feature used by D3 so there are no runtime dependencies.

**Comment by LucidityDesign** [comment]
@estradamarkie could you solve this problem?

**Comment by SV-efi** [comment]
This is the same problem I am facing. I am using 
Angular : 2.1.1,
Type Script : 2.0.10,
Did an npm install d3

Typescript was not finding the d3 module, I made these changes changes in system.config.js  
`System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/',
            'typings:':'typings/'
          },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            // other libraries
            **'d3':'npm:d3'**
         },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            
            **d3: {
                defaultExtension: 'js',
                main : 'index.js'
            }**
        }`. 
After this the d3 import was resolved. However I am getting a 404 on Traceur. 

Installed traceur module.  Then NONE of the d3 modules were resolved. All got a 404. 

At wits end here.

**Comment by SV-efi** [comment]
Looks like I am not alone. Stackoverflow has lots of questions and very little approved answers 
http://stackoverflow.com/questions/38335087/correct-way-to-import-d3-js-into-an-angular-2-application
