### ISSUE TITLE
Possible Error in Change Log?

### ISSUE THREAD

**Issue by danielstern** [d3/d3#2901]
The scale example in the change log
`d3.scaleLinear().domain([10, 0]).ticks(5); // [10, 8, 6, 4, 2, 0]`
Link: https://github.com/d3/d3/blob/master/CHANGES.md#scales-d3-scale

Gives the following error:

`Uncaught TypeError: scale.domain is not a function`
(Version 4.1.1)

**Comment by whatwehaveunlearned** [comment]
I don’t get that error in chrome running  v4.1.1…
It works properly for me.
 
Alberto González Martínez
whatwehaveunlearned@gmail.com

**Comment by mbostock** [comment]
Unable to reproduce. Here’s a working example:

https://tonicdev.com/5775df609f199c13001afdd5/5785868fad8ae313008d5fd4

If you want me to investigate further please post a link to a live example demonstrating the problem on bl.ocks.org / gist.github.com.
