### ISSUE TITLE
Tiny link typo in API reference

### ISSUE THREAD

**Issue by Dev-Lan** [d3/d3#2904]
On the [main API Reference Page](https://github.com/d3/d3/blob/master/API.md#ordinal-scales)

the link to d3.axisBottom actually links to axisTottom (https://github.com/d3/d3-axis/blob/master/README.md#axisTottom) instead.

**Comment by mbostock** [comment]
Thanks. Feel free to send a PR if you’d like to fix, or I will when I have a moment.

**Comment by Dev-Lan** [comment]
Just sent a pull request.

**Comment by mbostock** [comment]
Thank you!
