### ISSUE TITLE
General Update Pattern works with v3 but not with v4

### ISSUE THREAD

**Issue by urbanhop** [d3/d3#2908]
The example http://bl.ocks.org/mbostock/3808221 was last updated February 8, 2016, so I guess it is still relevant. It works with v3, but not with v4. With version 4, the new elements from the enter() selection are not updated.

To analyze this, I modified the example, so it updates the data upon click. The initial update however reveals the issue already:

http://urban-hop.com/d3/update-enter.v3.htm
http://urban-hop.com/d3/update-enter.v4.htm

Condensed, this code reveals the different behavior:

    <!DOCTYPE html>
    <meta charset="utf-8">
    <style>
        span {
            font: bold 12px monospace;
            margin: 6px;
            outline: solid 2px #333;
            padding: 4px;
            display: inline-block;
        }
        .enter {
            background: coral;
        }
        .update {
            background: yellowgreen;
        }
    </style>
    <body>
    </body>
    <script src="//d3js.org/d3.v4.min.js"></script>
    <script>

        var c = d3.select("body").append("div").attr("id", "container");
        var data = "1234567890".split("");

        // DATA JOIN
        // Join new data with old elements, if any.
        var sel = c.selectAll("span")
            .data(data);

        // ENTER
        // Create new elements as needed.
        sel.enter().append("span")
            .attr("class", "enter");

        // ENTER + UPDATE
        // Appending to the enter selection expands the update selection to include
        // entering elements; so, operations on the update selection after appending to
        // the enter selection will apply to both entering and updating nodes.
        console.log("sel", sel);

        sel.text(d => d); // <<<<< does not work with v4. works with v3

    </script>

workaround: do a fresh selection

    c.selectAll("span").text(d => d)

**Comment by mbostock** [comment]
The selection API has changed; please see the [release notes](https://github.com/d3/d3/blob/master/CHANGES.md#selections-d3-selection).  Please see the new [General Update Pattern 4.0](http://bl.ocks.org/mbostock/a8a5baa4c4a470cda598) example. I will be updating the 3.x examples to 4.0 as I have the time.
