### ISSUE TITLE
SVG attribute namespaces

### ISSUE THREAD

**Issue by lynaghk** [d3/d3#291]
I'm looking into using D3 to create `<svg>`s that I can convert to PDF, and I've been spending a lot of quality time learning about XML namespaces:

https://developer.mozilla.org/en/SVG/Namespaces_Crash_Course

I'd like to write a patch for D3 to prefix attribute namespaces explicitly, so that they show up in the DOM and exporting back to XML is easier.
Quoting from that article,

> For setting attributes that have a namespace, it is recommended (but not required) that you also include their prefix in the second argument so that the DOM can later be more easily converted back to XML (if for instance you want to send it back to the server). For example:
> 
> ``` javascript
> elt.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', 'otherdoc.svg');
> ```

Right now to get an explicit prefix one has to tell D3 twice:

``` javascript
div.append("svg").attr("xmlns", "http://www.w3.org/2000/svg")
  .attr("xmlns:xmlns:xlink", "http://www.w3.org/1999/xlink");
```

``` html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>
```

Is there anything that would go terribly wrong if we started using explicit prefixes on the attributes?
If not, I'll submit a pull request implementing this (and I'll patch #272 as well).

**Comment by jchamberlain** [comment]
I'd love to see some further discussion on this as I too need to serialize SVG elements for use in PDFs, and am encountering namespace errors.

**Comment by timiyay** [comment]
I am currently in the midst of this issue, and I find the use of `.attr()` to be unclear.

My use case is using an external `<image>` tag as a `<pattern>`, which is use the fill a `<path>`.

I try using `attr()` to set the `image.href` like so:

```js
imageSelection.attr({ 'xlink:href': myUrl })
```

However, the resulting markup only has `<image href="myUrl">` - the `xlink` namespace is dropped.

While this doesn't affect the SVG in the browser, it breaks down when trying to do other stuff like:  

* pre-render SVGs on the server, and convert them to JPG / PNG
* embed the SVGs inside PDFs

**Comment by mbostock** [comment]
The extra semicolon tricks D3 into calling:

```js
element.setAttribute("xlink:href", url);
```

instead of use the correct namespaced attribute, which is:

```js
element.setAttributeNS("http://www.w3.org/1999/xlink", "href", url);
```

I suppose that’s a reasonable hack to workaround shortcomings in a server-based DOM implementation that doesn’t support namespaced attributes in SVG. But there’s no guarantee that will continue to work in future D3 releases.

**Comment by Fil** [comment]
Thanks, it was impossible to imagine the extra semicolon trick.

**Comment by mbostock** [comment]
Related d3/d3-selection#94.

**Comment by Fil** [comment]
My use case was making a svg compatible with Inkscape, I needed `inkscape:groupmode="layer" inkscape:label="layer name"`.
https://github.com/visionscarto/fonds-de-cartes/commit/a47ef7a5855f9fb4504cb7ad76194f15abfe6dde
