### ISSUE TITLE
Nested selection does't allow an attribute object.

### ISSUE THREAD

**Issue by ha8012** [d3/d3#2915]
When I was trying to do nested selection, none of the attribute were applied to the element. I tried setting the attributed individually in the child element and it worked fine. 

focus.selectAll("path.area")
      .data(stack(data), function(d){ return d;})
      .enter()
      .append("path")
      .attr("class", "area")
      .attr("d", area)
      .style("fill", function(d) { console.log(d); return z(d.key); })
      .selectAll("circle.c").data(function(d){ return d; })
      .enter()
      .append("circle")   
      .attr("class", "c") //Here i coouldn't just pass an object. i had to set each attr separately. 
      .attr("cx", 100)
      .attr("cy", 100)
      .attr("r", 40) 

I appreciate all the hard work on the new release.

**Comment by mbostock** [comment]
You must use [d3-selection-multi](https://github.com/d3/d3-selection-multi) if you want multi-value map methods. Per the [release notes for d3-selection](https://github.com/d3/d3/blob/master/CHANGES.md#selections-d3-selection):

> For the sake of parsimony, the multi-value map methods have been extracted to [d3-selection-multi](https://github.com/d3/d3-selection-multi) and are no longer part of the default bundle. The multi-value map methods have also been renamed to plural form to reduce overload: [*selection*.attrs](https://github.com/d3/d3-selection-multi#selection_attrs), [*selection*.styles](https://github.com/d3/d3-selection-multi#selection_styles) and [*selection*.properties](https://github.com/d3/d3-selection-multi#selection_properties).

**Comment by ha8012** [comment]
Got it. Thank you very much for the quick feedback.
