### ISSUE TITLE
Revert from "zooming ignores events at the limits of the scale extent" in v4.x

### ISSUE THREAD

**Issue by IftachSadeh** [d3/d3#2917]
Hello, 

A new feature of zooming in `v4.x` is 

> The zoom behavior now ignores wheel events at the limits of its scale extent, allowing you to scroll past a zoomable area. 

This actually disrupts some implementations and is not always a desired feature. For instance, in a case where one zooms in and out a lot, users tend to overshoot the zoom out with the mouse wheel. They then end up inadvertently scrolling the page. The only way to scroll the page back up is to leave the active area, since the counter direction of the mouse wheel can only zoom back in...

Is it possible to somehow return to the old behavior, where zoomable areas do not revert to page scrolling?

Thanks,

**Comment by mbostock** [comment]
You can implement this by registering your own wheel event listener (typically AFTER applying the zoom behavior so that your event listener is only invoked if the zoom behavior does not handle the event) and calling d3.event.preventDefault.

**Comment by IftachSadeh** [comment]
Thank you for the quick replay, and for your superb work on this project!
