### ISSUE TITLE
brush.extent not dynamically updated

### ISSUE THREAD

**Issue by gaelicmichael** [d3/d3#2918]
I have a visualization that rescales itself whenever the window resize is triggered. My code is calling brush.extent() with the new pixel size (of parent SVG element), but it does not seem to get updated, as the brush is still constrained to the initial pixel size.

You can see this in action at: http://dhpress.unc.edu/gig-dev/prsp-exhibit/celtic-database/

Choose "Iron Age Chronology" with the drop-down menu, enlarge the display size and try moving the brush.

**Comment by mbostock** [comment]
After you call *brush*.extent to set the new extent, you must re-apply the brush via *selection*.call(*brush*). The brush does not capture references to the elements you previously applied it to, so you must re-apply the brush when you make any changes either via *brush* or *brush*.move.

**Comment by gaelicmichael** [comment]
Thank you for the explanation. That was not at all clear to me from the documentation or the example. BTW, I call brush.move() and it works properly without calling selection.cal(brush).

**Comment by mbostock** [comment]
That only works because you passed a selection to brush.move, which is
equivalent to using selection.call.

**Comment by mbostock** [comment]
Thanks for the feedback; I have made a note to myself to clarify the documentation in this matter (probably something similar to the comment for *brush*.handleSize).

**Comment by gaelicmichael** [comment]
That did indeed fix it. I hope I need not add that D3 is one of the best JS libraries ever and I respect your work greatly.

**Comment by mbostock** [comment]
Thank you!
