### ISSUE TITLE
attr no longer accepts objects?

### ISSUE THREAD

**Issue by sbromberger** [d3/d3#2919]
It used to be that you could do
```javascript
var foo = d3.select(...);
var a = {'id':'bar', 'class':'baz'};
foo.attr(a);
```

in v4, this doesn't appear to work. If one has a set of attributes in an object, is there an alternative way of setting them as attributes on a selected element? Thanks.

**Comment by mbostock** [comment]
See https://github.com/d3/d3-selection-multi and search these issues for additional context if desired.

**Comment by sbromberger** [comment]
Thank you. I'm sorry I didn't see this earlier....

**Comment by sbromberger** [comment]
Ref #2907 for future searchers.
