### ISSUE TITLE
__esModule true in build/d3.js?

### ISSUE THREAD

**Issue by alanshaw** [d3/d3#2921]
In the current version of d3 (4.1.1) installed via npm the built d3.js (in `node_modules/d3/build/d3.js`) includes the line:

```js
Object.defineProperty(exports, '__esModule', { value: true });
```

Should it?

I'm finding d3 is `undefined`  when I `import d3 from 'd3'`

Babel is generating this:

```js
var _d = require('d3');
var _d2 = _interopRequireDefault(_d);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

...and later in the same file my transpiled code does this:

```js
const layout = _d2.default.tree().size([height, width]);
```

However `d3.js` seems to be assigning directly to the `module` object and so `_d2.default` is `undefined`.

Can anyone help?

**Comment by mbostock** [comment]
There’s no default export from D3, so `import d3 from 'd3'` isn’t supposed to work. Did you mean to say `import * as d3 from 'd3'`?

As for \_\_esModule, that is something inserted by Rollup to indicate that the UMD bundle was transpiled from ES2015 modules, which is the case with all the D3 modules; see rollup/rollup#496.

**Comment by alanshaw** [comment]
:thumbsup: thank you!
