### ISSUE TITLE
Create codemods to port 3.x code to 4.x

### ISSUE THREAD

**Issue by jfsiii** [d3/d3#2925]
While [CHANGES.md](https://github.com/d3/d3/blob/master/CHANGES.md) does a great job of outlining the name & behavior changes, it'd be great if there was a mechanical way to convert 3.x code to 4.x. [codemods](https://medium.com/@cpojer/effective-javascript-codemods-5a6686bb46fb#.p2f4pua6s) would be an effective way to do this.

Not all changes would be easily represented in a codemod (the [selection changes](https://github.com/d3/d3/blob/master/CHANGES.md#selections-d3-selection) come to mind), most should be trivial (especially all affected by "the great namespace flattening").

It'd be a shame if the vast collection of 3.x code was stuck on that version because conversion was deemed too difficult or not worth it. This is especially true for the many libraries which build their reusable charts on d3. I did a survey of some popular ones a few weeks ago and *none of them* had any branches or tickets for 4.x. I opened tickets to discuss the migration, but this would be a great help to them (and all their customers).

**Comment by mbostock** [comment]
This is a fun idea, and it would be great if you or someone else wants to take a crack at it. However, it’s not something I am going to pursue, so I’m going to close this issue. Sorry, and thank you!

**Comment by jfsiii** [comment]
In case anyone else is interested in this, I recently found https://github.com/expobrain/d3-upgrade-codemods

The README says it's incomplete, and I haven't tried it, but it's worth a look.
