### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by TrySound** [d3/d3#2926]
Hi, Mike.

I just released [rollup-plugin-node-resolve@2](https://github.com/rollup/rollup-plugin-node-resolve/commit/3befb3ba9856a375881708258e39c7c7a7d63e86) which introduces module field for es modules. I enabled it by default to simplify configuration a bit. It's already supported by webpack. Would be great if you will add it to your packages. And please don't remove jsnext:main until new major version to prevent deploys breaking.

**Comment by mbostock** [comment]
Thanks for the heads up. Can you point me to a discussion regarding the
motivation for this change?

**Comment by TrySound** [comment]
https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md

**Comment by mbostock** [comment]
Okay, I can do that.

**Comment by mbostock** [comment]
Fixed in 4.2.1.

**Comment by TrySound** [comment]
Thanks!
