### ISSUE TITLE
Is there place for a PR to v3

### ISSUE THREAD

**Issue by amenadiel** [d3/d3#2930]
I've built [an ES6 fork of v3.5.17 that is also passing `vows` tests](https://github.com/amenadiel/d3/tree/v3_es6). (without destructive changes, mind you)

I know that d3 has moved on from v3, but some other libs (c3, nvd3) rely on d3@3 to work, so I'm using my fork to allow for tree shaking sweetness.

Is there a branch against which I could open a PR? It might help someone out there.

**Comment by mbostock** [comment]
Alas, I do not have the resources to maintain parallel versions of D3. You are welcome to maintain your own fork of v3, but all of my efforts are put towards v4 and later. Sorry and thank you for your understanding!
