### ISSUE TITLE
Article on upgrading to 4.0?

### ISSUE THREAD

**Issue by eglassman** [d3/d3#2931]
Dear developers,

I have a non-trivial interface rendered with d3 3.0. I'm considering whether or not it makes sense to upgrade it to 4.0. I found a previously written post within this repo helping users upgrade to 3.0: https://github.com/d3/d3/wiki/upgrading-to-3.0 Is anyone considering writing a similar post for the process of upgrading to 4.0? It would be very helpful for making that decision and implementing all the necessary changes.

**Comment by mbostock** [comment]
The short summary is here:

https://github.com/d3/d3/releases/v4.0.0

The comprehensive guide is here:

https://github.com/d3/d3/blob/master/CHANGES.md

Irene Ros (@iros) recently posted this summary here:

https://iros.github.io/d3-v4-whats-new/
