### ISSUE TITLE
Documentation for v4 is pretty much non-existant and tutorials on the tutorials page are out of date.

### ISSUE THREAD

**Issue by jeremysmitherman** [d3/d3#2932]
And the v4 section of the tutorials on the wiki are useless for new users

**Comment by jeremysmitherman** [comment]
And the v4 section is pretty useless for new people to the project

**Comment by mbostock** [comment]
There is a ton of documentation for v4:

https://github.com/d3/d3/blob/master/CHANGES.md
https://github.com/d3/d3/blob/master/API.md

If you’re looking for tutorials specifically (and not the API reference and release notes), then yes many tutorials were written over the five prior years of D3’s existence before v4. I can’t force people to update their old tutorials. I expect more tutorials to be written and updated in the coming years.

**Comment by jeremysmitherman** [comment]
Fair enough, I added a link to the tutorials wiki page referencing the changes files because that would have been super helpful for me as a brand new user.  Feel free to revert it if you feel it is unnecessary
