### ISSUE TITLE
Want to know about the updates on 3D Honeycomb Bar Chart, 3D Bar Chart.

### ISSUE THREAD

**Issue by kishorjadhav** [d3/d3#2937]
Hi , I just want to know the details and date when 3D Honeycomb Bar Chart & 3D Bar Chart  was added to the official D3 site. Need to report to my higher authorities. Please let me know.

**Comment by mbostock** [comment]
The D3 wiki is publicly editable. If you want to find when a particular change was made (and who made it), it’s probably easiest to clone the backing git repository and then grep the changes.

```
git clone https://github.com/d3/d3.wiki.git
git log -p -- Gallery.md
```
