### ISSUE TITLE
cannot read property 'line'/'svg' of undefined

### ISSUE THREAD

**Issue by rishi2893** [d3/d3#2939]
I had installed 'd3' using **npm install d3 --save**. But the above error comes up in the browser. Here is the [link](http://stackoverflow.com/questions/38880793/integrating-react-with-d3) to my question on stackoverflow:

Later I figured out that there might be no API like **d3.svg.line()** in the latest version of d3. So I replaced it with **d3.line()**. I got the error **cannot read property line of undefined **. Am I importing stuff correctly? Do I need to modify my **webpack.config.js** file? My webpack.config.js file is same as that found [here](http://www.tutorialspoint.com/reactjs/reactjs_environment_setup.htm)

Please help!!! Been stuck here like forever.

**Comment by mbostock** [comment]
Per the [README](https://github.com/d3/d3/blob/master/README.md), you need to import D3 as a namespace if you want to import everything:

```js
import * as d3 from "d3";
```

There is no default export from d3, so this doesn’t work:

```js
import d3 from "d3";
```

If there are any Webpack-specific issues, I can’t advise on those.
