### ISSUE TITLE
d3.scaleOrdinal is not a function

### ISSUE THREAD

**Issue by stewiegaribaldi** [d3/d3#2942]
I'm using meteor's d3js:d3, am I right to assume that the meteor's package is not updated?
If so, could we possibly update it?

**Comment by mbostock** [comment]
Sorry, but I don’t maintain Meteor’s copy of D3; the only supported publishing systems are [npm](https://www.npmjs.com/package/d3) (see also [npmcdn](https://npmcdn.com/d3/)), [GitHub releases](https://github.com/d3/d3/releases) and [d3js.org](https://d3js.org/d3.v4.js).

**Comment by stewiegaribaldi** [comment]
Thank you, I'll use npm. Great package!
