### ISSUE TITLE
CII best practices badge

### ISSUE THREAD

**Issue by david-a-wheeler** [d3/d3#2943]
Can I convince someone here to try to get for d3.js a “best practices” badge from the Linux Foundation Core Infrastructure Initiative (CII)? I’m the technical lead of the badging project. Someone from the project simply needs to go here and click on “Get Your Badge Now!”:
https://bestpractices.coreinfrastructure.org/

It’s basically a web form, and it shouldn’t take more than hour to fill it in for Blender. It costs nothing. We can help you (if you’d like) once you get started. I’d be happy to answer questions, too.  Node.js already has a badge; other projects with the badge include curl, the Linux kernel, and OWASP ZAP.

Let me know. Thanks!!

**Comment by mbostock** [comment]
Hi David. I appreciate the educational goals of the best-practices project, but I’m afraid I’m not currently willing to spend the time to fill out the form.

**Comment by david-a-wheeler** [comment]
It's not really just educational, and we can help with the time.

**Comment by david-a-wheeler** [comment]
Even if you did it by yourself, it should not take more than an hour.
