### ISSUE TITLE
ES6 style - import d3 from 'd3', the d3 is undefined

### ISSUE THREAD

**Issue by slashtu** [d3/d3#2950]
If I use ES6 style, the d3 is undefined
   ``` 
    import d3 from 'd3';
   ```

but It works on using require
   ``` 
    var d3 = require('d3');
   ```

**Comment by mbostock** [comment]
Please read the [README](https://github.com/d3/d3/blob/master/README.md#installing).

**Comment by connor11528** [comment]
`import * as d3 from "d3";`

**Comment by JerryWiltz** [comment]
Is d3 in the umf format in this case?
