### ISSUE TITLE
scale.linear is broken in v4

### ISSUE THREAD

**Issue by sachi-d** [d3/d3#2951]
The use of `d3.scale.linear() ` works fine with [v3](https://d3js.org/d3.v3.min.js) but not with [v4](https://d3js.org/d3.v4.min.js). 

I get the error 

> Uncaught TypeError: Cannot read property 'linear' of undefined

`

**Comment by sachi-d** [comment]
Solution found: https://github.com/d3/d3/blob/master/CHANGES.md#scales-d3-scale

**Comment by shegde4** [comment]
Hey Sachi, I am  a beginner in d3js, can you elaborate on what I need to fix ?
Thanks in advance.

**Comment by shegde4** [comment]
im sorry figured that out :) thanks !
