### ISSUE TITLE
[Request] zoom behaviour persist when mousemove event is added

### ISSUE THREAD

**Issue by ApolloTang** [d3/d3#2964]
With 'mousemove' event added, zoom behaviour is removed, for example:

```
    // bind zoom behavior
    selection_svg.call(
        d3.behavior.zoom()
        .translate([0, 0])
        .scale(1)
        .scaleExtent([1, 14])
        .on('zoom', ()=>{ selection_plotArea.attr('transform', 'translate('+d3.event.translate+')scale('+d3.event.scale+')'); })
    );

    // tool tip coordinate
    const toolTipNode = selection_toolTip.node();
    toolTipNode.style.position = 'absolute';
    selection_svg.node().addEventListener('mousemove', function(evt){
        const coord_client = {
            x:evt.clientX,
            y:evt.clientY,
        }
        toolTipNode.style.left = `${coord_client.x}px`;
        toolTipNode.style.top = `${coord_client.y}px`;
    }, false);
```

Because of this I am unable to track mouse cursor position without losing zoom behaviour.
 
Zoom behaviour is initiated on mousedown or on wheel scroll; when mouse button is not pressed or wheel is not scrolled, we should be able to trigger mousemove event while zoom listener remain attached.

**Comment by mbostock** [comment]
My apologies, but I am no longer maintaining D3 v3. Please upgrade to v4 to fix this bug.

**Comment by ApolloTang** [comment]
If you stumble into this same problem as me, the solution has been posted at:

http://stackoverflow.com/questions/39322238/d3-zoom-behaviour-is-overwriten-by-mousemove-event
