### ISSUE TITLE
attribute x: Expected length, "NaN" error

### ISSUE THREAD

**Issue by methikas** [d3/d3#2965]
When performing a dimple bar chart filter using the legend, d3 throws the following error:

attribute x: Expected length, "NaN".

Please see below jsfiddle for error. 
https://jsfiddle.net/fbpnzy9u/

click on a legend to filter chart. open dev tools and inspect console.
Should see above error from d3.

**Comment by curran** [comment]
This seems like a problem with Dimple, not D3.

I see you also filed an issue at https://github.com/PMSI-AlignAlytics/dimple/issues/248

**Comment by methikas** [comment]
Yes. Raised the issue with dimple. Since the crash appears to be thrown internally from d3.js, thought it might be worth raising it with d3 too.
