### ISSUE TITLE
D3.csv not supported in d3-dsv

### ISSUE THREAD

**Issue by my1stcar** [d3/d3#2972]
Hi,
I tried to just import d3-dsv.v1.js to use the function of d3.csv("file"..) to read external file. But it seems d3.csv function is not found in the d3-dsv module. Though it works if I use d3.v4.js, but I really like to know which module this function d3.csv is defined? Thanks a lot.
NewtoD3

**Comment by geekplux** [comment]
It's in `d3-request`. You could find what module you want in the [API doc](https://github.com/d3/d3/blob/master/API.md).
