### ISSUE TITLE
unable to rotate albersUsa projections

### ISSUE THREAD

**Issue by Fallenstedt** [d3/d3#2988]
This is not a critical issue, however, I noticed that I am only able to apply rotation to specific d3.geo projections. I cannot apply rotation to an albersUsa projection https://github.com/d3/d3-3.x-api-reference/blob/master/Geo-Projections.md

```
  function makeUsaProjection(scale) {
    return function(element) {
      var projection =  d3.geo.albersUsa()
      .scale(scale? scale : (element.width + 1) / 2 / Math.PI)
      .translate([element.offsetWidth / 2, element.offsetHeight / (2)]);

      var path = d3.geo.path()
      .projection(projection);

      return {path: path, projection: projection};
    }
  }

```

The code above will generate albersUsa map for me, however, when I specify a rotation on my projection:

> .rotate([10,10,10])

I receive the following error:

> explore-maps.js:497 Uncaught TypeError: d3.geo.albersUsa(...).rotate is not a function

I'm not sure why I can apply rotations to specific projections, and not the albersUsa map.

**Comment by mbostock** [comment]
It doesn’t make sense to rotate d3.geoAlbersUsa—it’s a composite projection specific to the contiguous forty-eight states, Hawai’i, and Alaska. If you rotated it, those countries would not fit into the designated parts of the display.

Internally, d3.geoAlbersUsa is backed by three projections (all Albers conic equal-area projections) which have hard-coded rotations. See [albersUsa.js](https://github.com/d3/d3-geo/blob/master/src/projection/albersUsa.js#L28-L30) for details.

**Comment by Fallenstedt** [comment]
I see. Some people have resorted to extended the d3.geo library. https://groups.google.com/forum/#!topic/d3-js/S65V7St8MAw

Thanks for the explanation @mbostock!

**Comment by mbostock** [comment]
Ah, yes. If you want to change how the projection is configured, it’s probably easiest to just copy the implementation and design a new composite projection. There’s not currently a general facility for composite projections in d3-geo.

**Comment by mbostock** [comment]
Although, see [d3-composite-projections](http://geoexamples.com/d3-composite-projections/) for exactly that.

**Comment by Fallenstedt** [comment]
Incase anyone comes wondering how they can rotate their albsersUsa projection, I dug through object that is generated and applied a style via javascript: 

`  var usaSvg = map.svg[0][0].childNodes[0];
  var dotsSvg = map.svg[0][0].childNodes[1];

  usaSvg.setAttribute('transform', 'rotate(-2)');
  dotsSvg.setAttribute('transform', 'rotate(-2)');`
