### ISSUE TITLE
d3.zoom defaultExtent error when SVGSVGElement does not have width or height properties.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [d3/d3#2991]
Getting an error with SVGSVGElement not having a width property implemented with PhantomJS, (I'll probably lodge an issue with them as well).

I figure it gets the width and height of the parent SVG element.

In Google Chrome the SVG node has a .width property as an instance of SVGAnimatedLength
One thing that comes to mind is that this might be used for the case of SVG inside SVG with animation/translation on them?

```
function defaultExtent() {
  var e = this, w, h;
  if (e instanceof SVGElement) {
    e = e.ownerSVGElement || e;
    w = e.width.baseVal.value;
    h = e.height.baseVal.value;
  } else {
    w = e.clientWidth;
    h = e.clientHeight;
  }
  return [[0, 0], [w, h]];
}
```
I ended up wrapping it in a try catch.
Tried to add properties to the SVGSVGElement object for width and height but it just would not use them.

```
  function defaultExtent() {
    var e = this, w, h;
    if (e instanceof SVGElement) {
      e = e.ownerSVGElement || e;
      try {
        w = e.width.baseVal.value;
        h = e.height.baseVal.value;
      } catch (e) {
        w = this.clientWidth;
        h = this.clientHeight;
      }
    } else {
      w = e.clientWidth;
      h = e.clientHeight;
    }
    return [[0, 0], [w, h]];
  }
```

Maybe not an ideal fix.

**Comment by mbostock** [comment]
Refiled as d3/d3-zoom#63.
