### ISSUE TITLE
projectionStream is not a function.

### ISSUE THREAD

**Issue by 16am** [d3/d3#2999]
We are working on this website http://bandaultralarga.italia.it/mappa-bul/

On that page we have a gMap where we draw some polygons on top, using d3(v3) and topoJson.

Now we want (would like) to switch to the new v4 to add new data viz design on the page but keeping what we already had.

Troubles come in the overlay function below where we translate the coordinates into the Google Map system.

We just tried to switch from:
`path = d3.geo.path().projection(googleMapProjection);`
to:
`path = d3.geoPath().projection(googleMapProjection);`
but this generates the subject error (projectionStream is not a function.)

Any clue to get this to work again?

```
var overlay = new google.maps.OverlayView();

        overlay.onAdd = function () {

            var div = document.createElement('div');
            div.id = 'svg_map';
            div.style.borderStyle = 'none';
            div.style.borderWidth = '0px';
            div.style.position = 'absolute';
            this.getPanes().overlayMouseTarget.appendChild(div);

            overlay.draw = function () {

                var overlayProjection = this.getProjection();

                var googleMapProjection = function (coordinates) {
                    var googleCoordinates = new google.maps.LatLng(coordinates[0], coordinates[1]);
                    var pixelCoordinates = overlayProjection.fromLatLngToDivPixel(googleCoordinates);
                    return [pixelCoordinates.x + 4000, pixelCoordinates.y + 4000];
                };

                path = d3.geoPath().projection(googleMapProjection); // Here is where troubles come

                generaOverlay(overlay, datiShape);

            };

        };
        overlay.setMap(map);
```

**Comment by ThomHurks** [comment]
Spelling mistake. There is an X in projection ;) Also please use
StackOverflow.

**Comment by 16am** [comment]
Well, yeah I had noticed I misspelled it while writing my issue, then edited...
Anyway it's spelled right in my code so the error is still there.
I will try on StackOverflow.
Thank you ThomHurks!

**Comment by mbostock** [comment]
Please read the [d3-geo release notes](https://github.com/d3/d3-geo/releases/v1.0.0) or [CHANGES.md](https://github.com/d3/d3/blob/master/CHANGES.md#geographies-d3-geo):

> “Fallback projections”—when you pass a function rather than a projection to [*path*.projection](https://github.com/d3/d3-geo#path_projection)—are no longer supported. For geographic projections, use [d3.geoProjection](https://github.com/d3/d3-geo#geoProjection) or [d3.geoProjectionMutator](https://github.com/d3/d3-geo#geoProjectionMutator) to define a custom projection. For arbitrary geometry transformations, implement the [stream interface](https://github.com/d3/d3-geo#streams); see also [d3.geoTransform](https://github.com/d3/d3-geo#geoTransform).

**Comment by danaAtmeh** [comment]
I am having the same issue and I am interested on how you solve it  @16am
