### ISSUE TITLE
BSD license of D3.js means is free for even commercial usage is...?

### ISSUE THREAD

**Issue by lse123** [d3/d3#3001]
BSD license of D3.js means is free for even commercial usage is...?

**Comment by mbostock** [comment]
If you have a question about how to interpret standard open-source licenses, I suggest you consult [opensource.org](https://opensource.org/licenses) or your own legal counsel. My apologies, but I cannot provide legal advice.

**Comment by lse123** [comment]
so exist fee?

**Comment by lse123** [comment]
too many legal info and get confused... well

**Comment by mbostock** [comment]
There is no fee, but there is a license, and I suggest you understand the license before using any open-source software.

**Comment by lse123** [comment]
can you say full url of developer's matters of usage?
