### ISSUE TITLE
D3 scaleTime bug with daylight saving time.

### ISSUE THREAD

**Issue by gbarchik** [d3/d3#3011]
I'm working in a Ionic/Cordova app that has an Price/Time chart and now, on October, the app just started to freeze in the iOS platform. No error messages, no crashes at all, just freeze the app.

When debugging it I've discovered that this is caused by scaleTime, when the first date is in a regular timezone (BRT) and the second one is in a daylight saving timezone (BRST). I'm trying to solve it using a GMT time, but it isn't working anyway.

May you guys look in d3 core code to a way to solve it?
Thanks..

**Comment by mbostock** [comment]
As noted in the issue template, please read the instructions on how to report an issue:

https://gist.github.com/mbostock/370b737ce71bed0749e103b01ce1bfaf

If you’d like me to investigate, please post a minimal test case on bl.ocks.org that demonstrates the issue, and then submit a new issue in the appropriate repository, such as [d3-time](https://github.com/d3/d3-time). Without code to reproduce this issue, there is no way for me to investigate. 

From your description, my guess is there could be a browser bug on iOS that causes a [time interval](https://github.com/d3/d3-time/blob/master/src/interval.js) to go into an infinite loop. I’d suggest trying methods such as *scale*.ticks to see if you can reproduce the infinite loop, and once you can, post the corresponding code to bl.ocks.org or https://runkit.com/npm/d3-time and open a new issue, and I’ll see if I can fix the problem. Thanks.

**Comment by gbarchik** [comment]
Thank you @mbostock and sorry by the poor bug description, I was king of lost because there is no errors, etc.. Now I found this issue that could help: https://github.com/d3/d3/issues/2375

Well.. Thank you again..
