### ISSUE TITLE
I want to use demo

### ISSUE THREAD

**Issue by dalisoft** [d3/d3#3016]
Hi

I want to use D3js demo in my application. I want make it private and premium. But not want release it under GPLv3. Can i use?

For more: https://gist.github.com/mbostock/7f063e44c57ecb5828dd5643e61f92d3

ARE YOU REPORTING AN ISSUE? Please file an issue on the relevant D3 module, not here; see https://github.com/d3. Please isolate the specific methods that exhibit unexpected behavior and precisely describe how your expectations were not met.

For more: https://gist.github.com/mbostock/370b737ce71bed0749e103b01ce1bfaf

**Comment by jagthebeetle** [comment]
This seems best to consult legal counsel about, but perhaps a starting
point:
https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem

**Comment by mbostock** [comment]
The library is BSD licensed. My examples are separately GPL licensed. See opensource.org for more information on these licenses, or consult a lawyer; I cannot provide legal counsel.

**Comment by dalisoft** [comment]
Thanks for reply. I give you credit for demo
