### ISSUE TITLE
Decouple force layout (and all other layouts) from the display loop.

### ISSUE THREAD

**Issue by trusktr** [d3/d3#3017]
This outlines the problem: http://stackoverflow.com/questions/40210172

I would like to render the scene using a render loop created by a library separate from d3, and I don't want `force` to create it's own rAF loop. Ideally it should be easy to do, but it's hard to do (at least in d3 v3.x.x).

For an example of an API easy to use in any render loop, check out [Tween.js](https://github.com/tweenjs/tween.js). For example:

```js
import {Tween} from 'tween.js'

const tween = new Tween({value: 0})
  .to({value: 100}, 2000 /*2 sec*/)
  .start()

// tick the tween in our own animation loop:
requestAnimationFrame(function loop(time) {
  requestAnimationFrame(loop)
  tween.update(time)
})
```

or using the render loop of a separate library:

```js
import {Motor} from 'infamous'

// tick the tween in Motor's loop:
Motor.addRenderTask(time => tween.update(time))
```

With d3's force layout, it could look like this:

```js
import {Motor} from 'infamous'

const force = d3.layout.force()
  /* ... set parameters ... */
  .start(false) // perhaps `false` indicates not to tick automatically, i.e. no internal loop will be created.

// tick the layout in Motor's loop:
Motor.addRenderTask(time => force.tick()) // doesn't rely on time.
```

**Comment by trusktr** [comment]
Is this possible in d3 v4.x.x?

**Comment by syntagmatic** [comment]
Yes, just use the `tick` method https://github.com/d3/d3-force#simulation_tick

**Comment by trusktr** [comment]
@syntagmatic Could you give an example?

**Comment by mbostock** [comment]
Yes, use *simulation*.tick. Here is an example: https://bl.ocks.org/mbostock/01ab2e85e8727d6529d20391c0fd9a16
