### ISSUE TITLE
selection.insert(type, before) - V4 API ref example code doesn't supply the mandatory 2nd param

### ISSUE THREAD

**Issue by easleydp** [d3/d3#3018]
Compared to V3 the V4 API documentation for `selection.insert` seems to specify that the _before_ param is now mandatory. That's fine but the example code that follows (e.g. `d3.selectAll("p").insert("div");`) doesn't supply the _before_ param.

**Comment by protectecho** [comment]
thank you!

**Comment by mbostock** [comment]
It is not mandatory—it defaults to null, which means to insert the new element as the last child of its parent. (This is slightly different than selection.append, which inserts the new element before the next element in the update selection, preserving order.) I will update the README when I get a chance.
