### ISSUE TITLE
Export formatSpecifier.toString()

### ISSUE THREAD

**Issue by epelc** [d3/d3#3023]
[`d3.formatSpecifier.toString()`](https://github.com/d3/d3-format/blob/master/src/formatSpecifier.js#L44) should be exported so we can convert objects(not created by `d3.formatSpecifier()` but using the same format) back into format strings.

This would help with generating custom graphs based on config. You could control each property of a format instead of having to build a string or manually copy the `toString` method.

**Comment by mbostock** [comment]
You should have filed this bug in d3-format, but no matter. I have fixed this by fixing `instanceof d3.formatSpecifier`, which means you can now use `d3.formatSpecifier.prototype.toString` (and augment the prototype, if desired). I will push a release later this week most likely.

**Comment by epelc** [comment]
@mbostock Sorry, I forgot d3 was broken up. Thanks for the quick fix!
