### ISSUE TITLE
d3-3.x api-reference links to d3 v4 example

### ISSUE THREAD

**Issue by M4urice** [d3/d3#3025]
The Image on https://github.com/d3/d3-3.x-api-reference/blob/master/Force-Layout.md links to http://bl.ocks.org/mbostock/4062045 which uses d3 v4. 

PS: Issue concerns the v3 api docs so I opened the issue here (I am aware of https://github.com/d3/d3/issues/2994#issuecomment-255180780)

**Comment by mbostock** [comment]
The examples are not versioned, so this will necessarily be the case as I update the examples to v4. You can find the old v3 examples if you dig through the history on gist.github.com, but I will not be explicitly fixing the links in the v3 archive to point to old versions.
