### ISSUE TITLE
Update stacked to grouped bar example and stack documentation for v4

### ISSUE THREAD

**Issue by pierrelang** [d3/d3#3034]
The Stacked-to-Grouped Bars example at [http://bl.ocks.org/mbostock/3943967](http://bl.ocks.org/mbostock/3943967 ) should be updated for d3 v4.

Also, a simple way to convert from the earlier (v3) stack format to the new one should be given somewhere in the documentation.

As I (kinda) needed it, it updated the example to d3 v4 for my needs. 
A fiddle for it is here: [https://jsfiddle.net/9y2g65qc/20/](https://jsfiddle.net/9y2g65qc/20/)

Also, the transpose trick (see the fiddle) or something better if it exist should be mentioned in the doc, as it is not obvious how one can fo it

**Comment by mbostock** [comment]
Here’s my take on it:

https://bl.ocks.org/mbostock/3943967/c3a3295f7741bc5a38994a14a73ec329b5c9462c

**Comment by pierrelang** [comment]
Cool! Thanks!
