### ISSUE TITLE
Submit v4 to JSDelivr

### ISSUE THREAD

**Issue by bradvogel** [d3/d3#3037]
Would you mind submitting v4 to JSDeliver? The latest version it has is 3.5.17 here: https://www.jsdelivr.com/projects/d3js

We use JSDelivr instead of the d3 CDN so we can download all libraries in one bundled file, for performance.

Thanks!

**Comment by mbostock** [comment]
I don’t maintain the JSDelivr metadata, but it looks like you could submit a pull request over there so that JSDelivr automatically grabs the latest v4 release as it is published to npm.

https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md
