### ISSUE TITLE
Google, security, and deprecation

### ISSUE THREAD

**Issue by jimlynnjulian** [d3/d3#3058]
The following is the error message from an 'inspect' in Chrome of the Solar Path example of D3.
The url was 'http://bl.ocks.org/mbostock/7784f4b2c7838b893e9b'. 
When I changed to a secure url, i.e., 'https://', the example worked.

"getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."

I was accessing the example from my laptop while connected to the web.
Jim Julian

**Comment by mbostock** [comment]
I’ve enabled auto-redirects to HTTPS on bl.ocks.org now.

**Comment by curran** [comment]
@mbostock Sweet! I think this will fix lots of broken things. I've noticed many HTTPS related errors, particularly on older bl.ocks.
