### ISSUE TITLE
Validate input of some functions

### ISSUE THREAD

**Issue by OndraZizka** [d3/d3#3059]
Some functions do not check the input for correctness. Instead, they take the parameters happily and then the execution fails somewhere deep into execution.

One instance is `d3.zoom().scaleExtent([0.2, 3]);`
If you give it `d3.zoom().scaleExtent(0.2, 3);`, it won't complain. But then, the `d3.event.transform` will contain all `NaN`'s.

I assume this is not being handled for performance and code size reasons? But in cases of methods which are typically only called once I think it is justifiable.

**Comment by mbostock** [comment]
I appreciate the suggestion, but it’s nothing something I’m currently willing to do. If you want stricter code validation, I suggest looking at D3’s TypeScript bindings.
