### ISSUE TITLE
Examples link is broken.

### ISSUE THREAD

**Issue by souravbadami** [d3/d3#3068]
The examples link on **README.md** is broken. Here's the link: http://bl.ocks.org/mbostock.

**Comment by curran** [comment]
Isn't that already where the link points to? This is the source for the README links section:

```markdown

## Resources

* [API Reference](https://github.com/d3/d3/blob/master/API.md)
* [Release Notes](https://github.com/d3/d3/releases)
* [Gallery](https://github.com/d3/d3/wiki/Gallery)
* [Examples](http://bl.ocks.org/mbostock)
* [Wiki](https://github.com/d3/d3/wiki)
```

**Comment by mbostock** [comment]
I’m unable to reproduce this issue. The link works for me.

**Comment by souravbadami** [comment]
Ah, It gave me a timeout yesterday. But it's fine now.
