### ISSUE TITLE
d3.dsvParse() wrong parsing with dsv string

### ISSUE THREAD

**Issue by manas271196** [d3/d3#3087]
When I use d3.dsvParse with a dsv string, it returns an empty array while the "columns" key is simply the last row of my file.

For example:
var bleh="p,S,SF,F,FM,M\nB,59,10,25,0,218\nI,0,0,2,0,3\nB,1,0,2,0,11\nS,7,0,1,0,22\nO,6,0,0,0,12";
var x=d3.csvParse(bleh);

x would be an empty array with the "column" key being  ["O", "6", "0", "0", "0", "12"].

**Comment by mbostock** [comment]
Works fine for me:

https://runkit.com/mbostock/58d7cc8a8176de001409354f

I am not able to reproduce.
