### ISSUE TITLE
classed的对象写法是有问题的

### ISSUE THREAD

**Issue by holidaying** [d3/d3#3093]
![Paste_Image.png](http://upload-images.jianshu.io/upload_images/2604175-bd7171f9c4bb0f2c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
这种对象写法是有问题的

![Paste_Image.png](http://upload-images.jianshu.io/upload_images/2604175-0f63b24c07e1aa2c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

这种写法也是错误的 一般是用于disabled、checked

**Comment by tianxuzhang** [comment]
@holidaying
D3 V3 support object as parameter。You can try the following demos:
* [selection.classed](https://github.com/tianxuzhang/d3-api-demo/blob/master/core/selection/
* selection.classed.html
[selection.property](https://github.com/tianxuzhang/d3-api-demo/blob/master/core/selection/selection.property.html)

This feature is no longer supported in D3 V4 by default. You must use [d3-selection-multi](https://github.com/d3/d3-selection-multi) if you want multi-value map methods. And here is a new translation about D3 V4 [d3.v4-API-Translation](https://github.com/tianxuzhang/d3.v4-API-Translation).

@hijiangtao 
Thanks a lot! I'll update the old document right away.

**Comment by hijiangtao** [comment]
@tianxuzhang Thanks for your work.
On the other hand, I think there's no need to change v3.x API if d3 was designed to support that specific grammar in the corresponding version.

**Comment by holidaying** [comment]
thanks a lot
