### ISSUE TITLE
why is d3.select() of d3 is different from select() of d3-selection???

### ISSUE THREAD

**Issue by runningbar** [d3/d3#3094]
I have used D3 latest version in react to do visualization， and found something weird.

**`d3.select()` of d3 lib is different from `select()` of d3-selection lib.**

can anyone explain this, and what is equivalent of `d3.select`

code as follow:

```js
import React from "react"
import { select } from "d3-selection"
import * as d3 from "d3"

export default class Test extends React.Component {
    componentDidMount() {
        this.renderBar();
    }
    componentDidUpdate() {
        this.renderBar();
    }

    renderBar() {
        let node = this.refs.bar;
        let r1 = select(node);
        let r2 = d3.select(node);
        console.log("result1", r1);
        console.log("result2", r2); 
        // I find r1 is different from r2.
        // such as r1 does not have transition() function but r2 has it!
    }

    render() {
        return (
            <rect ref="bar" ></rect>
        );
    }
}
```

![image](https://cloud.githubusercontent.com/assets/22721557/25040331/43405424-213b-11e7-8cdc-949bdf0d2ad2.png)

the two object have different function.

Then I have checked source code of `select()[d3-selection/build/d3-selection.js]` and `d3.select()[d3/build/d3.js]`, unfortunately, they are the same.

can anyone explain this, and what is equivalent of `d3.select`

or 

where am I going wrong?

thank you~

**Comment by johnwalley** [comment]
You might be seeing the same side-effect behaviour I came across in http://www.walley.org.uk/blog/2016/9/4/rollup-and-d3-plugins

**Comment by runningbar** [comment]
yeah, I find this problem just because of the error message:

![image](https://cloud.githubusercontent.com/assets/22721557/25040614/1a30fc12-213d-11e7-91b3-ab7ac005df09.png)

**Comment by runningbar** [comment]
thanks @johnwalley , I have solve it using your approach
