### ISSUE TITLE
Why PHP composer have been abandoned ?

### ISSUE THREAD

**Issue by dfranco** [d3/d3#3097]
Hello,
This is a simple question, not really an issue with d3.

Why did you stop using composer ?
I can find a Composer packager at packagist.org but it's not maintained anymore
https://packagist.org/packages/mbostock/d3

I'm not saying it's good or not, just want to know if you found another tool or choose another solution ;)

Thanks for your feedback

Regards

**Comment by mbostock** [comment]
Because I have finite time and it reduces complexity to support fewer distribution systems. I recommend npm or GitHub releases.
