### ISSUE TITLE
How to append the tspan in append text traversal??

### ISSUE THREAD

**Issue by cloudching** [d3/d3#3099]
var nodes_text = svg.selectAll(".nodetext")
            .data(data.nodes)
            .enter()
            .append("text")
            .attr("class", "nodetext")
            .attr("dx", -imageSize/2)
            .attr("dy", "1em")
            .text(function (d) {
                var text = d.name.split(",");
                d3.select(this)
                     .data(text)
                     .enter
                     .append('tspan')
                    .attr('dx',0)
                    .attr('dy',0)
                    .text(function(e){return e;});
                return "";
            });

how to fix this code?thx!

**Comment by Loksly** [comment]
Hi cloudching!

You should use question/answer platforms like https://stackoverflow.com/ for questions not related to suggestions or bugs. They work better and faster for this kind of question.

As you may see some have asked some relevant questions and may be some code that might fit your needs:
https://stackoverflow.com/search?q=tspan+d3


Have a nice day!

**Comment by cloudching** [comment]
thx
