### ISSUE TITLE
d3 chart give SyntaxError: Unexpected token '>' for safari Web Browser

### ISSUE THREAD

**Issue by rushil16** [d3/d3#3104]
Hi, I'm using windows os and D3 chart working well for google chrome, firefox but in safari I'm facing issue for syntax and the chart not going to drawn. Screenshot is attached please give me the solution.
![screenshot_8](https://cloud.githubusercontent.com/assets/24586572/26750778/dae579f2-4847-11e7-830c-7c7665cc6ad1.png)

**Comment by curran** [comment]
This seems to be not a bug in D3, but rather that your environment does not support ES6 arrow functions.
