### ISSUE TITLE
why does d3.event.preventDefault() fail in ...

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [d3/d3#3105]
in: Draggable Network II
https://bl.ocks.org/mbostock/raw/4566102/

(clicking on a node) => "(index):116 Uncaught TypeError: d3.event.preventDefault is not a function"
since typeof d3.event == 'Object'

From:
Capturing Mousemove
https://bl.ocks.org/mbostock/raw/4198499/

i learn, that typeof d3.event (should eventually be) == 'MouseEvent'

Since I found no 'd3-event', I hope here is the right place to report.

Please don't beat me, if I'am wrong,
I'am on the bootstrap of learning d3.js and still not an expert

Wolfgang

**Comment by mbostock** [comment]
That’s an old example, and it’s a bug. I’ve updated it to v4, which obviates the need to prevent default since the behaviors do that for you automatically; you may need to wait a few minutes for the bl.ocks cache to expire.

**Comment by wolfgangvonludwigsburg** [comment]
VERY Thank you for the immediate update to v4 !!

Your d3.js is a really superprofessional outstanding lib,
despite I'm sometimes despairing about the right way
to functionally select/access my data (=> __data__ ?!) ... ;-)
