### ISSUE TITLE
d3.format(".1s") rounds differently in Firefox / Chrome

### ISSUE THREAD

**Issue by jasonhealy** [d3/d3#3107]
d3.format using (".1s") is rounding values inconsistently between Firefox / Chrome

See example. Run in both browsers...
https://jsbin.com/puvejebaza/edit?html,js,console,output

Expectation is that the same value is returned

**Comment by mbostock** [comment]
Per the [ISSUE TEMPLATE](https://github.com/d3/d3/blob/master/ISSUE_TEMPLATE.md), if this were a bug in d3-format, you should file it over at [d3-format](https://github.com/d3/d3-format). 

However, this does *not* appear to be a bug in d3-format, but a bug in Firefox. The expected value of the following expression is "3e+3":

```js
(2500).toExponential(0)
```

In Firefox this currently evaluates to "2e+3". D3 is not a compatibility layer, and so in general does not attempt to workaround bugs in the browser’s JavaScript runtime.
