### ISSUE TITLE
any event cannot be fired per-time when fill is none with path

### ISSUE THREAD

**Issue by norangit** [d3/d3#3108]
demo is here: https://jsfiddle.net/noran/xyeghntp/5/

arc is not clickable when fill attribute is none;  why? fill means  to color shape
refer to https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes

**Comment by Fil** [comment]
This is an SVG question, not related to D3.

In SVG, transparent elements don't receive pointer events, except if you add a specific style:
` .style('pointer-events', 'all')`

A (lazier) solution is to use an "almost transparent" color such as `rgba(255,255,255,0.01)`.

**Comment by norangit** [comment]
Thanks a lot!!!
