### ISSUE TITLE
d3.select(<css selector>) does not work if id does not start with a letter

### ISSUE THREAD

**Issue by mightymercado** [d3/d3#3112]
I am using d3 3.5.17 in Plotly.

In HTML4, "ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".")."

However, in HTML5, the rule is only to have at least one character without spaces.

d3.select("#1test") would raise an error saying that the parameter is not a valid css selector.

**Comment by ssbunny** [comment]
D3 internally just call the `document.querySelector(selector)` method.
<img width="800" alt="qq20170706-133325 2x" src="https://user-images.githubusercontent.com/2247291/27898353-30213e22-6258-11e7-920b-0a059163be13.png">

**Comment by mightymercado** [comment]
Okay.

**Comment by jfsiii** [comment]
@mightymercado See the discussion in [this Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=620933) 

You could use `'[id="1test"]'` or, if your browser supports [`CSS.escape`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape), `'#' + CSS.escape('1test')`. There's also a [polyfill for `CSS.escape`](https://github.com/mathiasbynens/CSS.escape)
