### ISSUE TITLE
In D3 v4, d3.scale.linear() became dc.scaleLinear()

### ISSUE THREAD

**Issue by gutweniger** [d3/d3#3113]
Please update your tutorials (e.g. the one on bar charts) to the new syntax, otgerwise it's really confusing for beginners like me.

See also:
https://stackoverflow.com/questions/38450349/uncaught-typeerror-cannot-read-property-linear-of-undefined

Thanks a lot for the great work!

Andreas

**Comment by Loksly** [comment]
It is well documented:
https://github.com/d3/d3/blob/master/CHANGES.md#scales-d3-scale

« _For example, d3.scale.linear is now d3.scaleLinear_ »

Note d3 v4 is NOT retrocompatible with d3 v3.

The method you are talking about is:
https://github.com/d3/d3-scale



The problem was that the user should use this:
`<script src="https://d3js.org/d3.v3.min.js"></script>`

instead of:
`<script src="https://d3js.org/d3.v4.min.js"></script>`


The old d3 v3 api is here:
 https://github.com/d3/d3-3.x-api-reference/blob/master/API-Reference.md

**Comment by gutweniger** [comment]
You are absolutely right.

But usually, a novice usually starts with an introductory tutorial like 
https://bost.ocks.org/mike/bar/ (this is actually number 3 on the list of tutorials) before diving into the "well documented" details about different versions and APIs.

And nowhere in that turotial, I can see a hint that it only covers v3, so one might assume that it will work with v4.

Hence, I still think, it could be a good idea to add some remark to the tutorial about the naming change - it's not a big deal, is it?

**Comment by curran** [comment]
There are hundreds of tutorials that need updating. It's easy to want them all to be updated, but please realize that it would take a massive amount of effort to actually go through and update them all.

For example, you suggest that https://bost.ocks.org/mike/bar/ be updated, but this would also involve updating all the code and text for the whole series, and linked bl.ocks:

 * https://bost.ocks.org/mike/bar/
 * https://bl.ocks.org/mbostock/7322386
 * https://bost.ocks.org/mike/bar/2/
 * https://bl.ocks.org/mbostock/7341714
 * https://bost.ocks.org/mike/bar/3/
 * https://bl.ocks.org/mbostock/7341714

I'm not saying it's not worth doing, but just noting that it would be a lot of effort, probably several hours of work to do a proper job of it.

Also, in the tutorial the version of D3 used in the code examples is `d3.v3.min.js`.

**Comment by mbostock** [comment]
I try to update my tutorials when I have time. It’s a huge amount of work and has to be balanced against other tasks.

**Comment by gutweniger** [comment]
Thanks.
Updating everything is probably  a lot of work. But adding a small note in the beginning that the tutorials refer to v3 and that the syntax has changed in v4 would already be of great value to newbies like me.

Andreas


Von: Mike Bostock [mailto:notifications@github.com]
Gesendet: Freitag, 7. Juli 2017 17:51
An: d3/d3 <d3@noreply.github.com>
Cc: gutweniger <andreas.gutweniger@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [d3/d3] In D3 v4, d3.scale.linear() became dc.scaleLinear() (#3113)


I try to update my tutorials when I have time. It’s a huge amount of work and has to be balanced against other tasks.
