### ISSUE TITLE
Cannot read property 'linear' of undefined

### ISSUE THREAD

**Issue by tkggusraqk** [d3/d3#3123]
error:
   d3.scale.linear() ,Cannot read property 'linear' of undefined
https://d3js.org/d3.v4.min.js
right:
https://d3js.org/d3.v3.min.js

**Comment by Ledragon** [comment]
The API was changed between v3 and v4. you should now use `d3.scaleLinear()`. Check the [release notes](https://github.com/d3/d3/blob/master/CHANGES.md) to get details.

**Comment by ram-nallari** [comment]
error:
Error in [Cannot read property 'scale' of undefined].

**Comment by curran** [comment]
@ram-nallari Try `d3.scaleLinear`, or `d3.scaleOrdinal`, and check which version - `d3.scale` is there in v3 but gone in v4.
