### ISSUE TITLE
bl.ocks does not syntax highlight the 'const' keyword

### ISSUE THREAD

**Issue by alexjlockwood** [d3/d3#3127]
Apologies if this isn't the correct place to report the issue, but I noticed on bl.ocks that 'const' wasn't being recognized as a keyword (example: https://bl.ocks.org/alexjlockwood/f7c0b61574d4a0a66128805327b0ec51). Just wanted to let you know in case maybe the syntax highlighter dep hasn't been updated in a while.

**Comment by mbostock** [comment]
Yep, thanks. Moved to mbostock/bl.ocks.org#10.
