### ISSUE TITLE
Include d3-sparql inside the d3 organization

### ISSUE THREAD

**Issue by l00mi** [d3/d3#3128]
We would be happy to develop the [d3-sparql](https://github.com/zazuko/d3-sparql) plugin further inside the d3 organisation and allow others to participate.

**Comment by l00mi** [comment]
Yes, no, probably, wrong place to ask?

**Comment by mbostock** [comment]
The repositories in the d3 organization are ones I have personally committed to maintaining, so I think it would make more sense if you keep the d3-sparql repository under your own organization or account for now.

If you want to attract others to contribute to (and use) d3-sparql, I would recommend listing it on the [D3 Wiki](https://github.com/d3/d3/wiki/Plugins) and announcing it on the [d3-js Google group](https://groups.google.com/d/forum/d3-js) and [D3 Slack](https://d3js.slack.com/). Thank you!

**Comment by l00mi** [comment]
Okay, did already list in the wiki.

Then I hoped more that as described here https://bost.ocks.org/mike/d3-plugin/ that this helps with onboarding and organizing new developers.

Thank you!

**Comment by mbostock** [comment]
That was my original plan, but I think it works out better when it’s more obvious who the primary maintainers are. I’ve updated my plugin article accordingly! Thanks again.

**Comment by l00mi** [comment]
Fair enough, so lets see that with time we can eventually convince you to become a maintainer (-,
