### ISSUE TITLE
Dead link to API reference

### ISSUE THREAD

**Issue by palrogg** [d3/d3#3133]
Hello,
The link to the API reference in the Wiki sidebar ([https://github.com/d3/d3/wiki](https://github.com/d3/d3/wiki)) points to “This page has moved!”.
Maybe it could be replaced by a direct link to the D3 v4 reference: https://github.com/d3/d3/blob/master/API.md
There's a lot of other dead links, tell me if it's useful to mention them.
Best,
Paul

**Comment by mbostock** [comment]
For reasons I cannot fathom, the custom _Sidebar.md was deleted by a user on Friday, September 23, 2016. I have restored the sidebar.

**Comment by palrogg** [comment]
Thanks a lot!
