### ISSUE TITLE
Browser header removed from d3 package.json

### ISSUE THREAD

**Issue by izaera** [d3/d3#3141]
Hi there:

It looks like since commit https://github.com/d3/d3/commit/39154c570116ca4c6972a7fa2d29e0b82b187728#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 the `browser` header of the `package.json` file has been replaced by `unpkg` and `jsdelivr`, which look like some CDN-related headers.

Why is that? Was it an error or on purpose? I was relying on the `browser` header to load the correct flavor of d3 in the browser. 

Can we have that header back or is it problematic for some reason?

Thanks for your help in advance 🙂

**Comment by mbostock** [comment]
Please see d3/d3-request#24.
