### ISSUE TITLE
d3.zoom() is not support ios7.1

### ISSUE THREAD

**Issue by lincal4wlf** [d3/d3#3156]
v4.11.0 report gesture error in ios7.1

I changed to v3.5.17 to solve this error

**Comment by mbostock** [comment]
I don’t have access to a iOS 7 simulator, and without more specific information such as the code that was being executed and the exact stack trace and error message, I’m not going to be able to investigate this issue. If you would be willing to use your developer tools on iOS 7 and provide more detail as to what is causing the error, that would be greatly appreciated and I would be happy to take a look provided more context. Thank you!
