### ISSUE TITLE
D3 inbuilt filter feature

### ISSUE THREAD

**Issue by HarikrishnaVemula** [d3/d3#3169]
Hi Team,

We are implementing D3 charts in our applications. So we had some queries all about that, are there any inbuilt features such as filters, sorting and line click (if the chart is line) ? Or shall we write custom code on each attribute based on our requirement? If there are any inbuilt features, can you provide sample examples for them so that we will look into them .

Thanks,
Harikrishna

**Comment by mbostock** [comment]
D3 is not a charting library, but you can implement all of these features in your visualizations as desired, and you can find examples of these features in the gallery.

**Comment by curran** [comment]
@HarikrishnaVemula I think I understand what you are after.

May I suggest the following resources:

 * JavaScript's inbuilt functions [array.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) and [array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)
 * Cool library by @jheer called [Datalib](https://github.com/vega/datalib) that has nice aggregation capabilities.
 * [D3 Nest Tutorial and examples](http://bl.ocks.org/phoebebright/raw/3176159/) is useful to get a feel for what `d3.nest` can do.
 * [Crossfilter](http://square.github.io/crossfilter/) Implements filtering as well as aggregation (which you could implement on your own with array.filter and Datalib's aggregation).

Best of luck!
