### ISSUE TITLE
Can't update wiki (plugin page)

### ISSUE THREAD

**Issue by ErikOnBike** [d3/d3#3252]
I can't seem to update the wiki, to add a new module to the plugin page. Some pointers please how to do this.
If there is a 'special' procedure, maybe this can be described on the wiki itself.

Kind regards,
Erik

**Comment by mbostock** [comment]
Sorry, I had to lock the wiki due to aggressive spammers.

**Comment by ErikOnBike** [comment]
Mike,

I understand. Could you add the following to the plugins page or explain what to do to get it added?

[ErikOnBike/d3-template](https://github.com/ErikOnBike/d3-template) - D3 plugin to support templates using D3's data binding mechanism

Thanks for all the great work on D3. My favourite JS-lib by far ;-).

Cheers,
Erik

**Comment by mbostock** [comment]
Done! Thank you.
