### ISSUE TITLE
Use exact paths in imports.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#3265]
Rather than relying on the implicit addition of “.js”.

- [x] [d3-array](https://github.com/d3/d3-array)
- [x] [d3-axis](https://github.com/d3/d3-axis)
- [x] [d3-brush](https://github.com/d3/d3-brush)
- [x] [d3-chord](https://github.com/d3/d3-chord)
- [x] [d3-color](https://github.com/d3/d3-color)
- [x] [d3-contour](https://github.com/d3/d3-contour)
- [x] [d3-delaunay](https://github.com/d3/d3-delaunay)
- [x] [d3-dispatch](https://github.com/d3/d3-dispatch)
- [x] [d3-drag](https://github.com/d3/d3-drag)
- [x] [d3-dsv](https://github.com/d3/d3-dsv)
- [x] [d3-ease](https://github.com/d3/d3-ease)
- [x] [d3-fetch](https://github.com/d3/d3-fetch)
- [x] [d3-force](https://github.com/d3/d3-force)
- [x] [d3-format](https://github.com/d3/d3-format)
- [x] [d3-geo](https://github.com/d3/d3-geo)
- [x] [d3-hexbin](https://github.com/d3/d3-hexbin)
- [x] [d3-hierarchy](https://github.com/d3/d3-hierarchy)
- [x] [d3-interpolate](https://github.com/d3/d3-interpolate)
- [x] [d3-path](https://github.com/d3/d3-path)
- [x] [d3-polygon](https://github.com/d3/d3-polygon)
- [x] [d3-quadtree](https://github.com/d3/d3-quadtree)
- [x] [d3-random](https://github.com/d3/d3-random)
- [x] [d3-scale](https://github.com/d3/d3-scale)
- [x] [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic)
- [x] [d3-selection](https://github.com/d3/d3-selection)
- [x] [d3-shape](https://github.com/d3/d3-shape)
- [x] [d3-tile](https://github.com/d3/d3-tile)
- [x] [d3-time](https://github.com/d3/d3-time)
- [x] [d3-time-format](https://github.com/d3/d3-time-format)
- [x] [d3-timer](https://github.com/d3/d3-timer)
- [x] [d3-transition](https://github.com/d3/d3-transition)
- [x] [d3-zoom](https://github.com/d3/d3-zoom)

**Comment by okanthony** [comment]
This sounds like a good first issue for me - any other info or guidance you could provide?

**Comment by mbostock** [comment]
Whew that was fun!

**Comment by scola84** [comment]
I'm trying to get `d3-format` to work in node >= 13 with ESM. For that to work, a `"type": "module"` should be added to `package.json` of `d3-format`. See the [Node.js ESM documentation](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_package_json_type_field).

(Paths with an extension are another prerequisite to make it work, therefore I'm adding this request here).
