### ISSUE TITLE
Provide API reference link for v4

### ISSUE THREAD

**Issue by ccprog** [d3/d3#3266]
Currently, the repo and wiki home pages link the API reference to [master/API.md](https://github.com/d3/d3/blob/master/API.md) and thus already refer to v5.0. Especially since there is no stable release yet for v5, the default should be a reference to the [v4 branch](https://github.com/d3/d3/blob/4/API.md).

As a minimum, the home page should clearly distinguish between the reference for the different versions and master/API.md should denote the version it refers to.

**Comment by mbostock** [comment]
If you are visiting the repo, you are already looking at the master branch so a reference to the master API.md is what you want. Back in v4 when the d3 module pinned its dependencies it would have made sense to pin the versions in the links from API.md to the README.md in the respective modules, but as v5 no longer pins exact versions (instead using semver), and as GitHub does not provide a way to link to a semver range for a README, I don’t see a reasonable way to link to versioned READMEs. (It is tedious enough as it is to manage all the D3 modules, so I’m not about to add more links that will inevitably go out-of-sync during development.)

The API documentation is stored within the git repo, and is kept up-to-date with commits, and thus it is easy to find the documentation that corresponds exactly with the software you are using. The only issue is the top-level table of contents for the `d3` default bundle. This is versioned within the repo as well, but I’m not going to make parallel commits in the wiki with every release.

I will update CHANGES.md to cover the changes in v5; for now these are available on the release notes page.

**Comment by ccprog** [comment]
Would it be reasonable to at least provide entry links to the deprecated modules, citing their status?

Otherwise, you should expect an upsurge in people wondering where the (links to the) documentation for these modules have gone, or even [not being aware of their existence](https://stackoverflow.com/questions/48869429/how-to-add-svg-as-an-imagexml-in-d3-version-4).

**Comment by mbostock** [comment]
Links to deprecated modules (and methods etc.) are in CHANGES.md, not API.md.
