### ISSUE TITLE
Possible bug in d3 v3 --> v4 changelog?

### ISSUE THREAD

**Issue by alexjlockwood** [d3/d3#3268]
In the section on d3-chord (link: https://github.com/d3/d3/blob/master/CHANGES.md#chords-d3-chord), it states:

> For consistency with [*arc*.padAngle](https://github.com/d3/d3-shape/blob/master/README.md#arc_padAngle), *chord*.padding has also been renamed to [*ribbon*.padAngle](https://github.com/d3/d3-chord/blob/master/README.md#ribbon_padAngle).

Do you mean that "chord.padding" has been renamed to "chord.padAngle" instead?

**Comment by mbostock** [comment]
No; d3.svg.chord was replaced with d3.ribbon, so *chord*.padding is replaced with *ribbon*.padAngle.
