### ISSUE TITLE
inclusion of Behrmann Equal Area Cylindrical projection

### ISSUE THREAD

**Issue by spyrostheodoridis** [d3/d3#3271]
Major scientific journals ask for data to be presented in Behrmann Equal Area Cylindrical projection. Unfortunately, I do not see such an option in d3-geo-projection. Do you think it's possible to include this projection as well? Alternatively, how could one define it in a custom way?

**Comment by mbostock** [comment]
Try d3.geoCylindricalEqualAreaProjection with a standard parallel of 30°.

https://beta.observablehq.com/@mbostock/cylindrical-equal-area-projections

**Comment by spyrostheodoridis** [comment]
Thanks a lot Mike! 
Amazing explanation in the link
