### ISSUE TITLE
d3-fetch

### ISSUE THREAD

**Issue by Ya-Za** [d3/d3#3280]
To use `d3-fetch`, after installing `npm install d3-fetch`, you have to use `import { ... } from 'd3-fetch';` and unfortunately, for example, `d3.csv` function doesn't work!
For solving this problem, I think, the line `export * from "d3-fetch";` should be added to the `node_modules/d3/index.js`.

Thank you :-)

![d3-fetch](https://user-images.githubusercontent.com/16613088/37620092-87ecac80-2bd0-11e8-871f-c8c8a86774e7.png)

**Comment by mbostock** [comment]
This is already the case in master, which has the 5.0.0 prerelease. The release will be available soon.
