### ISSUE TITLE
Wrong "sequential" link in 5.0.0 (RC4) release notes

### ISSUE THREAD

**Issue by magjac** [d3/d3#3282]
Extremely minor issue, but the https://github.com/d3/d3/releases/tag/v5.0.0 release notes link to https://github.com/d3/d3-scale-chromatic/blob/master/README.md#sequential which does not exist. https://github.com/d3/d3-scale-chromatic/blob/master/README.md#sequential-single-hue and https://github.com/d3/d3-scale-chromatic/blob/master/README.md#sequential-multi-hue do exist.

**Comment by mbostock** [comment]
Thanks. Fixed!
