### ISSUE TITLE
d3.json(url, (err,data) => { ... })  : when use d3.v5.min.js, -> bad, when use d3.v3.min.js is good

### ISSUE THREAD

**Issue by o-matsuo** [d3/d3#3292]
i watched backlog. but i did not watch target.

i use
--------------------------------
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>D3.js chart</title>
    <script src="http://d3js.org/d3.v5.min.js" charset="utf-8"></script>
  </head>
  <body>
    <svg id="chart"></svg>
    <script src="js/main.js"></script>
  </body>
</html>
----------------------------------------
main.js is
   ... d3.json('URL -> RESTAPI', (error,data) => {  something statement   });

main.js is not work.  d3.json method is not work. did not go into { something statement }

but i use 
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
and so main.js is good.

why, v3 version -> v5 version is different things.

i watched RESTAPI return JSON Data.
help me

**Comment by mbostock** [comment]
Please read CHANGES:

https://github.com/d3/d3/blob/master/CHANGES.md

**Comment by o-matsuo** [comment]
i understood! thank you very match.
