### ISSUE TITLE
6.0

### ISSUE THREAD

**Issue by mbostock** [d3/d3#3333]
d3-array
* Add [d3.group](https://github.com/d3/d3-array/blob/master/README.md#group).
* Add [d3.groups](https://github.com/d3/d3-array/blob/master/README.md#groups).
* Add [d3.rollup](https://github.com/d3/d3-array/blob/master/README.md#rollup).
* Add [d3.rollups](https://github.com/d3/d3-array/blob/master/README.md#rollups).
* Add [d3.bin](https://github.com/d3/d3-array/blob/master/README.md#bin).
* Add [d3.count](https://github.com/d3/d3-array/blob/master/README.md#count). Thanks, @Fil!
* Add [d3.least](https://github.com/d3/d3-array/blob/master/README.md#least).
* Add [d3.leastIndex](https://github.com/d3/d3-array/blob/master/README.md#leastIndex).
* Add [d3.maxIndex](https://github.com/d3/d3-array/blob/master/README.md#maxIndex).
* Add [d3.minIndex](https://github.com/d3/d3-array/blob/master/README.md#minIndex).
* Add [d3.quickselect](https://github.com/d3/d3-array/blob/master/README.md#quickselect).
* Rewrite [d3.median](https://github.com/d3/d3-array/blob/master/README.md#median) to use quickselect.
* Allow more than two iterables for [d3.cross](https://github.com/d3/d3-array/blob/master/README.md#cross).
* Deprecate d3.scan; use [d3.leastIndex](https://github.com/d3/d3-array/blob/master/README.md#leastIndex) instead.
* Deprecate d3.histogram; use [d3.bin](https://github.com/d3/d3-array/blob/master/README.md#bin) instead.

d3-collection [Removed!]
* Remove d3.keys; use [Object.keys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys).
* Remove d3.values; use [Object.values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values).
* Remove d3.entries; use [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries).
* Remove d3.map; use [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).
* Remove d3.set; use [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).
* Remove d3.nest; use [d3.group](https://github.com/d3/d3-array/blob/master/README.md#group), [d3.rollup](https://github.com/d3/d3-array/blob/master/README.md#rollup), *etc.*

d3-delaunay [Added!]
* Add [d3.Delaunay](https://github.com/d3/d3-delaunay/blob/master/README.md#Delaunay).

d3-force
* Add support for iterables.

d3-hierarchy
* Add *node*.find.
* Add *node*[Symbol.iterator].
* Add support for iterables.
* Pass *index* to *node*.each and other traversal methods.

d3-random
* Add [d3.randomInt](https://github.com/d3/d3-random/blob/master/README.md#randomInt).
* Add [d3.randomBinomial](https://github.com/d3/d3-random/blob/master/README.md#randomBinomial).
* Add [d3.randomGeometric](https://github.com/d3/d3-random/blob/master/README.md#randomGeometric).
* Add [d3.randomPareto](https://github.com/d3/d3-random/blob/master/README.md#randomPareto).
* Add [d3.randomBernoulli](https://github.com/d3/d3-random/blob/master/README.md#randomBernoulli).
* Don’t wrap Math.random in the default source.

d3-shape
* Add support for iterables.

d3-scale
* Add support for iterables.
* …

d3-selection
* Change [*selection*.on](https://github.com/d3/d3-selection/blob/master/README.md#selection_on) to pass the *event*.
* [Remove d3.event!](https://github.com/d3/d3-selection/issues/191)

d3-transition
* Change d3-selection to be a peer dependency.

d3-voronoi [Removed!]
* Remove d3.voronoi; use [d3.Delaunay](https://github.com/d3/d3-delaunay/blob/master/README.md#Delaunay).

Upgrade:
- [x] [d3-array](https://github.com/d3/d3-array/releases)
- [ ] [d3-axis](https://github.com/d3/d3-axis/releases)
- [ ] [d3-brush](https://github.com/d3/d3-brush/releases)
- [ ] [d3-chord](https://github.com/d3/d3-chord/releases)
- [ ] [d3-color](https://github.com/d3/d3-color/releases)
- [ ] [d3-contour](https://github.com/d3/d3-contour/releases)
- [ ] [d3-dispatch](https://github.com/d3/d3-dispatch/releases)
- [ ] [d3-drag](https://github.com/d3/d3-drag/releases)
- [ ] [d3-dsv](https://github.com/d3/d3-dsv/releases)
- [ ] [d3-ease](https://github.com/d3/d3-ease/releases)
- [ ] [d3-fetch](https://github.com/d3/d3-fetch/releases)
- [x] [d3-force](https://github.com/d3/d3-force/releases)
- [ ] [d3-format](https://github.com/d3/d3-format/releases)
- [ ] [d3-geo](https://github.com/d3/d3-geo/releases)
- [ ] [d3-hierarchy](https://github.com/d3/d3-hierarchy/releases)
- [ ] [d3-interpolate](https://github.com/d3/d3-interpolate/releases)
- [ ] [d3-path](https://github.com/d3/d3-path/releases)
- [ ] [d3-polygon](https://github.com/d3/d3-polygon/releases)
- [ ] [d3-quadtree](https://github.com/d3/d3-quadtree/releases)
- [ ] [d3-random](https://github.com/d3/d3-random/releases)
- [x] [d3-scale](https://github.com/d3/d3-scale/releases)
- [ ] [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic/releases)
- [ ] [d3-selection](https://github.com/d3/d3-selection/pull/210)
- [ ] [d3-shape](https://github.com/d3/d3-shape/releases)
- [ ] [d3-time](https://github.com/d3/d3-time/releases)
- [ ] [d3-time-format](https://github.com/d3/d3-time-format/releases)
- [ ] [d3-timer](https://github.com/d3/d3-timer/releases)
- [ ] [d3-transition](https://github.com/d3/d3-transition/pull/94)
- [ ] [d3-zoom](https://github.com/d3/d3-zoom/releases)

**Comment by mbostock** [comment]
I’m thinking maybe we don’t need to do a major version bump across all the modules just for the sake of announcing ES2015 syntax adoption. We could bump those modules as necessary when we make changes that benefit from ES2015 syntax, and then the d3 package could use a version range (*e.g.*, `1.1.0 - 2`).

**Comment by curran** [comment]
Really looking forward to 6.0!

**Comment by curran** [comment]
I'd be interested in trying out a pre-release of 6.0, similar to the [5.0 prerelease](https://github.com/d3/d3/releases/tag/v5.0.0-rc.1).

Might this be in the realm of possibility? Anyone else interested?

Also noticed that `d3-array quantileSorted` is done and can be checked off.

**Comment by gordonwoodhull** [comment]
We at dc.js are planning to switch to the individual D3 modules in order to test against 6.0 before it’s released. But I agree, a release candidate would give us more certainty that we’re testing the right thing.

For us, the d3-selection changes may have the biggest impact - iterators etc. I don’t think those changes have started yet.

**Comment by mbostock** [comment]
There’s a two branch in d3-selection and d3-transition, but the removal of d3.event hasn’t been implemented yet which is blocking the release of those modules.

**Comment by mbostock** [comment]
d3.event removal has been implemented, and 2.0.0-rc.1 releases for d3-selection and d3-transition if you want to try them out!

It looks like the major thing blocking this release is now just the adoption of iterables in d3-hierarchy and d3-shape. A major part of this release is the adoption of new ES language features including iterables, so d3-hierarchy and d3-shape should be upgraded before we release. The other relevant modules (d3-array, d3-selection and d3-scale) have already been upgraded.

**Comment by mbostock** [comment]
I’ve implemented iterables for d3-hierarchy and d3-shape, so major releases of those modules should be imminent.

The last remaining step is to upgrade d3-brush, d3-drag and d3-zoom to the d3-selection changes, and specifically the removal of d3.event, d3.customEvent *etc.*

**Comment by Fil** [comment]
d3-hexbin has PR https://github.com/d3/d3-hexbin/pull/19 that does:
- canvas support
- incremental binning (add and remove points)
- hexgrid rotation and translation
- finding the bin from coordinates without adding the point

**Comment by mbostock** [comment]
I think I want to give d3-hexbin a little more time to “bake” and we should consider deferring its addition to 6.1. I haven’t had a chance to review the proposed API changes yet. There is other blocking work for 6.0 that needs to be done first, as well, notably upgrading d3-brush, d3-drag and d3-zoom to d3-selection 2.0 (namely the removal of d3.event and related changes).

**Comment by iam-synapse** [comment]
How long before 6.0 becomes available?

**Comment by jipexu** [comment]
HI great work
this 6 version will have heavy breaking change ?
(little bit worry to change a lot of code ...)

**Comment by Fil** [comment]
https://github.com/d3/d3/releases/tag/v6.0.0
