### ISSUE TITLE
Dead links and images in CHANGES.md

### ISSUE THREAD

**Issue by severo** [d3/d3#3340]
In the v4 section of [CHANGES.md](https://github.com/d3/d3/blob/master/CHANGES.md), some links and images are broken (see for example "viridis", "inferno", etc.):

![Capture d’écran de 2019-08-12 12-30-28](https://user-images.githubusercontent.com/1676121/62859302-0188c880-bcfd-11e9-94f7-bca0fa1217d5.png)

The reason is the functions and images have been moved from d3-scale to d3-scale-chromatic in v5.

I had been preparing a PR (#3339), but I don't know which strategy would be better:

- don't do anything, under the principle that changelogs must not be edited
- change `d3-scale` to `d3-scale-chromatic` in broken links and images. But note it would not fix the three links to `d3.schemeCategory20`, `d3.schemeCategory20` and `d3.schemeCategory20c` that disappeared in v5
- change `d3-scale/blob/master` to `d3-scale/v1.0.0/master` in broken links and images (or in all v4 section links?). But it means a lot of changes, and it only pushes the problem one step beyond: in https://github.com/d3/d3-scale/blob/v1.0.0/README.md#schemeCategory20c, the image is missing too, because the image src refers to the d3-scale master branch.

**Comment by severo** [comment]
Two dead links for obsolete function names: `d3.radialLine` (now `d3.lineRadial`) and `d3.radialArea` (now `d3.areaRadial`)

**Comment by mbostock** [comment]
I think it’s probably best to just leave things as-is. If we link to the 4.x documentation, then we’re pointing people to older documentation, and I would rather encourage them towards the latest versions (especially with v6 on the way #3333, and new major versions of several D3 modules already released). That said, I fixed the broken images.
