### ISSUE TITLE
d3.json event handler doesn't work with current d3 version

### ISSUE THREAD

**Issue by frameworker2019** [d3/d3#3347]
According [https://gist.github.com/mbostock/3750941](https://gist.github.com/mbostock/3750941)
I've tried to use onload mimics and so on.
But I got d3.json(url).on is not a function.

**Comment by wufeihuang** [comment]
That demo uses v3. However lots of APIs have been changed since v4. With the current version of v5,  you should use `d3.json` in this way: `d3.json(url).then(data => {})`.

The document is here: https://github.com/d3/d3-fetch/blob/v1.1.2/README.md#json

**Comment by mbostock** [comment]
https://github.com/d3/d3/blob/master/CHANGES.md#changes-in-d3-50
