### ISSUE TITLE
Gallery Example has links to spyware

### ISSUE THREAD

**Issue by znicholasbrown** [d3/d3#3354]
Hi, I hope this is the right place to report this (since it's in the d3 repo wiki), if not my apologies.

The Hacker News Popularity example in the [wiki gallery](https://github.com/d3/d3/wiki/Gallery) has numerous (all that I've tried) links to spyware/adware sites.

**Comment by mbostock** [comment]
This one? http://hn.metamx.com/

I don’t see any spyware on that page…

**Comment by znicholasbrown** [comment]
Yup that's the one - clicking anywhere in the graph routes to various malicious sites.

**Comment by mbostock** [comment]
Wow. The problem is the searchyc[.]com domain appears to have expired and has been taken over my bad actors. /cc @vogievetsky

**Comment by mbostock** [comment]
Removed.
