### ISSUE TITLE
Issue with latest update.

### ISSUE THREAD

**Issue by srikarbobbiganipalli** [d3/d3#3356]
My application solely uses d3.js. After the last update done before 23 hours i.e 5.14.1  i guess. we had multiple deployments on our Application which took the latest, after this all the elements which use d3 went invisible. 
it was getting viewable only when you resize the page.
We had to switch back to the previous versions to get it stable. we have now moved to 5.12.0 to get it stable.

**Comment by mbostock** [comment]
This issue doesn’t provide any information on how to reproduce the problem, so I have no way of investigating. If you’d like to share some code that reproduces the problem you are seeing I would be happy to take a look.
