### ISSUE TITLE
4.0.0版本click事件在win系统和mac上的差别

### ISSUE THREAD

**Issue by fkitty** [d3/d3#3361]
4.0.0版本，append('path').on('click')  在win系统上需要点击两次才能执行，在mac上只要点击一次就能执行

**Comment by Fil** [comment]
“in version 4.0.0 append('path').on('click') requires two clicks to execute on win system, one click to execute on mac”

Please upgrade to d3v5, and report this bug, if it is still present, at https://github.com/d3/d3-selection
