### ISSUE TITLE
How can I update my own outdated link on the gallery page and add some new examples.

### ISSUE THREAD

**Issue by xuchen81** [d3/d3#3365]
How can I update my own outdated link on the gallery page and add some new examples.

Thanks

**Comment by mitchdenny** [comment]
I'm not a maintainer of this project but I stopped by to see how active development was because I really liked d3 when I played with it a few years ago. Anyway, by the looks of it the web-site is also in GitHub in this repository:

```https://github.com/d3/d3.github.com```

**Comment by mbostock** [comment]
I am maintaining a new gallery on Observable:

https://observablehq.com/@d3/gallery

I will probably retire the old gallery on this wiki because there are too many broken and malicious links, and it is not feasible for me to maintain those links in perpetuity.

**Comment by mbostock** [comment]
Please send me any requests by filing an issue. Thank you!
