### ISSUE TITLE
Issue Queue Spamming

### ISSUE THREAD

**Issue by charlieartist** [d3/d3#3392]
@Fil Is there a way for anyone to flag issue queue spam? I tried to (and accidentally clicked on one of the spam links), but found the process to be cumbersome, where a policy violation needed to be submitted to GitHub moderators. Is flagging only available to repository maintainers?

**Comment by rousan** [comment]
Couldn't we create a bot to watch new issues and indentify the spams and delete them.

**Comment by linusaurus** [comment]
I'm getting hammered ever few minutes. Any way to stop this

**Comment by trigus00** [comment]
Same 😞😓

Gustavo Mendoza

**Comment by mbostock** [comment]
Please contact GitHub support regarding spamming.
