### ISSUE TITLE
Wiki edit: add to plugin list

### ISSUE THREAD

**Issue by carpiediem** [d3/d3#3422]
I've tried to figure out how to submit a GitHub [pull request for the wiki repository](git remote add origin git@github.com:carpiediem/d3-wiki.git), but I [can't seem to make it work](https://github.com/carpiediem/d3-wiki/commit/e0c83a96d79c62e87a616b98f3fa682bd6f2d30c). I'd just like to add an item to the list of plugins.

```
* [carpiediem/d3-curve-circlecorners](https://github.com/carpiediem/d3-curve-circlecorners) - a curve function that uses circular corners instead of Bézier curves
```

**Comment by sarkisben** [comment]
I can take this issue.

**Comment by sarkisben** [comment]
I replicated carpiediem's issue. When attempting to push his changes, I got a 403 error.  Someone with wiki edit permissions will have to update Plugins.md for him.  Also, the guide on adding plugins needs to be updated with more detail about this permissions issue.

**Comment by mbostock** [comment]
Added. The wiki is locked due to persistent spam abuse.
