### ISSUE TITLE
new module "in v5 use" (API changes)

### ISSUE THREAD

**Issue by sergeykish** [d3/d3#3423]
As new to d3
I do not know about v3, v4, v5 API changes
And there are a lot of really god v3 and v4 examples

It's undefined, I search, for example https://stackoverflow.com/questions/10592753/how-to-define-setter-getter-on-prototype https://stackoverflow.com/questions/40198378/interpolate-is-not-a-function

There is https://github.com/d3/d3/blob/master/CHANGES.md and it is too big yet

It would be great if library helped me by itself:

    d3.scale.linear()
    Error: d3 v5: use .scaleLinear
    d3.line().interpolate('basis')
    Error: d3 v5: use .curve(d3.curveBasis)

And it is not that hard

    d3.scale = {
      get linear() {
        throw 'd3 v5: use .scaleLinear'
      }
    }
    d3.line().__proto__.interpolate = (name) => {
       let renamed = {
         'basis': 'd3.curveBasis'
       };
       throw `d3 v5: use .curve(${renamed[name]})`
    }
    d3.line().interpolate('basis')

From my understanding (complete novice) it should be in separate module. So it is easy to bundle in dev version and it does not pollute production.

What do you think?

**Comment by mbostock** [comment]
I’m focused on D3 v6 now and not planning on introducing new changes to help the v3 ↦ v4 migration. v4 was released four years ago. We’ve also been creating and updating lots of examples over on Observable: https://observablehq.com/@d3

**Comment by sergeykish** [comment]
@mbostock you're doing great job, the libraryis marvel and Observable demos superb. It's just that there are a lot of examples outside Observable ([bl.ocks.org](https://bl.ocks.org)).

I've discovered d3 just a month ago and that's my experience. Please, take a look [d3.scale is undefined](https://www.google.com/search?q=d3.scale%20is%20undefined), (d3.line is not a function)[https://www.google.com/search?q=d3.line+is+not+a+function]. That was my path too.

I've thought maybe I can help other people.
