### ISSUE TITLE
Wiki edit: add tutorial link to https://github.com/sgratzl/d3tutorial

### ISSUE THREAD

**Issue by sgratzl** [d3/d3#3431]
Hi, 

I wrote a D3 v5 tutorial at https://github.com/sgratzl/d3tutorial that is actively maintained and would love to add it to the tutorial section of the wiki. 

The tutorial starts with an introduction into the basic concepts and interactively develops a simple bar chart using Codepen. The second part of the tutorial explains advanced concepts such as layouts and results in a simple multiple coordinated view setup with four views that support brushing and linking.

**Comment by PascalUlor** [comment]
can I work on this?

**Comment by mbostock** [comment]
Added to the wiki… but we still need to overhaul and reorganize the wiki.
