### ISSUE TITLE
Installing d3 via "ng add"

### ISSUE THREAD

**Issue by Serjohn27** [d3/d3#3436]
Hi , 

I was trying to experiment with angular 10 , they have following command to add dependencies. but i get message below from cli. Is this something d3js needs to suport ? 

ng add d3
Installing packages for tooling via npm.
Installed packages for tooling via npm.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author 
to add ng-add support.

**Comment by mbostock** [comment]
I’m not familiar with ng, sorry.
