### ISSUE TITLE
Wrong mouse event targets with d3.js v6

### ISSUE THREAD

**Issue by herrvigg** [d3/d3#3441]
hello,
i couldn't find any specific d3 module for events or mouse so i put it here, supposing this belongs to core functionalities.
The changes with d3 events in v6 are creating some problems, i noticed this change of behavior which i think is an issue.

I have a table with images contained in the cells `<td><img>` and a callback on `mouseover`.

### d3 v5.16
```
    tbody.selectAll("td:nth-child(2)")
        .on("mouseover", function () {  console.log(this, d3.event); // my handler follows...
         });
```

I get an event fired on the `td` item consistently. If the mouse goes over the image, i still get a target `td` with `fromElement = img`.

### d3 v6
Now if i rewrite with the new API:
```
    tbody.selectAll("td:nth-child(2)")
        .on("mouseover", (event, d) => { console.log('mouseover', event.target); })
```
I would now get events fired both on `td` and `img` which does not seem logic. I only declared an event handler on `td`, why do i get events on `img`? I expect it to be as before, only fire on `td`. If the mouse is over the image the event should have `fromElement = img`.

**Comment by herrvigg** [comment]
Oh i just realized this belongs rather to d3-select... Sorry about that! I create a new ticket.

**Comment by Fil** [comment]
yes :) https://github.com/d3/d3-selection/issues/258
