### ISSUE TITLE
Android WebView throttles .on("zoom",...) as of latest update producing lag when dragging

### ISSUE THREAD

**Issue by javieranton-zz** [d3/d3#3444]
https://bl.ocks.org/willzjc/a11626a31c65ba5d319fcf8b8870f281

The link above will lag when dragging if you use Android Webview/Chrome and have the latest update (25th of August)

I raised a bug with Chromium

https://bugs.chromium.org/p/chromium/issues/detail?id=1125525#c13

They say we need to "make your touchMove handlers on the chart div passive: false and calling preventDefault()"

The example given here works in all browsers but has stopped working on Chromium. They are trying to push devs to do something because they think it's better but not sure how this affects d3. Is there some workaround we can use in absence of a built-in d3 solution?

**Comment by Fil** [comment]
Maybe similar to https://github.com/d3/d3-brush/issues/76 ?

**Comment by javieranton-zz** [comment]
To fix this,

In https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js

this.addEventListener(type, this[name] = l, l.$ = capture);

needs to be changed to 

if (type === "touchmove") {
          this.addEventListener(type, this[name] = l, {capture: l.$ = capture,passive: false});
      } else {
          this.addEventListener(type, this[name] = l, l.$ = capture);
      }
