### ISSUE TITLE
d3 .on no pass correctly value

### ISSUE THREAD

**Issue by Juan-Baquero** [d3/d3#3446]
I found this  in version 6.1.1.0 when I create a figure with **.on('click',d=>console.log(d))** pass the value of MouseEvent  , and I think it must pass the current value of the data (d) 

_in ts/angular_
   this.svg.selectAll(".circle")
      .data(this.historia)
      .enter().append("circle")      
      .attr("class", (d,i) => ("circulo" + this.data.nombre+i))
      .attr("cx", (d, i) => this.margin.left + xScale(i + 1))
      .attr("cy", d => yScale(d))
      .attr("r", 4)
        .style('fill', (d) => {
        if (d > 0) return '#FF3C5F'
        if (d < 0) return '#2ED47A'
      })
      .on("click", (d,i) => { this.showPopOver(d,i) })  

I return to the version 5.16.0... and works as expected.. I hope this could be helpful, thank you

**Comment by mbostock** [comment]
https://github.com/d3/d3/blob/master/CHANGES.md
