### ISSUE TITLE
Make typescript Type definitions as part of d3

### ISSUE THREAD

**Issue by goyaltushar92** [d3/d3#3447]
d3 is wonderful library but if someone want to use it typescript it needs type definitions (for better developer experience). Currently there is a type definition available with package name `@types/d3` but it is out of date. It will be good if we can have definitions as part of each package instead as separate package.

**Comment by Fil** [comment]
This project defers to DefinitelyTyped. There is currently a lot of work pending to upgrade `@types/d3` to d3@6 versions:
https://github.com/DefinitelyTyped/DefinitelyTyped/search?q=d3&type=issues

**Comment by goyaltushar92** [comment]
yes, I knew and my request wasn't for updating that repo, but I want d3 to have its type definitions to be part of d3 packages itself. like few other libraries does (e.g. https://github.com/moment/moment)

**Comment by curran** [comment]
I think the consensus is that the types are best off living inside DefinitelyTyped, rather than in d3 packages.

**Comment by goyaltushar92** [comment]
> I think the consensus is that the types are best off living inside DefinitelyTyped, rather than in d3 packages.

OK, then how can we speed up the process of type extraction?

**Comment by gordonwoodhull** [comment]
Contribute to DefinitelyTyped. One of my collaborators has done this for D3, and they have a smooth fast review system which went well.

**Comment by goyaltushar92** [comment]
wouldn't it be good if d3 have jsdoc comments, then I think we can use some tool to extract type definition? or d3 is using some other way to generate docs?

**Comment by gordonwoodhull** [comment]
No, that’s not really how jsdoc works. As far as I know, there is no good way to extract type information automatically, sorry.

**Comment by goyaltushar92** [comment]
Actually i was going through [this](https://dev.to/open-wc/generating-typescript-definition-files-from-javascript-5bp2) article, according to it, with newer version of typescript compiler it is possible to compile a .js file with jsDoc annotations and generate type definitions.
I checked it with `max` function of `d3-array` and it worked.

max.js with jsDoc annotations
```
/**
 * @function
 * @template T
 * @param {Iterable<T>} values 
 * @param {(value:T, index: number, values:Iterable<T>) => any } [valueof] 
 * @returns {T}
 */
export default function max(values, valueof) {
  let max;
  if (valueof === undefined) {
    for (const value of values) {
      if (value != null
          && (max < value || (max === undefined && value >= value))) {
        max = value;
      }
    }
  } else {
    let index = -1;
    for (let value of values) {
      if ((value = valueof(value, ++index, values)) != null
          && (max < value || (max === undefined && value >= value))) {
        max = value;
      }
    }
  }
  return max;
}
```
command I run
```
tsc max.js --allowJS --declaration --outDir ./out
```
Generated max.d.ts
```
/**
 * @function
 * @template T
 * @param {Iterable<T>} values
 * @param {(value:T, index: number, values:Iterable<T>) => any } [valueof]
 * @returns {T}
 */
export default function max<T>(values: any, valueof?: (value: T, index: number, values: any) => any): T;
```

However, I am not sure it would work for every case (does not worked for jsDoc `@yields` annotation ), but I think it can speed up the process.
