### ISSUE TITLE
Negative sign doesnt render in domain

### ISSUE THREAD

**Issue by Badri-Tib** [d3/d3#3450]
I tried to make a graph having axis with negative values and instead of the negative sign "-" I got this "âˆ’"
![image](https://user-images.githubusercontent.com/58753805/97312445-c6bd7280-1865-11eb-89e2-6a6e553f668f.png)

**Comment by mbostock** [comment]
Try adding 

```html
<meta charset="utf-8">
```

Or when you load d3-format, set the `charset="utf-8"` attribute.
