### ISSUE TITLE
Is there any widget available for selecting Xaxis and yaxis from the combo box for creating any type of graph?

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [d3/d3#3451]
I have table of data with column names.

Is there any available componenet to acheive the below.

Combox box shows with list of graph in D3.
THe user selects bar graph, then based on the selection , it will show 2 more combo box with the list of columns.
1 for X axis, another 1 for Y axis. After selecting the columns it will render the bar graph.

Thank you for your time :+1:

**Comment by curran** [comment]
@vijayakumarmariyappan This might be of interest: https://www.youtube.com/watch?v=j4VI47GlmGA&list=PL9yYRbwpkykuK6LSMLH3bAaPpXaDUXcLV&index=32

You may also like https://vega.github.io/voyager/ 

Generally this is not the best place to ask for help. Try the #help channel of the [D3 Slack](https://d3-slackin.herokuapp.com/), or [StackOverflow (D3 tag)](https://stackoverflow.com/questions/tagged/d3.js).

**Comment by vijayakumarmariyappan** [comment]
@curran Thanks again :+1:  Could you please update that if you have any other list of tools similar to voyager. Thanks for your help:)

**Comment by curran** [comment]
@vijayakumarmariyappan Voyager is part of the Vega ecosystem, worth checking out all that stuff:
 * https://vega.github.io/vega/
 * https://github.com/vega - poke around in here

Al the best!

**Comment by vijayakumarmariyappan** [comment]
@curran 
Thank you so much :+1:
