### ISSUE TITLE
d3 v6 is not supported in IE 11

### ISSUE THREAD

**Issue by pankajupadhyay29** [d3/d3#3453]
D3 V6 is not working in IE11 because of arrow functions, it failed with syntax error as below
![image](https://user-images.githubusercontent.com/11428124/101635324-b7634480-3a21-11eb-86b1-aec1bbb479a7.png)
To reproduce this just create a simple example page like
```html
<html>
<head>
<script src="https://d3js.org/d3.v6.js"></script>
<script>
function onLoad() {
	console.log(d3);
	d3.select("body").style("background-color", "black");
	d3.select("body").style("color", "white");
}
</script>
</head>
<body onload="onLoad()">
Hello
</body>
</html>
```

**Comment by gordonwoodhull** [comment]
This is intentional. [d3@6 uses ES2015](https://github.com/d3/d3/releases/tag/v6.0.0)

You need to stick with v5 or transpile if you still need to support IE, which is not supported by Microsoft anymore.
