### ISSUE TITLE
how to verify d3 number format?

### ISSUE THREAD

**Issue by yankeeguyu** [d3/d3#3456]
how to verify d3 number format? e.g. someone input number, how to vefify number is d3 format?

**Comment by curran** [comment]
Can you add more detail about what you are trying to do?

What exactly does it mean to "vefify number is d3 format"?

**Comment by yankeeguyu** [comment]
> Can you add more detail about what you are trying to do?
> 
> What exactly does it mean to "vefify number is d3 format"?


I want to know if the content entered by the user is in d3 format.
e.g. Users input text is `,.1f`, `,.3%`, i verify this is d3 format, but users input `0.00`, this isn't d3 format.

**Comment by mbostock** [comment]
No, this is not supported. Related https://github.com/d3/d3-format/issues/20.

**Comment by yankeeguyu** [comment]
Ok, thanks!
