### ISSUE TITLE
README/API would benefit from vanilla html/js getting started section (not Observable).

### ISSUE THREAD

**Issue by haydenlinder** [d3/d3#3460]
The existing API docs lack complete examples (only fragments of javascript without corresponding html), and Observable doesn't simulate a real development environment, making the learning curve for this library very steep. 

This github would benefit from a 'getting started'/examples section with complete vanilla html/js examples to make it accessible to beginners who plan to use it with html/js.

**Comment by mbostock** [comment]
Thanks for the feedback. Maintaining the examples and the API reference, in addition to the code itself, is a lot of work, and I don’t plan on maintaining a separate set of vanilla examples in addition to the Observable ones. I’d be happy to point to a community-maintained set of vanilla examples. One issue there is that many community examples are out of date; for example, the [D3 Graph Gallery](https://www.d3-graph-gallery.com) is mostly on version 4. You can also find many old versions of the D3 examples, now unmaintained, as [GitHub gists](https://gist.github.com/mbostock).

**Comment by curran** [comment]
@haydenlinder You may like https://vizhub.com/create-viz
