### ISSUE TITLE
Uncaught (in promise) ReferenceError: FileAttachment is not defined.

### ISSUE THREAD

**Issue by Adi-11** [d3/d3#3461]
```
(async () => {
  const file = d3.csvParse(
    await FileAttachment("category-brands.csv").text(),
    d3.autoType
  );
  data = file;
  console.log(data);
})();
```

**Giving Error: _Uncaught (in promise) ReferenceError: FileAttachment is not defined._**
Even after looking for all the resources, no solution was found!!

**Comment by Fil** [comment]
FileAttachment is defined in https://github.com/observablehq/stdlib and mostly for use on https://observablehq.com ; to load files you can alternatively use [fetch](https://fetch.spec.whatwg.org/), or in the case of a CSV file, [d3.csv](https://github.com/d3/d3-fetch/blob/master/README.md#csv).
