### ISSUE TITLE
Wiki edit: broken tutorial link

### ISSUE THREAD

**Issue by tigerxy** [d3/d3#3470]
Broken link is in `Tutorials.md`. Quick fix:

78 - `- [Converting dynamic SVG to PNG with node.js, d3 and Imagemagick](http://eng.wealthfront.com/2011/12/converting-dynamic-svg-to-png-with.html) - Wealthfront`
78 + `- [Converting dynamic SVG to PNG with node.js, d3 and Imagemagick](https://eng.wealthfront.com/2011/12/22/converting-dynamic-svg-to-png-with-node-js-d3-and-imagemagick/) - Wealthfront`

**Comment by Fil** [comment]
fixed by https://github.com/d3/d3/wiki/Tutorials/076be50339510ca18fe702486e8dbf8200ed0262

thank you!
