### ISSUE TITLE
d3-sankey is missing in package.json and index.js

### ISSUE THREAD

**Issue by DavidBruant** [d3/d3#3484]
I have read the warning and i still believe this is the correct repo for this issue

I tried the following (reduced test case):
```js
import * as d3 from 'd3'; 

d3.sankeyLinkHorizontal()
```

and `d3.sankeyLinkHorizontal` does not exist

I have noticed that d3-sankey is neither in package.json nor listed as `export * from ...` in index.js

If this is actually an issue, i'm happy to make the PR

**Comment by Fil** [comment]
Like other modules (d3-hexbin, d3-geo-projection etc), d3-sankey is a module but is not part of the main distribution.
