### ISSUE TITLE
Graphviz (Sugiyama) layout.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#349]
Something along these lines: http://www.graphviz.org/Documentation/TSE93.pdf

**Comment by gaitat** [comment]
Just wondering what is the status of the Sugiyama layout in d3

thank you

**Comment by kbrock** [comment]
Hello @gaitat 

The main 2 javascript Sugiyama layout entries I use are:

- http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html
- https://github.com/mdaines/viz.js/

That first one is very d3 friendly, just not as dynamic as we've grown accustomed to. Hard for anything to reach the fluidity of d3.

**Comment by magneticnorth** [comment]
Not sure if this thread is comatose already,but if anyone is implementing, you would want to at least look at more recent techniques for layered graph crossing reduction and coordinate assignment, like this work of Brandes and Köpf. algo.uni-konstanz.de/publications/bk-fshca-01.pdf  There may be others from the same lab.  Bachmaier et al had a sifting algorithm that seems quite effective and might reduce the problems of quadratic increase in graph size due to creation of virtual nodes; see http://www.emis.de/journals/JGAA/accepted/2011/BachmaierBrandenburgBrunnerHubner2011.15.5.pdf
Stephen North   north@graphviz.org

**Comment by gaitat** [comment]
thank you very much for your suggestions.

**Comment by whitequark** [comment]
We've solved this a long time ago using dagre, in https://github.com/evilmartians/furnace-xray/blob/master/lib/furnace-xray/app/assets/javascripts/lib/drawer.js.coffee

**Comment by cpettitt** [comment]
Dagre uses Brandes and Köpf's paper (with a few minor fixes), and also took a huge amount of inspiration from Dr. North's paper, "A Technique for Drawing Directed Graphs". There would be no dagre without the work of Gansner, Koutsofios, North, and Vo. I've read Bachmaier's paper but haven't implemented it - dagre uses a barycenter strategy for crossing minimization.

**Comment by kocokolo** [comment]
Hello @ALL ,I am using https://github.com/OpenKieler/klayjs to do this job and that meet my need .

**Comment by ericmiao** [comment]
Really appreciate the effort here from cpettitt, webgraphviz, webcola, klayjs, ... etc.

Can I ask what is the latest status? There seem to be many excellent solutions here with external code base, yet I'd really like to see d3 to have its own layout engine to cover this, either from one of these solutions or come up with its own, I don't mind using any of these, as long as it's well integrated.

Is there any plan for this? Anyone tried to send @mbostock any git pull? Or @mbostock has any concerns or ideas of any better alternative?

**Comment by testn** [comment]
I also came across https://github.com/mstefaniuk/graph-viz-d3-js

**Comment by waldyrious** [comment]
@mbostock for reference, what exactly was the reason this was closed?

**Comment by mbostock** [comment]
I bulk-closed all open D3 issues as any active issues should now be tracked in the appropriate D3 sub-repository.

Also I have no immediate plans to implement this specific functionality, and it makes perfect sense for it to be implemented as a [D3 plugin](https://bost.ocks.org/mike/d3-plugin).

**Comment by waldyrious** [comment]
> it makes perfect sense for it to be implemented as a D3 plugin.

I was wondering if https://github.com/mstefaniuk/graph-viz-d3-js or https://github.com/cpettitt/dagre-d3/ could be converted into such a plugin. /cc @mstefaniuk, @cpettitt

**Comment by mstefaniuk** [comment]
Componentmstefaniuk/ graphviz

**Comment by magjac** [comment]
@waldyrious: I just released the new [d3-graphviz](https://github.com/magjac/d3-graphviz) plugin if you're still interested. It's also based on [Viz.js](https://github.com/mdaines/viz.js/).
