### ISSUE TITLE
Release maintenance d3-geo@2.0.2 and d3@6.7.1?

### ISSUE THREAD

**Issue by Fil** [d3/d3#3504]
Because of https://github.com/observablehq/plot/issues/430 we should probably release a maintenance version of d3-geo@2 based on https://github.com/d3/d3-geo/commit/54f8890a44826828bd29a81d0bc6dfba9e6786b4, and by way of consequence a maintenance version of d3@6.

**Comment by mbostock** [comment]
We don’t need to publish a patch of d3, just of d3-geo, which I’ve done.
