### ISSUE TITLE
D3 latest version is using older version of d3-array

### ISSUE THREAD

**Issue by cdeepshikha23** [d3/d3#3505]
Have installed and using latest version (6.7.0) of d3 package.

 
This is still installing the older version of d3-array package which is 2.12.1 .

While using the latest version of d3 package below is the error that occurred.

<img width="1311" alt="Screenshot 2021-06-10 at 9 09 17 PM" src="https://user-images.githubusercontent.com/41605876/121555203-6d8b0380-ca30-11eb-9b3a-6b46031c437b.png">

**Comment by Fil** [comment]
The new d3-array will be bundled with d3@7 which is not out yet.

**Comment by Narinderg** [comment]
But, then the current latest d3 package is giving error aa mentioned.

**Comment by Fil** [comment]
How can we reproduce the error?

**Comment by curran** [comment]
It looks like the environment or build tool there does not support ES6 arrow functions.

**Comment by daftspaniel** [comment]
Get the same error running Jest in CI mode but not locally. Still looking into this issue but seems to be something to do with babel-jest not processing cumsum.js even if the modules are in the transform list.

**Comment by cederom** [comment]
Yup. BLOCKER. D3 seems broken because of that D3-ARRAY Unexpected Token problem. I am using it wit React 16.13.1 and React Native 0.63.4 and Node 16.6.1. https://stackoverflow.com/questions/68376430/d3-giveing-error-of-unexpect-token-on-import

**Comment by cederom** [comment]
Turns out to be Babel compiler bug, should be fixed with https://github.com/babel/babel/pull/13581, thank you @mbostock :-)
