### ISSUE TITLE
Wiki latest link error

### ISSUE THREAD

**Issue by petermcd** [d3/d3#3512]
https://github.com/d3/d3/wiki has a link to the latest version in the instaling section. This points too https://unpkg.com/d3/build/ which appears to forward too https://unpkg.com/browse/d3@7.0.0/build/ but the output on the page is:

```
Not found: d3@7.0.0/build/
```

**Comment by mbostock** [comment]
Fixed. The current instructions are here: https://github.com/d3/d3/blob/main/README.md#installing
