### ISSUE TITLE
D3 / d3-array/dist/d3-array.js: Unexpected token (139:15)

### ISSUE THREAD

**Issue by cederom** [d3/d3#3527]
Hello world :-) 

`d3` is broken on import because of `d3-array` problem reported here https://github.com/d3/d3-array/issues/229.

This problem is also reported on closed unsolved Issue https://github.com/d3/d3/issues/3505.

I need to remove all references to `d3` from my project as this happens on `import * as d3 from 'd3';`:

```
Android Bundling failed 4845ms
SyntaxError: (..)my_project/node_modules/d3-array/dist/d3-array.js: Unexpected token (139:15)

  137 |   var sum = 0, index = 0;
  138 |   return Float64Array.from(values, valueof === undefined
> 139 |     ? v => (sum += +v || 0)
      |                ^
  140 |     : v => (sum += +valueof(v, index++, values) || 0));
  141 | }
  142 |
```

Please advise :-)

**Comment by mbostock** [comment]
Duplicate of https://github.com/d3/d3-array/issues/147.
