### ISSUE TITLE
Infinite loop in ticks function

### ISSUE THREAD

**Issue by Monsignor** [d3/d3#3543]
In the ticks function, there is a way to create an infinite loop.

```
d3.axisBottom(x)
                .tickFormat(d3.timeFormat("%m/%y")).ticks(d3.timeMonth)
                .ticks(d3.timeDay.filter(function(d) {
                    console.log(d.getFullYear(), d.getMonth, d.getDate())l
                    return d.getMonth() === 10;
                }))
```

Here, I wanted to show ticks only for data points in November. This condition happened to always be false.

Despite the x.domain() begin from 2002 to 2023 in my data, the loop runs from the year 2023 backwards in time, to negative infinity. At least I think - the last time, I interrupted the loop at around 400 B.C.

To recreate the issue:

```
d3.axisBottom(x)
                .tickFormat(d3.timeFormat("%m/%y")).ticks(d3.timeMonth)
                .ticks(d3.timeDay.filter(function(d) {
                    return false;
                }))
```

**Comment by mbostock** [comment]
This isn’t related to d3.ticks; the loop occurs within your faulty filtered time interval because the filter never returns true. You can see the loop here:

https://github.com/d3/d3-time/blob/08cdaa68cdfbd44342342d99ea133979d599c01d/src/interval.js#L38-L50

You can reproduce the problem here:

```js
const filter = d3.utcDay.filter(() => false);
filter(new Date);
```

**Comment by Monsignor** [comment]
It's not faulty, I just don't want to show any ticks unless there is data in November. The data is otherwise fine. If I don't try to create ticks, the chart works fine otherwise.

An infinite loop should never be expected behavior; in this case, the reasonable behavior would be to return no ticks and let the chart render normally.
