### ISSUE TITLE
Consider editing repository setings to remove "Packages" section

### ISSUE THREAD

**Issue by matkoniecz** [d3/d3#3549]
"Packages No packages published" is displayed right now, fortunately this pointless section can be removed.

Edit repo page config to remove it (cog next to the description).

I am not making a PR as it is defined in proprietary github settings, not in a git repository - and I have no rights to modify repo settings.

![Peek 2020-10-25 09-10](https://user-images.githubusercontent.com/899988/97102018-3a168700-16a2-11eb-8c18-7bd9a88922eb.gif)

**Comment by mbostock** [comment]
Done, thanks for the tip.
