### ISSUE TITLE
csvParse, autoType, readFileSync, return string keys

### ISSUE THREAD

**Issue by winner106** [d3/d3#3557]
when I wrote the code in node as follows, It will return string keys.

my local  csv file :

![image](https://user-images.githubusercontent.com/50519642/156351508-1a87b44f-ef45-49ba-a944-ab13b58e8b5e.png)

run the code to get data from local csv file: 

```js
  const data = csvParse(
    readFileSync(join("data", "population.csv"), "utf8"),
    autoType
  );
```

and the result of `data` is (return string keys of country):

![image](https://user-images.githubusercontent.com/50519642/156351772-cf1aee63-f167-4a32-887a-b159ce744a2b.png)

### the correct key name should be `country` ,  not `'country'`

when I only use `csvParse`, the problem still happen

```js
  const data = csvParse(readFileSync(join("data", "population.csv"), "utf8"));
  console.log(data);
```
![image](https://user-images.githubusercontent.com/50519642/156354181-b945d22d-992c-4e6d-b71e-7c85fbc50df0.png)

**Comment by Fil** [comment]
The confusion probably comes from the way you're printing the array? If the key is indeed 'country', you should see this:

~~~js

[
  { "'country'": 'China', population: 1439000000 },
  columns: [ 'country', 'population' ]
]
~~~

can you try this?
~~~sh
   echo 'console.log({country: "China", population: 1.439})' | node
~~~

**Comment by winner106** [comment]
> The confusion probably comes from the way you're printing the array? If the key is indeed 'country', you should see this:
> 
> ```js
> [
>   { "'country'": 'China', population: 1439000000 },
>   columns: [ 'country', 'population' ]
> ]
> ```
> 
> can you try this?
> 
> ```shell
>    echo 'console.log({country: "China", population: 1.439})' | node
> ```

![image](https://user-images.githubusercontent.com/50519642/156356069-b5d6ad86-c70a-472e-b9d5-aa560bd6309d.png)

**Comment by winner106** [comment]
> The confusion probably comes from the way you're printing the array? If the key is indeed 'country', you should see this:
> 
> ```js
> [
>   { "'country'": 'China', population: 1439000000 },
>   columns: [ 'country', 'population' ]
> ]
> ```
> 
> can you try this?
> 
> ```shell
>    echo 'console.log({country: "China", population: 1.439})' | node
> ```

I try logging `data.country`, `data["'country'"]` ,  then result is `undefined`

**Comment by winner106** [comment]
@Fil  it works , is I do this
![image](https://user-images.githubusercontent.com/50519642/156360037-cc833170-3a84-4399-9ba9-d6b7c8216f01.png)

**Comment by Fil** [comment]
Ah, maybe the initial problem is because your file starts with a BOM (https://en.wikipedia.org/wiki/Byte_order_mark)? This could explain what you see.

**Comment by winner106** [comment]
> Ah, maybe the initial problem is because your file starts with a BOM (https://en.wikipedia.org/wiki/Byte_order_mark)? This could explain what you see.

yes , you are right , thanks ! saved my life!

**Comment by Fil** [comment]
No, it's something that should be handled by the ingestion process (node's fs, in this case).

**Comment by winner106** [comment]
> No, it's something that should be handled by the ingestion process (node's fs, in this case).

maybe, but if d3.csvParse can make it done would be perfect! I finally found this, also a csv Parser. [https://csv.js.org/parse/options/bom/](https://csv.js.org/parse/options/bom/)
