### ISSUE TITLE
Uncaught TypeError: r.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by makingbands** [d3/d3#3558]
Uncaught TypeError: r.compareDocumentPosition is not a function   at qn.order (d3.v7.min.js:2:22488)     at qn.join (d3.v7.min.js:2:22022)

It's a very good thing I only use min.js from a cdn or I would not have the exact line number: "2" where the error occurs.
(a&&**4^r.compare**DocumentPosition(a)&&a.parentNode.insertBefore(r,a),a=r);return this},

I'm not sure if I am just behind the times but I do not believe I have seen the 4 raised to the power of r.compareDocumentPosition(...) nomenclature previously.   I'm going to roll back to an older version as I'm thinking this is a typo.  Cheers.

**Comment by makingbands** [comment]
Ugh... I wish I could jump in here and say I figured out the problem; but I don't know why there are so many things going on in the second for loop declaration =/  

I'm a bit out of my league there cause I know this simple looking code is probably some of the soup that makes d3 so easy to use.  I'm not going try to solve it but I know that removing the semi-colon 
        if (next && node.compareDocumentPosition(next) ^ 4) next.parentNode.insertBefore(node, next);
makes all the red go away =D in my browser.

Also, this goes back as far as 6 and is not caused by the minified code sadly it is a bug.

```
function selection_order() {

  for (var groups = this._groups, j = -1, m = groups.length; ++j < m;) {
    for (var group = groups[j], i = group.length - 1, next = group[i], node; --i >= 0;) {
      if (node = group[i]) {
        if (next && node.compareDocumentPosition(next) ^ 4) next.parentNode.insertBefore(node, next);
        next = node;
      }
    }
  }

  return this;
}
```

**Comment by makingbands** [comment]
This may be of interest I was easily able to un-produce the error by not using a repugnant variation of the join pattern:

This very beautiful code will probably warm the heart of the writer(s) of d3: 

```

                let chipsTransformer = function(state) {state.append('rect').attr('height',pSize).attr('width',pSize).attr('color', d=>{return `rgb(${d.r},${d.g},${d.b})`}).attr('fill', d=>{return `rgb(${d.r},${d.g},${d.b})`}).attr("transform", (d,i)=>{return `translate(${ (   (((i*pSize)/1280)-(Math.floor(i* (i/1280)))) - Math.floor( (((i*pSize)/1280)-(Math.floor(i* (i/1280)))))          ) * 1280 },${Math.floor(i/(1280/pSize))*pSize})`}); return state;}
                chips.data(tiles).join(enter=>chipsTransformer(enter), update=>chipsTransformer(update), exit=>exit.remove());

```
_huh what does scalelinear have to do with anything_ 

These two lines, literally, work the two lines above are what triggered the error:

   ```
             let chipsTransformer = function(state) {state.append('rect').attr('height',pSize).attr('width',pSize).attr('color', d=>{return `rgb(${d.r},${d.g},${d.b})`}).attr('fill', d=>{return `rgb(${d.r},${d.g},${d.b})`}).attr("transform", (d,i)=>{return `translate(${ (   (((i*pSize)/1280)-(Math.floor(i* (i/1280)))) - Math.floor( (((i*pSize)/1280)-(Math.floor(i* (i/1280)))))          ) * 1280 },${Math.floor(i/(1280/pSize))*pSize})`}); return state;}
                chips.data(tiles).join(enter=>enter.append('rect').attr('height',pSize).attr('width',pSize).attr('color', d=>{return `rgb(${d.r},${d.g},${d.b})`}).attr('fill', d=>{return `rgb(${d.r},${d.g},${d.b})`}).attr("transform", (d,i)=>{return `translate(${ (   (((i*pSize)/1280)-(Math.floor(i* (i/1280)))) - Math.floor( (((i*pSize)/1280)-(Math.floor(i* (i/1280)))))          ) * 1280 },${Math.floor(i/(1280/pSize))*pSize})`}), update=>update, exit=>exit.remove());
```

**Comment by Fil** [comment]
Please try and create a clear bug report, with a minimal reproduction of the issue you are facing, ideally in an observable notebook.

PS: ^ is the bitwise XOR operator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_XOR
