### ISSUE TITLE
Error in d3.json function or advertised in the wrong way!

### ISSUE THREAD

**Issue by RiadOkba** [d3/d3#3559]
The function d3.json doesn't deliver as explained in many tutorials. In every tutorials, they considered d3.json as d3.csv but for JSON format. So they explain this would work:
d3.json("./data/users.json", function(error, data) {
 d3.select("body").selectAll("p").data(data).enter().append("p").text(function(d) {
          return d.name + ", " + d.location;
      });
});

It doesn't ! Viewing the code in d3.v7.js, the d3.json should work like so:
d3.json("./data/users.json").then ( data => {
    d3.select("body").selectAll("p").data(data).enter().append("p").text(function(d) {
          return d.name + ", " + d.location;
      });
});

So if I'm not wrong, either d3 module should be readjusted making d3.json works in the same logic as d3.csv or all tutorials about d3.json in the web needs to be informed about the mistake...

Please if I'm wrong correct me.

**Comment by Fil** [comment]
you're right; unfortunately no one has the capacity to reach out to every tutorial author on the internet

**Comment by curran** [comment]
The API changed in v5. Details are here https://github.com/d3/d3/blob/main/CHANGES.md#changes-in-d3-50
