### ISSUE TITLE
[feature] d3.csvParse should be a function

### ISSUE THREAD

**Issue by kkdd** [d3/d3#3581]
Hello,
I think that d3.csvParse should be a function.

When tested in Google Chrome 104.0.5112.79:

```
console.log(["foo,bar\n1,2", "foo,bar\n1,2"].map(csvParse));
==>  Uncaught TypeError: n is not a function
```

* Note that the following works well:

```
console.log(["foo,bar\n1,2", "foo,bar\n1,2"].map(dat=>d3.csvParse(dat)));
==>  [[{foo: "1", bar: "2"}, columns: ["foo", "bar"]], [{foo: "1", bar: "2"}, columns: ["foo", "bar"]]]
```

**Comment by mbostock** [comment]
When you invoke that way with array.map, you are passing additional arguments to csvParse leading to the error. Please see the documentation for these two functions for details.
