### ISSUE TITLE
The function without parameters and the lambda function performs differently

### ISSUE THREAD

**Issue by GaryBikini** [d3/d3#3582]
The code is below, and I want to show the value of `input` tag when typing in. But I find that the function without parameters `function(){...}` performs normally. But if I use the lambda function `()=>{...}`, a error raises: `this.value` is undefined when typing "abcd".

In my opinion, these two types of functions should behave exactly the same. Am I right? 

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <input id='myinput' type="text" value="abc" />
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script>

        // ****** Use the function without parameters ******
        // d3.select('#myinput').on('input', function () {
        //     console.log(this.value)  // output "abcd" when inputing "abcd"
        // })

        // ****** Use the lambda function  *****************
        d3.select('#myinput').on('input', () => {
            console.log(this.value)  // output "undefined" when inputing "abcd"
        })
    </script>
</body>

</html>
```

**Comment by magjac** [comment]
No. From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions:

> There are differences between arrow functions and traditional functions, as well as some limitations:
> 
> * Arrow functions don't have their own bindings to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this), [arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) or [super](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super), and should not be used as [methods](https://developer.mozilla.org/en-US/docs/Glossary/Method).
