### ISSUE TITLE
unmaintained dependency `dagre-d3` depends on vulnerable `d3-color` version

### ISSUE THREAD

**Issue by kamulos** [d3/d3#3588]
This is a bit frustrating: I run `npm audit` automatically in my project to catch CVEs. For a few days now this is always red, because the dependency tree of `d3` contains an old `d3-color` version, that is affected by [this vulnerability](https://github.com/advisories/GHSA-36jr-mh4h-2g58).

This old version of `d3-color` is pulled in via `dagre-d3` which is totally unmaintained and no update can be expected.

How can this be fixed?

**Comment by Fil** [comment]
If no one wants to maintain dagre-d3, I don't know. For the d3-color part, please follow the discussion in https://github.com/d3/d3-color/pull/100.
