### ISSUE TITLE
Upgrade d3-color to v3.1.0

### ISSUE THREAD

**Issue by digitaleyes00** [d3/d3#3589]
Please upgrade `d3-color` to use version 3.1.0 in order to fix this vulnerability.

> The d3-color module provides representations for various color spaces in the browser. Versions prior to 3.1.0 are vulnerable to a Regular expression Denial of Service. This issue has been patched in version 3.1.0. There are no known workarounds.

**Comment by Fil** [comment]
duplicate of https://github.com/d3/d3-color/pull/100
