### ISSUE TITLE
usage issue: how to export d3 parallel-coordinates images as PNG or SVG

### ISSUE THREAD

**Issue by Lijiaoa** [d3/d3#3605]
As the title, I want to export my parallel-coordinates as a image in the website, but I didn't find the way to export.

**Comment by Fil** [comment]
can you share the link? If it's on observable, you should be able to download it from the menu on the left on the cell that shows three vertical dots.

**Comment by Lijiaoa** [comment]
Thanks for your quick reply! My chart is the same as the picture. But I couldn't find the button to download it. My code is in here: https://github.com/microsoft/nni/blob/master/ts/webui/src/components/experiment/trialdetail/chart/Para.tsx

![image](https://user-images.githubusercontent.com/61399850/202391514-a0e29f7b-cade-49c9-b538-fd6e5f4df7f2.png)

**Comment by Fil** [comment]
Sorry, I don't see how this relates to D3. It's probably something that needs to be added on the website you're using.

**Comment by Lijiaoa** [comment]
Could you provide the related doc or example about parallel-coordinates chart download function? Thanks!

**Comment by Fil** [comment]
I'm afraid there is no such thing. To be clear, any download function must be implemented by the website; "download button" is not in the scope of what D3 does.

**Comment by Lijiaoa** [comment]
> If it's on observable, you should be able to download it from the menu on the left on the cell that shows three vertical dots.

so what's the meaning of this word? I think it says that d3 had the download function.

**Comment by Fil** [comment]
It meant that, if your visualization was made on the http://observablehq.com/ website, you'd have a download button. But that's because Observable creates download buttons, not D3.

Please address your questions to the https://github.com/microsoft/nni project instead, thank you.
