### ISSUE TITLE
[Bug] "d3@v7.7.0" could not be built. 

### ISSUE THREAD

**Issue by Turokhunter** [d3/d3#3607]
Hi,

My code was working two days ago, and then I received this issue. I haven't been able to find any reference to it online, so I decided to report it just in case it's a bug from the newest update. 

![image](https://user-images.githubusercontent.com/7236305/205462650-9d2b0b23-c047-40ed-a99e-6934ab2d5588.png)
![image](https://user-images.githubusercontent.com/7236305/205462660-04250951-5a83-43f6-a63d-548a94f46c67.png)
![image](https://user-images.githubusercontent.com/7236305/205462670-9eb542c5-fbae-48d4-8bc2-63c674415b9f.png)

**Comment by mathewtitus** [comment]
Just chiming in that the same behavior's occurring for my sites which use the same Skypack import scheme.

**Comment by mbostock** [comment]
This is a bug with Skypack. Track in https://github.com/skypackjs/skypack-cdn/issues/332.

As an alternative, it appears that [jsDelivr’s esm.run CDN](https://www.jsdelivr.com/esm) works as expected:

```js
import * as d3 from "https://cdn.jsdelivr.net/npm/d3@7.7.0/+esm";
```

**Comment by john-guerra** [comment]
I'm getting this same error when embedding an [Observable notebook](https://observablehq.com/@john-guerra/primera-vuelta-bogota-2022) on this [scrollytelling piece I made about the Colombian election](https://johnguerra.co/viz/resultadosPrimeraVuelta2022Bogota/)
