### ISSUE TITLE
Potential addition to the Tutorials wiki page

### ISSUE THREAD

**Issue by holtzy** [d3/d3#3632]
Hi,

I'm the maintainer of two d3 related websites:
- the [d3 graph gallery](https://www.d3-graph-gallery.com) displays many simple charts made in pure d3
- the [react graph gallery](https://www.react-graph-gallery.com) does the same, but using d3 for math and react for rendering

I was wondering if those 2 projects could be listed in the [tutorials wiki page](https://github.com/d3/d3/wiki/Tutorials)?

Thanks so much for your work on this awesome d3 project.

Note: I tried to open a PR but it looks like the wiki is not open for contributions 🤔 
Note: I can offer my help to check all the links listed in this wiki page to double check if they are all still alive

**Comment by curran** [comment]
I think this would be a great addition!

**Comment by holtzy** [comment]
Glad to hear this!

How can we proceed to add it? How can I help? I don't think I can do a PR on the wiki page unless I missed something.

**Comment by curran** [comment]
I'm not sure. I do not have permissions to change the wiki, and I'm not sure who does.

**Comment by mbostock** [comment]
We will be shutting down the wiki as part of the new website and documentation effort in #3655. The wiki has not been maintained for years and contains many stale and broken resources.
