### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by kondoumh** [d3/d3#3635]
It would be great if D3 could be used in SSR. With SSR available, we can offload data fetching and SVG rendering to the server side.
I heard that `d3.select` API works only on the client side, so it cannot support SSR. If a DOM library that operates on the server side, such as jsdom, is adopted inside D3.js, it may be possible to render SVG on the server side, that is, with Node.js, etc., and use hydration on the client side to realize an interactive UI. Is it not?

**Comment by mbostock** [comment]
You can already use D3 with JSDOM (as D3’s tests do).
