### ISSUE TITLE
CI: Set minimum permissions on GitHub Workflow

### ISSUE THREAD

**Issue by diogoteles08** [d3/d3#3636]
Hi!

I'd like to suggest the addition of top-level minimal permissions on your workflow, as it would harden your security agains supply-chain attacks.

I see that you have only one workflow, the [node.js.yml](https://github.com/d3/d3/blob/main/.github/workflows/node.js.yml), but it does not specify the permissions for its jobs, letting their privileges determined by GitHub's defaults. By defining minimal permissions you would be secured against erroneous or malicious actions from external jobs you call from your workflow. It's specially important for the case they get compromised, for example.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

I'd be happy to raise a PR with the changes if you agree.

#### Context
I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) suggesting and implementing security changes on critical open source projects :blush:

**Comment by mbostock** [comment]
Thank you for the report. I have changed the default workflow permissions for this repository to be restricted instead of permissive. I believe this should address the issue you raised, but please let me know if further action is needed.
