### ISSUE TITLE
Links to the d3 Slack on website and Github do not work

### ISSUE THREAD

**Issue by traitortots** [d3/d3#3645]
Hello! I tried sending a message on Twitter about this on 2/1/23, but got no response there. It seems like something is wrong with the link to the d3 Slack on [http://d3js.org](https://d3js.org/#:~:text=Chat%20with%20the%20community) (going to [https://d3-slackin.herokuapp.com](https://t.co/KRUYFO871U)) ![image](https://user-images.githubusercontent.com/88009118/228052588-9bc30178-f98b-47f2-8d9d-986c1ade9141.png)

It would be great to be able to connect with other d3 users/enthusiasts through the Slack platform!

**Comment by curran** [comment]
There is an open pull request here that fixes this issue: https://github.com/d3/d3.github.com/pull/28

Here's the link where folks can join the D3 Slack https://join.slack.com/t/d3js/shared_invite/zt-1neihq96a-xkXVPXYOmKg8ou7DL3kr7g

**Comment by curran** [comment]
It would be awesome if [https://d3-slackin.herokuapp.com](https://t.co/KRUYFO871U) redirected to https://join.slack.com/t/d3js/shared_invite/zt-1neihq96a-xkXVPXYOmKg8ou7DL3kr7g, as there are links to that URL all over the place.

**Comment by curran** [comment]
Who would be able to merge this and deploy the change?

**Comment by codingsagar** [comment]
I would like to contribute. Is this okay as a good first issue ? Then please assign it to me

**Comment by codingsagar** [comment]
And if you could give some instructions about the issue. As it's my first contribution.

Thanks
Sagar

**Comment by codingsagar** [comment]
Okay great 

Thanks

**Comment by mbostock** [comment]
Thank you for the report. We are aware of the issue and have decided as maintainers that we will no longer promote the current D3 community Slack and instead will encourage folks to use the [Observable community Slack](https://observable-community.slack.com/ssb/redirect) and [Observable forum](https://talk.observablehq.com/) (which we are already using for Observable and Observable Plot). We want to consolidate our efforts. We will be updating the Slack link as part of the ongoing website and documentation redesign in #3654.

**Comment by curran** [comment]
Here's the link where folks can join the D3 Slack https://join.slack.com/t/d3js/shared_invite/zt-1neihq96a-xkXVPXYOmKg8ou7DL3kr7g
