### ISSUE TITLE
Latest cdn link returns undefined for tooltip text. Previous cdn return values.

### ISSUE THREAD

**Issue by AtGbemiga** [d3/d3#3648]
I'm referring to <script src="https://d3js.org/d3.v7.min.js"></script>
Mouseon any data with this CDN returns undefined. Change the CDN to https://d3js.org/d3.v5.min.js and the right values are displayed. The same bug occurs on my other d3.js code. View on codepen here https://codepen.io/ATmanAtos/pen/ExdKoOw 
or
Here's my code.
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualize Data with a Heat Map</title>
    <link rel="stylesheet" href="styles.css">
    <script src="https://d3js.org/d3.v7.min.js"></script>
</head>
<body>
    <h1 id="title">Monthly Global Land-Surface Temperature</h1>
    <h3 id="description">1753 - 2015: base temperature 8.66℃</h3>
    <div id="tooltip">

    </div>
    <svg>
        
    </svg>
    <svg id="legend">
        <g>
            <rect x="10" y="0" width="40" height="40" fill="blue"></rect>
            <text x="60" y="20" fill="black">Variance of -1 or less</text>
        </g>
        <g>
            <rect x="10" y="40" width="40" height="40" fill="black"></rect>
            <text x="60" y="60" fill="black">On or below average</text>
        </g>
        <g>
            <rect x="10" y="80" width="40" height="40" fill="green"></rect>
            <text x="60" y="100" fill="black">Above average</text>
        </g>
        <g>
            <rect x="10" y="120" width="40" height="40" fill="red"></rect>
            <text x="60" y="140" fill="black">Variance of 1 or more</text>
        </g>
    </svg>
</body>
<script defer src="script.js"></script>
</html>`
`let url = 'https://raw.githubusercontent.com/freeCodeCamp/ProjectReferenceData/master/global-temperature.json'
let req = new XMLHttpRequest
let mv;
let baseTemp;
let values = [] //api data

let xScale 
let yScale

let width = 1200
let height = 600
let padding = 60

let svg = d3.select('svg')
let tooltip = d3.select('#tooltip')

const drawCanvas = () => {
    svg.attr('width', width)
    svg.attr('height', height)
}

const generateScales = () => {
    xScale = d3.scaleLinear()
        .domain([d3.min(mv, item => {
            return item.year
        }), d3.max(mv, item => {
            return item.year
        })])
        .range([padding, width - padding])

    yScale = d3.scaleTime()
        .domain([new Date(0, 0, 0, 0, 0, 0, 0), new Date(0, 12, 0, 0, 0, 0, 0)])
        .range([padding, height - padding])
}

const plotHeatMap = () => {
    svg.selectAll('rect')
        .data(mv)
        .enter()
        .append('rect')
        .attr('class','cell')
        .attr('fill', item => {
            if(item.variance <= -1) {
                return 'blue'
            } else if (item.variance <= 0) {
                return 'black'
            } else if (item.variance <= 1) {
                return 'green'
            } else {
                return 'red'
            }
        })
        .attr('data-month', item => {
            return item.month - 1
        })
        .attr('data-year', item => {
            return item.year
        })
        .attr('data-temp', item => {
            return baseTemp + item.variance
        })
        .attr('height', item => {
            return (height - (2 * padding)) / 12
        })
        .attr('width', item => {
            return (width - (2 * padding)) / item.year
        })
        .attr('y', item => {
            return yScale(new Date(0, item['month'] - 1, 0, 0, 0, 0, 0))
        })
        .attr('x', item => {
            return xScale(item.year)
        })
        .on('mouseover', item => {
            tooltip.style('visibility', 'visible')
            if (item.year != '') {
                tooltip.text(`${item.year} ${item.month} ${item.variance}`)
            } else {
                return ''
            }
        })
        .on('mouseout', item => {
            tooltip.style('visibility', 'hidden')
        })
}

const generateAxis = () => {
    let xAxis = d3.axisBottom(xScale)
        .tickFormat(d3.format('d')) 
    svg.append('g')
        .call(xAxis)
        .attr('id', 'x-axis')
        .attr('transform', `translate(0, ${height - padding})`)

    let yAxis = d3.axisLeft(yScale)
        .tickFormat(d3.timeFormat('%B'))
    svg.append('g')
        .call(yAxis)
        .attr('id', 'y-axis')
        .attr('transform', `translate(${padding}, 0)`)
}

req.open('GET', url, true)
req.onload = () => {
    values = JSON.parse(req.responseText)
    console.log(values)
    mv = values.monthlyVariance
    baseTemp = values.baseTemperature
    drawCanvas()
    generateScales()
    plotHeatMap()
    generateAxis()
}
req.send()`
`svg{
    background-color: whitesmoke;
}
#tooltip{
    visibility: hidden;
}`

**Comment by mbostock** [comment]
See the release notes.
