### ISSUE TITLE
fix links to bl.ocks

### ISSUE THREAD

**Issue by Fil** [d3/d3#3696]
source | target
-- | --
https://d3js.org/d3-color | http://bl.ocks.org/mbostock/3e115519a1b495e0bd95
https://d3js.org/d3-color | http://bl.ocks.org/mbostock/78d64ca7ef013b4dcf8f
https://d3js.org/d3-color | http://bl.ocks.org/mbostock/9f37cc207c0cb166921b
https://d3js.org/d3-color | http://bl.ocks.org/mbostock/debaad4fcce9bcee14cf
https://d3js.org/d3-force/link | https://bl.ocks.org/mbostock/f584aa36df54c451c94a9d0798caed35
https://d3js.org/d3-force/simulation | https://bl.ocks.org/mbostock/01ab2e85e8727d6529d20391c0fd9a16
https://d3js.org/d3-force/simulation | https://bl.ocks.org/mbostock/1667139
https://d3js.org/d3-geo/path | https://bl.ocks.org/mbostock/5663666
https://d3js.org/d3-geo/projection | https://bl.ocks.org/mbostock/5126418
https://d3js.org/d3-hierarchy/pack | https://bl.ocks.org/mbostock/751fdd637f4bc2e3f08b
https://d3js.org/d3-scale-chromatic | https://bl.ocks.org/mbostock/048d21cf747371b11884f75ad896e5a5
https://d3js.org/d3-scale-chromatic/cyclical | http://bl.ocks.org/mbostock/310c99e53880faec2434
https://d3js.org/d3-selection/joining | http://bl.ocks.org/mbostock/3808218
https://d3js.org/d3-transition/modifying | https://bl.ocks.org/mbostock/3916621

do we want to create notebooks? or defer to another block viewer in the meantime?

Also this link has changed: https://d3js.org/d3-selection/joining => http://bost.ocks.org/mike/bar/2/ is now redirected to https://observablehq.com/@d3/lets-make-a-bar-chart/2

**Comment by nachocab** [comment]
Also add https://d3js.org/d3-selection/control-flow#selection_each => https://bl.ocks.org/mbostock/4c5fad723c87d2fd8273

**Comment by curran** [comment]
I vote to add links into https://blocks.roadtolarissa.com/
