### ISSUE TITLE
d3__WEBPACK_IMPORTED_MODULE_0__.hierarchy is not a function

### ISSUE THREAD

**Issue by mbasakCinedigmInd** [d3/d3#3742]
const root = d3
.hierarchy(data)
.sum(d => d.value)
.sort((a, b) => b.value - a.value)
.eachAfter(
d =>
(d.index = d.parent ? (d.parent.index = d.parent.index + 1 || 0) : 0)
);

versions :

"react": "^18.2.0",
"d3": "^3.5.17"

how to solve this?

repository : https://github.com/mbasakCinedigmInd/d3-hierarchical-bar-chart.git

I created this repository.. please tell me you need anything else. I am desperately searching for a solution

**Comment by curran** [comment]
>how to solve this?
Use the latest version of D3, not version 3.
