### ISSUE TITLE
API doc links in example notebooks still point to README

### ISSUE THREAD

**Issue by mootari** [d3/d3#3784]
Most of d3's package READMEs have been updated to point to https://d3js.org/ for the package's documentation. However, many example notebooks still include links that point to a package's README.

Example:
- Notebook: https://observablehq.com/@d3/d3-scaleordinal
- API link: https://github.com/d3/d3-scale/blob/master/README.md#ordinal_domain
- Actual location: https://d3js.org/d3-scale/ordinal#ordinal_domain

**Comment by Fil** [comment]
It may take a while since there are lots of notebooks to fix
https://observablehq.com/search?query=%22https%3A%2F%2Fgithub.com%2Fd3%2F%22+%40d3&creator=fil&sort=relevance&direction=desc&useES=true&accessPublic=true

2 done, 94 to go :)

**Comment by Fil** [comment]
I think I'm done, but it's hard to search for that pattern and I might have missed some.

**Comment by Fil** [comment]
I've found 91 more notebooks that need changes!

**Comment by Fil** [comment]
Note: some notebooks are still pointing to github because they reference d3-tile, d3-hexbin, d3-geo-projection etc. + specific cases like linking to a source code file or locale json.
