### ISSUE TITLE
d3.min and d3.least don't always ignore nulls

### ISSUE THREAD

**Issue by helderdarocha** [d3/d3#3790]
The documentation states, for `d3.min`, that "Unlike the built-in `Math.min` this method ignores `undefined`, `null` and `NaN` values", so I would expect that if I had an array:
```
array = ['5', '10', null, '2']
```
then `d3.min(array)` would return `'10'` (which is expected, since natural order is used), and `d3.min(array, d => +d)` would return `2`.

But no, `d3.min(array)` returns `0` (as expected, because `null` coerces to zero _before_ the accessor function is called, but the user that expects nulls to be ignored might not care to verify this). Although the issue is actually in the conversion, this is easy to overlook and can lead to bugs. 

The documentation for `d3.least` doesn't explicitly mention that it ignores null, but in this example, `d3.least(array, d => +d)` returns `null` (shouldn't it produce the same result as `d3.min` when using an accessor?)

**Comment by mbostock** [comment]
<img width="238" alt="Screenshot 2023-10-28 at 8 49 37 AM" src="https://github.com/d3/d3/assets/230541/0e312c72-1278-44fa-a599-e2e8fcfe0bd5">

You’re probably using an old version of D3?

**Comment by mbostock** [comment]
As for the other cases, this:

```js
d3.min(['5', '10', null, '2'], (d) => +d)
```

is equivalent to this:

```js
d3.min(['5', '10', null, '2'].map((d) => +d))
```

is equivalent to this:

```js
d3.min([5, 10, 0, 2])
```

hence it returns zero.

And likewise for d3.least, it doesn’t care that the _element_ is null, it cares whether the return value of the given accessor is null. So if you coerce null to zero in your accessor, and zero is the least value, then d3.least will return the corresponding element which is null.

**Comment by helderdarocha** [comment]
Yes. Thank you. I know this is the expected behavior. The problem is that the accessor is not really being used to access anything, but to coerce and change values in the dataset, which can lead to cryptic code. Mislead by an example of mine where I used +d to coerce strings, my student spent a day trying to fix a bug and fixed it after removing nulls from her dataset. She had understood that extent should ignore nulls, but wasn't aware that they were being coerced.

**Comment by mbostock** [comment]
Yes, I recommend that you apply type coercion as early as possible — ideally when the data is loaded, say by using d3.autoType in conjunction with d3.csv, or Observable’s FileAttachment helper with typed: true. If you defer type coercion until later, there is much more surface area for these problems.
