### ISSUE TITLE
Replace Math.random() with crypto function

### ISSUE THREAD

**Issue by swetha8612** [d3/d3#3807]
There is a Math.random() in dist/d3.js file.
Please update it with crypto function like **window.crypto.getRandomValues(new Uint32Array(10))[0]**
The fortify scan is raising it as a security vulnerability during the scan.

**Comment by swetha8612** [comment]
is there a new version for this change?

**Comment by mbostock** [comment]
No, I’m declining your request as it is nonsensical.

**Comment by swetha8612** [comment]
We are using d3 package in some of our projects and when we ran fortify scans it has been flagged as high vulnerability. It is asking to replace Math.random() to crypto function. There are other packages which have this same issue. I am trying to contact them as well. Thank you.

**Comment by jayDayZee** [comment]
My friend,

the random numbers generated within D3 do not have a security implication.
What you should be doing is informing your "foritfy" widget that d3 is not
part of your security / privacy landscape, not asking a graphics / data
analytics tooling to present cryptographic random numbers.

Christopher Reay (they / them)


Be prepared to have your predictions come true
