### ISSUE TITLE
Non english language texts being cut off

### ISSUE THREAD

**Issue by mona456** [d3/d3#3809]
I am using the following d3 libraries in my angular application
 "d3": "^5.12.0",
    "d3-tip": "^0.9.1",
    
Our application supports 14 non english languages, when it is russian language the text is cut off and it is a blocker for russian users.

![image](https://github.com/d3/d3/assets/102917906/e1a7f0b1-4cce-4189-8028-c0d0d4d5be98).

Please do the needful

**Comment by mona456** [comment]
why is it closed? is my issue shifted somehwere?

**Comment by mbostock** [comment]
You’ll need to find someone else to help you.

**Comment by mona456** [comment]
I didnt understand.

am i at the wrong place posting my question?
________________________________

**Comment by mbostock** [comment]
Yes, this is the wrong place. We can’t help you.
