### ISSUE TITLE
the wrong parameter name at Binning data of d3-array documentation 

### ISSUE THREAD

**Issue by Benbinbin** [d3/d3#3830]
the parameter name of [bin.thresholds](https://d3js.org/d3-array/bin#bin_thresholds) is `count`

but in the next two paragraph use the `thresholds` as the parameter name

> If _thresholds_ is specified ...

> If _thresholds_ is not specified ... will have _thresholds_.length + 1

although it is a minor issue, fixing it will improve readers' understanding of the document

**Comment by AlejandroBlanco2001** [comment]
Hey @Benbinbin @mbostock  , I really like the project, can I pick this issue?

**Comment by mbostock** [comment]
It’s not incorrect. The value can be any number of things (a count, an array of values, or a function). We used the name count because it’s the most common case.

**Comment by AlejandroBlanco2001** [comment]
This issue should be close then?

**Comment by Benbinbin** [comment]
> It’s not incorrect. The value can be any number of things (a count, an array of values, or a function). We used the name count because it’s the most common case.
> 
> Edit: but probably calling it _thresholds_ as the most generic name is the right thing to do for the docs.

yep, it's just a small issue in Docs, maybe change the parameter name to `thresholds` can make the context more consistent and easier for readers to understand.
