### ISSUE TITLE
Adding a link towards DefinitelyTyped

### ISSUE THREAD

**Issue by terrence-ou** [d3/d3#3840]
Hi, I'm browsing the npm installation section of Getting Started on the D3 website (https://d3js.org/getting-started#installing-from-npm). At the bottom of that section is "TypeScript declarations are available via DefinitelyTyped." Would it be helpful to add a link to the DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped) to make the reader navigate to that repo more easily? Thanks for reviewing this issue!

**Comment by AlejandroBlanco2001** [comment]
Hey @terrence-ou , I agree with you, I will make a PR to solve this issue. :smile:
