### ISSUE TITLE
Add Repobeats (metrics) to README

### ISSUE THREAD

**Issue by JuanPabloDiaz** [d3/d3#3898]
[Repobeats](https://repobeats.axiom.co) is a way to embed contributor analytics into your GitHub project's README.md

Metrics are everything. Data is powerful

#### Project Examples:

- [FreeForGeeks](https://github.com/JuanPabloDiaz/freeForGeeks#how-to-contribute)
- [Tabler](https://github.com/tabler/tabler#-project-activity)
- [Projectdiscovery](https://github.com/projectdiscovery/nuclei-templates#-contributions)
- [ArchiSteamFarm](https://github.com/JustArchiNET/ArchiSteamFarm)
- [Growthbook](https://github.com/growthbook/growthbook#license)

![image](https://github.com/user-attachments/assets/3e27ce01-cfb9-4091-bdc8-56bb6572e408)

**Comment by Fil** [comment]
Thanks for the suggestion.
