### ISSUE TITLE
`geoContains(object, point)` returns `true` for a `point` outside the `object`

### ISSUE THREAD

**Issue by pete-murphy** [d3/d3#3937]
### Minimal reproduction

This works as expected:
```js
d3.geoContains(
  {
    type: "Polygon",
    coordinates: [
      [
        [0, 0],
        [0, 1],
        [1, 1],
        [1, 0],
        [0, 0]
      ]
    ]
  },
  [2, 2]
) //-> false
```
but when `coordinates` includes some negative numbers, `geoContains` unexpectedly returns `true`
```js
d3.geoContains(
  {
    type: "Polygon",
    coordinates: [
      [
        [0, 0],
        [0, 1],
        [-1, 1],
        [-1, 0],
        [0, 0]
      ]
    ]
  },
  [2, 2]
) //-> true
```

### Discussed in https://github.com/d3/d3/discussions/3936

<div type='discussions-op-text'>

<sup>Originally posted by **pete-murphy** October 16, 2024</sup>
`d3.geoContains(polygon, point)` returns `true` for a `point` that is outside the `polygon`. Maybe I'm not using the right format?
See this notebook: https://observablehq.com/d/e5b29db5ddda89f8</div>

**Comment by mbostock** [comment]
Probably a winding order issue. Did you try geoRewind?

**Comment by pete-murphy** [comment]
> Did you try geoRewind?
Is that from this library? The only search result for `geoRewind` is this issue 🙈 https://github.com/search?q=repo%3Ad3%2Fd3+geoRewind&type=code
Not getting much from Googling that either...

**Comment by pete-murphy** [comment]
Oh I see a `rotation.invert` maybe that's it?

**Comment by pete-murphy** [comment]
OK so I think I can just call `.toReversed()` on all the coordinates, and that resolves the issue. I don't know how my data ended up with the wrong winding order.

**Comment by mbostock** [comment]
Apologies for the cryptic hint. I meant: https://observablehq.com/@fil/rewind
