### ISSUE TITLE
ReDoS vulnerability on RegExp used in d3js

### ISSUE THREAD

**Issue by rajkumarg736** [d3/d3#3939]
In d3js latest version 7.9.0, starting from older versions like 3.5.17 reported with ReDoS vulnerability on the regular expression used 
`/[-+]?(?:\d+\.?\d*|\.?\d+)(?:[eE][-+]?\d+)?/g `
In latest version 7.9.0 line no,: 3662 this regular expression present.
Few links related to this vulnerability,
CWE: https://cwe.mitre.org/data/definitions/400.html
OWASP: https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS
Reference: https://snyk.io/blog/redos-and-catastrophic-backtracking/ 

Is there any solution or workaround for this ReDoS attack from d3js or community?

**Comment by curran** [comment]
Are you able to successfully execute the ReDoS attack on an example D3 program?

It's probably not even a real attach vector. I'd guess it's an overly eager security reporting tool.

**Comment by mbostock** [comment]
This is presumably referring to the regular expression used by d3.interpolateString that finds numbers embedded within strings.

https://github.com/d3/d3-interpolate/blob/2eeffc0d02f2947552cf0a0b73bdf26fe90e1c28/src/string.js#L3

D3 is almost never used to handle user input, so these ReDoS vulnerabilities are generally a huge waste of time. But if someone wants to optimize the above regular expression to avoid catastrophic backtracking, that’d be welcome. We made similar improvements in [d3-color 3.1.0](https://github.com/d3/d3-color/releases/tag/v3.1.0).

**Comment by rajkumarg736** [comment]
Hi @curran / @mbostock ,

Vulnerability has been reported as Critical issue in Contrast Security scan and
tried RegExp ` /[-+]?(?:\d+\.?\d*|\.?\d+)(?:[eE][-+]?\d+)?/g` in below online tool, It also says this RegExp is vulnerable.
https://redosdetector.com/?pattern=&caseInsensitive=false&unicode=false
