### ISSUE TITLE
NextJS 15.0.3: Unexpected end of JSON input

### ISSUE THREAD

**Issue by edumorlom** [d3/d3#3950]
As of version 15.0.3 of NextJS, I am getting the following error when building:

> next build

   ▲ Next.js 15.0.3
    - Environments: .env.production
   - Experiments (use with caution):
     · reactCompiler

   Creating an optimized production build ...
Failed to compile.

./src/app/layout.tsx + 33 modules
Unexpected end of JSON input

./node_modules/d3/src/index.js + 159 modules
Unexpected end of JSON input

**Comment by FallingSakura** [comment]
How to solve it? I met this problem too.

**Comment by Fil** [comment]
Maybe ask on the nextjs repo.
