### ISSUE TITLE
union selections?

### ISSUE THREAD

**Issue by mbostock** [d3/d3#399]
I wonder if it would be useful to union selections (or transitions). For example, say you have a barUpdate transition, and another barExit transition. What if you want to apply the same operations to both? Sure, you could extract that code out into a separate function and call it explicitly:

```javascript
var barUpdate = transition(bar)
    .attr("transform", function(d) { return "translate(0," + y(d.State) + ")"; })
    .style("fill-opacity", 1)
    .call(update);

barUpdate.select("text")
    .text(function(d) { return format(d[age]); });

var barExit = transition(bar.exit())
    .style("fill-opacity", 0)
    .remove()
    .call(update);

function update(bar) {
  bar.select("rect").attr("width", function(d) { return x(d[age]); });
  bar.select("text").attr("x", function(d) { return x(d[age]) - 3; });
}
```

But if you could union them, you could just restructure the code slightly:

```javascript
var barUpdate = transition(bar)
    .attr("transform", function(d) { return "translate(0," + y(d.State) + ")"; })
    .style("fill-opacity", 1);

barUpdate.select("text")
    .text(function(d) { return format(d[age]); });

var barExit = transition(bar.exit())
    .style("fill-opacity", 0)
    .remove();

var barAll = barUpdate.union(barExit);

barAll.select("rect")
    .attr("width", function(d) { return x(d[age]); });

barAll.select("text")
    .attr("x", function(d) { return x(d[age]) - 3; });
```

**Comment by jmsrpp** [comment]
Any further thoughts on this? I ran into a situation where I want to add the clicked parent node to a node.enter() selection and union would be quite helpful.

**Comment by tenedor** [comment]
Thanks @aogriffiths for this code, I'm now using it! I'd love to know if this feature is added into the d3 source.

This feature is useful for nested data-bound elements. When I bind new data, I exit entire groups as well as individual children on updated groups, and I want to treat all exiting children the same way whether they're exiting on their own or exiting as part of their parent group. With `union`, I'm able to apply exit logic to the selection `children.exit().union(groups.exit().selectAll('.child'))`.

Fuller example:
```javascript
// data is an array of groups; each group holds an array of children
var data = [{groupId: 0, children: [{childId: 4, parentId: 0}, ...]}, ...];

var groups = d3.selectAll('.group')
    .bind(data, 'groupId');
groups.enter().append('g')
    .classed('group', true);

var children = groups.selectAll('.child')
    .bind(function(group){return group.children;}, 'childId');
children.enter().append('rect')
    .classed('child', true)
    .attr('x', function(child){return child.parentId * 20;})
    .attr('y', function(child){return child.childId * 20;})
    .attr('width', 0)
    .attr('height', 0)
  .transition(700)
    .attr('width', 10)
    .attr('height', 10);

// exit logic for all exiting children
children.exit().union(groups.exit().selectAll('.child')).transition(700)
    .attr('width', 0)
    .attr('height', 0)
    .remove();

groups.exit().transition(700)
    .remove();
```

**Comment by mbostock** [comment]
For 4.0, d3-selection now has [*selection*.merge](https://github.com/d3/d3-selection#selection_merge) for merging selections. However, it’s not the same as the union discussed above: given two selections *a* and *b*, elements from *b* are only merged into the returned selection if the corresponding element from *a* is null. Thus, the merged selection is guaranteed to have the same structure and indexes as *a*. This is intended to support the merging of update with the materialized enter selection after the data-join, now that selections are immutable.

A *selection*.union method would still be possible, though.

**Comment by mbostock** [comment]
Moved to d3/d3-selection#89.
