### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by mkfs** [d3/d3#437]
This is not an actual issue, but a request for additional information that should, ultimately, be searchable by the public.

The license file https://raw.github.com/mbostock/d3/master/LICENSE contains a pretty stock license for standard applications and libraries, but it's a bit confusing when applied to web applications.

When hosting the d3 package, a server "redistributes" it in source code form to a browser client, so condition 1) should apply.

This defeats (to some extent) the purpose of using the minimized/uglified versions of the javascript code. If these were treated as "binary redistribution", then condition 2) should apply.

In this case, however, the copyright notice is buried in a documentation file that may not ever be accessed by the end user, which seems a disservice.

What is the recommended way to incorporate d3 into a proprietary/commercial/non-open web application? Would it suffice to include the copyright notice and a link to the license file (or a copy thereof) as an HTML comment in the pages that use d3?

**Comment by ywarnier** [comment]
Note to self: this is a 3-clause revised BSD license: https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29

**Comment by teetotum** [comment]
We are using D3 in our product. Thanks for making your work available as open source.

Two weeks ago, as I was authoring an entry about third-party-software for our documentation I tried to find out in which category of established open software licenses your license falls.
Identified it (erroneously) as a modified Apache Software License, version 1.1 (the modification would be: deletion of conditions #3 and #5 of the original Apache Software License,Version 1.1, http://www.apache.org/licenses/LICENSE-1.1).

Today I found out (by pure luck) it really is a 3-clause BSD license.

There might be others like me (not really well versed in license stuff) scratching their heads whether this is a MIT license, or something else. Please consider to add a hint that the license is the 3-clause BSD. Again many thanks for a great lib.
