### ISSUE TITLE
d3.format()(-1) yeilds "âˆ’1" with d3.min.js

### ISSUE THREAD

**Issue by braingram** [d3/d3#466]
Running on chromium:
14.0.835.202 (Developer Build 103287 Linux) Ubuntu 11.10

I also tried configuring the Makefile to build on my machine and the same bug occurs when using the custom build d3.min.js

It looks like uglifyjs is converting \u2212 to âˆ’ on

src/format.js line 41

**Comment by alexander-daniel** [comment]
@mbostock, you just saved my bacon. thanks.
