### ISSUE TITLE
d3.distinct() / d3.nest.distinct()

### ISSUE THREAD

**Issue by mbostock** [d3/d3#472]
It'd be nice to have a version of d3.nest for computing the number of distinct keys. Currently, you can do something like this:

``` js
var m = d3.nest().key(function(d) { return d.foo; }).entries(objects).length;
```

However, it would be faster to just compute the distinct count than to populate all the entries. That might look like this:

``` js
var m = d3.nest().key(function(d) { return d.foo; }).distinct(objects);
```

Alternatively, this could be provided as a `d3.distinct(array[, f])` method. It's kind of nice that you can get the same functionality out of a nest operator, though. However, it's a bit weird since the nest operator allows multiple keys; do you want the number of distinct values for all keys? Or just the first key? Probably across all keys.

**Comment by bddicken** [comment]
@mbostock I see this was closed awhile ago, but are you planning on adding something like this to d3? Or is there a function that does something equivalent? I for one would find it very useful. I ended up just implementing it myself in one of the vis projects I am working on, but I would think it a nice API feature.

**Comment by mbostock** [comment]
Well, there’s a slightly more concise version available now due to d3.map:

```js
var m = d3.map(objects, function(d) { return d.foo; }).size();
```

**Comment by bddicken** [comment]
Ah yes, that works very well indeed! Thanks for the tip.
