### ISSUE TITLE
Update examples to use current best practices.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#565]
For example, this:

``` js
var margin = {top: 0, right: 0, bottom: 0, left: 0},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var x = d3.scale.linear()
    .domain([.05, .95])
    .range([0, width]);

var y = d3.scale.linear()
    .range([height, 0]);

var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
```

In detail:
- margin object with `top`, `right`, `bottom`, `left` properties (CW order)
- define width and height as inner width and inner height
- full words rather than single letter variables (`margin` instead of `m`, etc.)
- breakout definition of scales to multi-line statement
- use inverted y-range for consistent positioning
- use nested svg:g within svg:svg for margins

**Comment by tophtucker** [comment]
❤️ to this issue (and to @kitmonisit). got here from repo's insights tab, seeing @kitmonisit's giant commit spike. i've been the beneficiary of this consistency for many years and i'd never seen a visible trace of the effort. i'm sure it can be thankless work compared to adding features or w/e — maybe "patterns" systematically get taken for granted relative to APIs — but it's nice to just see the issue and commits and be reminded of how much conscious organized effort it required!
