### ISSUE TITLE
Support rgba interpolation

### ISSUE THREAD

**Issue by jasondavies** [d3/d3#582]
The default string interpolation results in floating-point values; it might be simple enough to extend d3.rgb to handle an alpha component too.

The spec mentions that [integers should be used](http://www.w3.org/TR/css3-color/#rgba-color).

See also: [this thread](https://groups.google.com/group/d3-js/browse_thread/thread/5766df1568fb0a08).

**Comment by cool-Blue** [comment]
You can easily build a composite interpolator combining `d3.interpolateRgb` and `d3.interpolate` and generalize it using `d3.rgb()`.
For example, this will handle rgba and any other format supported by `d3.rgb()`...
 ```javascript
function interpolateRgba(fromRgba, toRgba) {
	var fromRgb = rgb(fromRgba), toRgb = rgb(toRgba),
			rgbInterp = d3.interpolateRgb(fromRgb.rgb, toRgb.rgb),
			aInterp = d3.interpolate(fromRgb.a, toRgb.a)

	return function (t) {
		var c = d3.rgb(rgbInterp(t)), target = toRgba
		return 'rgba(' + c.r + ', ' + c.g + ', ' + c.b + ', ' + aInterp(t) + ')'
	}
	function rgba(colString) {
		if (colString.search(/rgba/) === 0) {
			return colString
		} else {
			if (colString.search(/rgb/) === 0) {
				return colString.replace(/rgb(.*)\)/, 'rgba$1, 1.0)')
			}
		}
	}
	function rgb(colString) {
		if (colString.search(/rgba/) === 0) {
			var regExp = /rgba(.*),\s?(.*)\)/,
			results = regExp.exec(colString)
			return {
				rgba: results[0],
				rgb: 'rgb' + results[1] + ')',
				a: results[2]
			}
		} else {
			if (colString.search(/rgb/) === 0) {
				return {
					rgba: null,
					rgb: colString,
					a: 1.0
				}
			} else {
				var c = d3.rgb(colString)

				return {
					rgba: null,
					rgb: 'rgb(' + c.r + ',' + c.g + ',' + c.b + ')',
					a: 1.0
				}
			}
		}
	}
}
// example...
		selection.transition().duration(1000)
			.styleTween('background-color', function (d, i, a) {
				return interpolateRgba(a, 'rgba(255, 255, 0, 0.8)')
			})
			.styleTween('color', function (d, i, a) {
				return interpolateRgba(a, 'yellow')
			})
			.styleTween('outline-color', function (d, i, a) {
				return interpolateRgba(a, '#ccc')
			})

```

**Comment by ericsoco** [comment]
I just stumbled across this after a half hour of debugging -- my shapes were mysteriously disappearing as soon as they started their transition, and I eventually tracked it down to this.

Is `rgba` widely supported enough now that this should be reconsidered? Or, at the very least, perhaps `d3` can warn when a `style` or `attr` containing an `rgba` key is `transition()`ed...

**Comment by PatrickKing** [comment]
This just bit me today. [caniuse](http://caniuse.com/#search=rgba) shows RGBA as being supported in all modern browsers, with the only notable holdout being IE8.

**Comment by mbostock** [comment]
D3 4.0 supports RGBA interpolation. See [d3-color](https://github.com/d3/d3-color) and [d3-interpolate](https://github.com/d3/d3-interpolate).
