### ISSUE TITLE
CSSStyleDeclaration undefined in IE9 (Chords)

### ISSUE THREAD

**Issue by jvhouten** [d3/d3#599]
Dear,

For a project for my Master in Industrial Ecology I made use of d3 to create chord diagrams. It works perfectly fine in all browsers exept IE9. In IE10 it does work. Reading through the issues it seems as if it should have been resolved and since I am not a programmer I do not know how to solve this. Could you be able to help?

The website were it is embedded is: http://resourceatlas.tudelft.nl/tools/chords.html

Thanks in advance,
Jeroen

The error message:
Message: 'CSSStyleDeclaration' is undefined
Line: 7
Char: 3
Code: 0
URI: http://resourceatlas.tudelft.nl/css/chord_diagram/d3.v2.js

**Comment by conradbm** [comment]
Thank you, this solution worked!!
