### ISSUE TITLE
Tree traversal.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#6]
More tree traversal methods are needed. Potentially:
- `parent` - select parent node.
- `previous` - select previous sibling.
- `next` - select next sibling.
- `firstChild` - select first child.
- `lastChild` - select last child.
- `children` - select all (immediate) children.

Some convenience filtering method might also be useful:
- `first` - filter selection to the first node.
- `last` - filter selection to the last node.
- `slice(start[, end])` - filter selection to the given subset by index.

**Comment by kanitw** [comment]
Looks like it's undocumented that we can pass arbitrary function to select and selectAll.
