### ISSUE TITLE
Weird behaviour from d3. SVG doesn't show.

### ISSUE THREAD

**Issue by interstar** [d3/d3#638]
I'm new to d3 and trying to produce a variant on the "three little circles" demo, but using circles to plot x,y co-ordinates.

However, when I create a number of circles with d3 I don't see anything on my page. Here's the SVG that was created by d3 and which I copied from Firebug.

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
   <circle cx="82" cy="306" r="10" style="fill: #6666ff; stroke: #0000ff; stroke-width: 1px; "></circle>
   <circle cx="226" cy="216" r="10" style="fill: #6666ff; stroke: #0000ff; stroke-width: 1px; "></circle>
   <circle cx="399" cy="444" r="10" style="fill: #6666ff; stroke: #0000ff; stroke-width: 1px; "></circle>
   <circle cx="269" cy="598" r="10" style="fill: #6666ff; stroke: #0000ff; stroke-width: 1px; "></circle>
</svg>
```

If I manually paste that code back into my page, then I can see the circles perfectly well.

Looking at the DOM in Firebug I see that the circle tags in the d3 generated svg tag (but not the svg tag itself) are greyed out, as if Firefox knows they are hidden for some reason. The manually pasted circles are not greyed out.

I can't think why there should be a difference given that the SVG is identical. But I'm wondering if it's some mode or something that d3 creates tags in. Anyone got any ideas?

**Comment by tweinfeld** [comment]
I have the some problem. When the SVG element is not created by d3, nothing appears on screen, even though the d3 appears to have populated it correctly.
For instance, if I use `d3.select($jQuerySVGSelector[0]).append('circle').attr(..)` a circle will _not_ appear.

**Comment by mbostock** [comment]
@tweinfeld If you created the SVG element with jQuery, it probably doesn’t have the SVG namespace, so it’s not really an svg:svg element. You need to use createElementNS with the appropriate namespace, or D3.

**Comment by tweinfeld** [comment]
@mbostock - Thanks! that solves the problem.

**Comment by praveen-jegan** [comment]
Though an old post, I would like to share my mistake..
I too had a same kind of problem where `cirlce` `svg` components were not showing up in Firefox.   The problem is I was adding the `r`(radius) attribute via `class`(external stylesheet) and thereby not working in Firefox.  Once I directly added in the 'svg' component via JS the `circle` were showing perfectly in FF.

**Comment by lgrkvst** [comment]
Yaaaay!! createElementNS made all the difference for me as well!

I still can't help thinking I'm going about this the wrong way. I started with `g.append("circle");`, but discovered I _sometimes_ wanted to append a `rect`. My solution was `g.append(f)`, in which `f` would return a `circle` _or_ a `rect`, both created using plain old DOM operations.

How would I go about if I wanted to do this using d3 operations?

**Comment by chazzmoney** [comment]
Wanted to share what made the difference for me for the svg to start showing up:

`document.createElementNS("http://www.w3.org/2000/svg", "svg")`
