### ISSUE TITLE
D3 examples with JSON data - error -TypeError: 'null' is not an object (evaluating 'collection.features')

### ISSUE THREAD

**Issue by ns-1m** [d3/d3#673]
It seems that almost all the D3 examples with JSON data have this error.

TypeError: 'null' is not an object (evaluating 'collection.features')

For example, albers projection.

d3.json("../data/us-states.json", function(collection) {
  d3.select("#states")
    .selectAll("path")
      .data(collection.features)       <--------line 56

The error is in   .data(collection.features) line 56.

This is using Safari 5.1.7 in Mac OS and also in Firefox 3.x.

Thanks.

Edit: This example works.

http://bl.ocks.org/2374239

However, the D3 examples with JSON data does not work.

**Comment by coderextreme** [comment]
digitallyinfected:  Read about the FileReader answer on this page: http://stackoverflow.com/questions/7346563/loading-local-json-file  I've been testing this and it seems to work in Chrome.  What it does is load the file into the web page with an input tag.  I am testing with D3.js and X3DOM right now.  I'm getting more JSON examples, and will report more as I progress.  This might be a way to load DOM as JSON from a local file system, which would revolutionize how D3.js is typically managed (handcrafted JavaScript will make way to JSON).
