### ISSUE TITLE
Format strings should be overridable.

### ISSUE THREAD

**Issue by mbostock** [d3/d3#750]
d3.time.format contains a number of locale-specific strings (month names and day names, also the locale default formats for %x and %X), as well as regular expressions derived from these names. It would be nice to be able to customize these for a different locale.

d3.format also would benefit from localization. For example, you might want to format 1234.56 as "1 234,56" in France and  "1.234,56" in Germany. It’s possible to change the thousands group separator (currently a comma, ","), but the period comes from JavaScript’s built-in number formatting. So this might only be possible by substituting a custom number format implementation or by post processing to swap characters (e.g., "," ↦ " " and "." ↦ ","). d3.format does not currently support parsing so this simplifies the problem somewhat.

Doing this “properly” might be out-of-scope of D3; see for example [jquery/globalize](https://github.com/jquery/globalize), which is a much more extensive library for localization.

**Comment by ankakusu** [comment]
+1 It is working.
