### ISSUE TITLE
disabling an event while a transition is in progress?

### ISSUE THREAD

**Issue by janwillemtulp** [d3/d3#77]
Is it possible to disable an event while a transition is in progress? For instance, I have a mouseover event and a circle moves for 4000 milliseconds. Is it possible to disable the mouseover event while the circle is moving, and then re-enable the event when the transition is done?

**Comment by syoels** [comment]
Hey @mbostock ! Your solution works perfectly. 
What would you do if you had to disable only some of the pointer events, for example disable "hover" but keep the "drag" events working?
