### ISSUE TITLE
Create DOM element without appending it?

### ISSUE THREAD

**Issue by zacwitte** [d3/d3#825]
Is it possible to create a DOM element without appending it? In building an SVG tree I want to create a `<g>` element, add a bunch of children to it, then append the entire tree at once. I believe this is more efficient than calling `append()` right after `select().data().enter()` which would cause the browser to do more redraws than necessary.

**Comment by fredefox** [comment]
Hello @mbostock I'm very interested in hearing your feedback on this.

**Comment by mbostock** [comment]
You haven’t set a width and height attribute on your svg element, and you haven’t specified the appropriate namespace in conjunction with document.createElementNS when creating the svg element. Another strategy you could consider is to remove the element from the DOM immediately after creating it:

```js
var svg = d3.select("body").append("svg")
    .remove()
    .attr("width", 400)
    .attr("height", 400);

svg.append("circle")
    .attr("r", 200);

document.body.appendChild(svg.node());
```

**Comment by hughes** [comment]
@fredefox you may need to create a namespace-specific DOM node. 

    var svg = document.createElementNS("http://www.w3.org/2000/svg","svg");

**Comment by mootari** [comment]
Just ran into this myself. For SVG groups the syntax has to be:
`var group = d3.select(document.createElementNS('http://www.w3.org/2000/svg', 'g'));`

Simply using `document.createElement('g')` will create the element, but it won't render.

**Comment by ming-codes** [comment]
Yup, @mootari has the correct syntax. But you can shorten it.

```js
document.createElementNS(d3.ns.prefix.svg, 'g')
```

Still, I wish there's an easier way.

**Comment by mootari** [comment]
In v4 it's either `d3.namespaces.svg` or `d3.namespace('svg').space`.

**Comment by skibulk** [comment]
I had to do this in order to support percentage widths on my SVG element:

```
var svgDom = document.createElementNS("http://www.w3.org/2000/svg", "svg");
svgDom.setAttributeNS("http://www.w3.org/2000/xmlns/", "xmlns:xlink", "http://www.w3.org/1999/xlink");
svg = d3.select(svgDom)
	.attr("class", "chart")
	.attr("width", "100%")
	.attr("height", "100%");
```

**Comment by PaulineBock** [comment]
Hello, I wanted to know, is it possible to create a SVG element in a function,  without appending it directly to the DOM, and then return this svg, and get back it in another function where now, we can append this svg to the DOM ? (I'm actually working in javascript scripts, but I'm rather new in programmation). Thank's for your answers.

**Comment by mbostock** [comment]
D3 5.0 added [d3.create](https://github.com/d3/d3-selection/blob/master/README.md#create) for creating a selection from a new detached DOM element. So you could say:

```js
function createSvg() {
  const svg = d3.create("svg");
  // Add stuff to the SVG element here.
  return svg.node();
}

document.body.appendChild(createSvg());
```

**Comment by PaulineBock** [comment]
Thank's a lot ! I will try this !

2018-04-13 16:40 GMT+02:00 Mike Bostock <notifications@github.com>:
