### ISSUE TITLE
RangeError: Maximum call stack size exceeded when using d3.layout.force tick()

### ISSUE THREAD

**Issue by jbilcke** [d3/d3#892]
Hi,

I tried to run the force layout on a large graph (5000 nodes),
since Barnes-Hut is supposed to make such sizes possible,

however I encountered a wild uncaught RangeError:

  Maximum call stack size exceeded
  l
  k
  l
  k
  l
  ...

Is there another solution to this? Where in d3.js is such pattern used, so maybe I could try to fix it? 

(this exception is not bound to a stack trace in the debug console, and just pop out of nowhere, so I don't know where are the problematic lines)

Thank you,
Julian

**Comment by jarandaf** [comment]
@jbilcke were you able to find a solution?

**Comment by jbilcke** [comment]
@jarandaf it was quite a long time ago, but I think that in my case it was indeed an issue with some x/y values

One can log / fix them using something like `value = (isNaN(value) || ! isFinite(value)) ? 0 : value;`


However if your issue is really related to the graph size, and you want to stick to d3, maybe you could try to port another graph layout algorithm to d3.js, for instance the ForceAtlas algorithm from Gephi / Sigma projects, because it has some special optimizations for large networks (this version is designed to run inside a webworker, so with a bit of hacking it could be used with another library: https://github.com/jacomyal/sigma.js/blob/master/plugins/sigma.layout.forceAtlas2/worker.js )

**Comment by mbostock** [comment]
D3’s force layout uses the same Barnes–Hut approximation, so it should have comparable performance.
