### ISSUE TITLE
Edge crossing with Reingold-Tilford radial tree layout

### ISSUE THREAD

**Issue by adriaanbaelus** [d3/d3#973]
Disclaimer: This is my first time using d3, or doing any real data visualization, so please feel free to correct me or point me to documentation if this is incorrect or trivial.

While playing around with the radial tree layout, I've noticed in some edge cases the links cross. I'm not sure if this is a bug or not. According to http://hci.stanford.edu/courses/cs448b/f09/lectures/CS448B-20091021-GraphsAndTrees.pdf Reingold-Tilford shouldn't have edge crossings, but I'm not sure if that's a reliable source?

An example of what I am talking about: http://bl.ocks.org/4344931
I would've expected that same layout, but with child B at 180° opposite to child A.

If this behaviour is to be expected from the algorithm, is there some way to take this particular situation into account (perhaps by modifying the separation function)?

**Comment by wxingheng** [comment]
I seem to have found a solution. Calculate through the layout layout to determine if any of the deepest set of adjacent nodes have a range greater than 50 degrees, and rescale our size. I managed to avoid the confusion or crossover caused by abnormal data
