### ISSUE TITLE
Pinch-in and pinch-out support on d3?

### ISSUE THREAD

**Issue by kongch** [d3/d3#989]
Hi ,

I have read the posts about the pinch issue. I wonder if there is a solution or plan to work on the pinch zoom support on d3? If not, can you recommend a work around solution?

I'm using d3.js to create a zoom-able network visualization on Firefox which will run on a touch screen. Everything is perfect but the only problem is the pinch-zoom event. We really need to get this working. It will be great if you can show me some direction to be started

**Comment by ezyang** [comment]
Hello, I verified that on Windows 8.1, Metro Internet Explorer 11, using d3.js's zoom handler along with `touch-action` and `-ms-touch-action` (having tried setting it to both `none` and `manipulation`) doesn't seem to work: the default full page pan/zoom is still in effect. So maybe this should be reopened?

The example code is here: http://web.mit.edu/~ezyang/Public/latency/?11
